<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Print Label ID'),
    'required' => TRUE,
    'where' => 'civicrm_print_label.id',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.4',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Title'),
    'description' => ts('User title for this label layout'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_print_label.title',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'add' => '4.4',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Name'),
    'description' => ts('variable name/programmatic handle for this field.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_print_label.name',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'add' => '4.4',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Description'),
    'description' => ts('Description of this label layout'),
    'where' => 'civicrm_print_label.description',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'html' => [
      'label' => ts("Description"),
    ],
    'add' => '4.4',
  ],
  'label_format_name' => [
    'name' => 'label_format_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Label Format'),
    'description' => ts('This refers to name column of civicrm_option_value row in name_badge option group'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_print_label.label_format_name',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'name_badge',
      'optionEditPath' => 'civicrm/admin/options/name_badge',
    ],
    'add' => '4.4',
  ],
  'label_type_id' => [
    'name' => 'label_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Label Type'),
    'description' => ts('Implicit FK to civicrm_option_value row in NEW label_type option group'),
    'where' => 'civicrm_print_label.label_type_id',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'label_type',
      'optionEditPath' => 'civicrm/admin/options/label_type',
    ],
    'add' => '4.4',
  ],
  'data' => [
    'name' => 'data',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Data'),
    'description' => ts('contains json encode configurations options'),
    'where' => 'civicrm_print_label.data',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_JSON,
    'html' => [
      'label' => ts("Data"),
    ],
    'add' => '4.4',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Label is Default?'),
    'description' => ts('Is this default?'),
    'required' => TRUE,
    'where' => 'civicrm_print_label.is_default',
    'default' => '1',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '4.4',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Label Is Active?'),
    'description' => ts('Is this option active?'),
    'required' => TRUE,
    'where' => 'civicrm_print_label.is_active',
    'default' => '1',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.4',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Label Reserved?'),
    'description' => ts('Is this reserved label?'),
    'required' => TRUE,
    'where' => 'civicrm_print_label.is_reserved',
    'default' => '1',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'add' => '4.4',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to civicrm_contact, who created this label layout'),
    'where' => 'civicrm_print_label.created_id',
    'table_name' => 'civicrm_print_label',
    'entity' => 'PrintLabel',
    'bao' => 'CRM_Core_DAO_PrintLabel',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '4.4',
  ],
  ];
  
