<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Confirmation ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_confirm.id',
    'table_name' => 'civicrm_mailing_event_confirm',
    'entity' => 'MailingEventConfirm',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventConfirm',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'event_subscribe_id' => [
    'name' => 'event_subscribe_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Subscribe ID'),
    'description' => ts('FK to civicrm_mailing_event_subscribe'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_confirm.event_subscribe_id',
    'table_name' => 'civicrm_mailing_event_confirm',
    'entity' => 'MailingEventConfirm',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventConfirm',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventSubscribe',
    'html' => [
      'label' => ts("Mailing Subscribe"),
    ],
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Confirm Timestamp'),
    'description' => ts('When this confirmation event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_confirm.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_confirm',
    'entity' => 'MailingEventConfirm',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventConfirm',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
