<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Profile Field ID'),
    'description' => ts('Unique table ID'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.id',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'uf_group_id' => [
    'name' => 'uf_group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Profile ID'),
    'description' => ts('Which form does this field belong to.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.uf_group_id',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_UFGroup',
    'html' => [
      'type' => 'Select',
      'label' => ts("Profile"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_uf_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '1.1',
  ],
  'field_name' => [
    'name' => 'field_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Profile Field Name'),
    'description' => ts('Name for CiviCRM field which is being exposed for sharing.'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_uf_field.field_name',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Core_BAO_UFField::getAvailableFieldOptions',
    ],
    'add' => '1.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Field Is Active'),
    'description' => ts('Is this field currently shareable? If false, hide the field for all sharing contexts.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.is_active',
    'default' => '1',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.1',
  ],
  'is_view' => [
    'name' => 'is_view',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Is View Only'),
    'description' => ts('the field is view only and not editable in user forms.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.is_view',
    'default' => '0',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'is_required' => [
    'name' => 'is_required',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Field Is Required'),
    'description' => ts('Is this field required when included in a user or registration form?'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.is_required',
    'default' => '0',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('Controls field display order when user framework fields are displayed in registration and account editing forms.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.weight',
    'default' => '1',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'help_post' => [
    'name' => 'help_post',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Profile Field Post Help'),
    'description' => ts('Description and/or help text to display after this field.'),
    'where' => 'civicrm_uf_field.help_post',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 1,
    'add' => '1.1',
  ],
  'help_pre' => [
    'name' => 'help_pre',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Profile Field Pre Help'),
    'description' => ts('Description and/or help text to display before this field.'),
    'where' => 'civicrm_uf_field.help_pre',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 1,
    'add' => '3.2',
  ],
  'visibility' => [
    'name' => 'visibility',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Profile Field Visibility'),
    'description' => ts('In what context(s) is this field visible.'),
    'maxlength' => 32,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_uf_field.visibility',
    'default' => 'User and User Admin Only',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::ufVisibility',
    ],
    'add' => '1.1',
  ],
  'in_selector' => [
    'name' => 'in_selector',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Field Is a Filter'),
    'description' => ts('Is this field included as a column in the selector table?'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.in_selector',
    'default' => '0',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '1.2',
  ],
  'is_searchable' => [
    'name' => 'is_searchable',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Field Is Searchable'),
    'description' => ts('Is this field included search form of profile?'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.is_searchable',
    'default' => '0',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'location_type_id' => [
    'name' => 'location_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Location Type ID'),
    'description' => ts('Location type of this mapping, if required'),
    'where' => 'civicrm_uf_field.location_type_id',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_LocationType',
    'html' => [
      'label' => ts("Location Type"),
    ],
    'add' => '1.3',
  ],
  'phone_type_id' => [
    'name' => 'phone_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Profile Field Phone Type'),
    'description' => ts('Phone Type ID, if required'),
    'where' => 'civicrm_uf_field.phone_type_id',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'phone_type',
      'optionEditPath' => 'civicrm/admin/options/phone_type',
    ],
    'add' => '2.2',
  ],
  'website_type_id' => [
    'name' => 'website_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Profile Field Website Type'),
    'description' => ts('Website Type ID, if required'),
    'where' => 'civicrm_uf_field.website_type_id',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'website_type',
      'optionEditPath' => 'civicrm/admin/options/website_type',
    ],
    'add' => '4.5',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Profile Field Label'),
    'description' => ts('To save label for fields.'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_uf_field.label',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 1,
    'add' => '1.4',
  ],
  'field_type' => [
    'name' => 'field_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Profile Field Type'),
    'description' => ts('This field saves field type (ie individual,household.. field etc).'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_uf_field.field_type',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Field Is Reserved'),
    'description' => ts('Is this field reserved for use by some other CiviCRM functionality?'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '3.0',
  ],
  'is_multi_summary' => [
    'name' => 'is_multi_summary',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Field Supports Multiple'),
    'description' => ts('Include in multi-record listing?'),
    'required' => TRUE,
    'where' => 'civicrm_uf_field.is_multi_summary',
    'default' => '0',
    'table_name' => 'civicrm_uf_field',
    'entity' => 'UFField',
    'bao' => 'CRM_Core_BAO_UFField',
    'localizable' => 0,
    'add' => '4.3',
  ],
  ];
  
