<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('PCP Block ID'),
    'description' => ts('PCP block ID'),
    'required' => TRUE,
    'where' => 'civicrm_pcp_block.id',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.2',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_pcp_block.entity_table',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity'),
    'description' => ts('FK to civicrm_contribution_page.id OR civicrm_event.id'),
    'required' => TRUE,
    'where' => 'civicrm_pcp_block.entity_id',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'target_entity_type' => [
    'name' => 'target_entity_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Target Entity'),
    'description' => ts('The type of entity that this pcp targets'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_pcp_block.target_entity_type',
    'default' => 'contribute',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'target_entity_id' => [
    'name' => 'target_entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Target Entity ID'),
    'description' => ts('The entity that this pcp targets'),
    'required' => TRUE,
    'where' => 'civicrm_pcp_block.target_entity_id',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'supporter_profile_id' => [
    'name' => 'supporter_profile_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Supporter Profile ID'),
    'description' => ts('FK to civicrm_uf_group.id. Does Personal Campaign Page require manual activation by administrator? (is inactive by default after setup)?'),
    'where' => 'civicrm_pcp_block.supporter_profile_id',
    'default' => NULL,
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_UFGroup',
    'html' => [
      'label' => ts("Supporter Profile"),
    ],
    'add' => '2.2',
  ],
  'owner_notify_id' => [
    'name' => 'owner_notify_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Owner Notification'),
    'description' => ts('FK to civicrm_option_group with name = PCP owner notifications'),
    'where' => 'civicrm_pcp_block.owner_notify_id',
    'default' => '0',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'html' => [
      'type' => 'Radio',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'pcp_owner_notify',
      'optionEditPath' => 'civicrm/admin/options/pcp_owner_notify',
    ],
    'add' => '4.6',
  ],
  'is_approval_needed' => [
    'name' => 'is_approval_needed',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Approval Required?'),
    'description' => ts('Does Personal Campaign Page require manual activation by administrator? (is inactive by default after setup)?'),
    'required' => TRUE,
    'where' => 'civicrm_pcp_block.is_approval_needed',
    'default' => '0',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'is_tellfriend_enabled' => [
    'name' => 'is_tellfriend_enabled',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Tell a Friend Enabled?'),
    'description' => ts('Does Personal Campaign Page allow using tell a friend?'),
    'required' => TRUE,
    'where' => 'civicrm_pcp_block.is_tellfriend_enabled',
    'default' => '0',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'tellfriend_limit' => [
    'name' => 'tellfriend_limit',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Tell A Friend Limit'),
    'description' => ts('Maximum recipient fields allowed in tell a friend'),
    'where' => 'civicrm_pcp_block.tellfriend_limit',
    'default' => NULL,
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'link_text' => [
    'name' => 'link_text',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Link Text'),
    'description' => ts('Link text for PCP.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_pcp_block.link_text',
    'default' => NULL,
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 1,
    'add' => '2.2',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Enabled?'),
    'description' => ts('Is Personal Campaign Page Block enabled/active?'),
    'required' => TRUE,
    'where' => 'civicrm_pcp_block.is_active',
    'default' => '1',
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '2.2',
  ],
  'notify_email' => [
    'name' => 'notify_email',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Notification Email'),
    'description' => ts('If set, notification is automatically emailed to this email-address on create/update Personal Campaign Page'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_pcp_block.notify_email',
    'default' => NULL,
    'table_name' => 'civicrm_pcp_block',
    'entity' => 'PCPBlock',
    'bao' => 'CRM_PCP_BAO_PCPBlock',
    'localizable' => 0,
    'add' => '2.2',
  ],
  ];
  
