<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from xml/schema/CRM/ACL/ACLCache.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d7c69e5c465c096d3a8af87dbf2ae013)
 */

/**
 * Database access object for the ACLCache entity.
 */
class CRM_ACL_DAO_ACLCache_Fields {

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Cache ID'),
          'description' => ts('Unique table ID'),
          'required' => TRUE,
          'where' => 'civicrm_acl_cache.id',
          'table_name' => 'civicrm_acl_cache',
          'entity' => 'ACLCache',
          'bao' => 'CRM_ACL_DAO_ACLCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '1.6',
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contact ID'),
          'description' => ts('Foreign Key to Contact'),
          'where' => 'civicrm_acl_cache.contact_id',
          'table_name' => 'civicrm_acl_cache',
          'entity' => 'ACLCache',
          'bao' => 'CRM_ACL_DAO_ACLCache',
          'localizable' => 0,
          'html' => [
            'type' => 'EntityRef',
            'label' => ts("Contact"),
          ],
          'add' => '1.6',
        ],
        'acl_id' => [
          'name' => 'acl_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ACL ID'),
          'description' => ts('Foreign Key to ACL'),
          'required' => TRUE,
          'where' => 'civicrm_acl_cache.acl_id',
          'table_name' => 'civicrm_acl_cache',
          'entity' => 'ACLCache',
          'bao' => 'CRM_ACL_DAO_ACLCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_ACL_DAO_ACL',
          'html' => [
            'label' => ts("ACL"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_acl',
            'keyColumn' => 'id',
            'labelColumn' => 'name',
          ],
          'add' => '1.6',
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Cache Modified Date'),
          'description' => ts('When was this cache entry last modified'),
          'required' => FALSE,
          'where' => 'civicrm_acl_cache.modified_date',
          'table_name' => 'civicrm_acl_cache',
          'entity' => 'ACLCache',
          'bao' => 'CRM_ACL_DAO_ACLCache',
          'localizable' => 0,
          'add' => '1.6',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

}
