<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Cache ID'),
    'description' => ts('Unique table ID'),
    'required' => TRUE,
    'where' => 'civicrm_acl_cache.id',
    'table_name' => 'civicrm_acl_cache',
    'entity' => 'ACLCache',
    'bao' => 'CRM_ACL_DAO_ACLCache',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.6',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('Foreign Key to Contact'),
    'where' => 'civicrm_acl_cache.contact_id',
    'table_name' => 'civicrm_acl_cache',
    'entity' => 'ACLCache',
    'bao' => 'CRM_ACL_DAO_ACLCache',
    'localizable' => 0,
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Contact"),
    ],
    'add' => '1.6',
  ],
  'acl_id' => [
    'name' => 'acl_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('ACL ID'),
    'description' => ts('Foreign Key to ACL'),
    'required' => TRUE,
    'where' => 'civicrm_acl_cache.acl_id',
    'table_name' => 'civicrm_acl_cache',
    'entity' => 'ACLCache',
    'bao' => 'CRM_ACL_DAO_ACLCache',
    'localizable' => 0,
    'FKClassName' => 'CRM_ACL_DAO_ACL',
    'html' => [
      'label' => ts("ACL"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_acl',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '1.6',
  ],
  'modified_date' => [
    'name' => 'modified_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Cache Modified Date'),
    'description' => ts('When was this cache entry last modified'),
    'required' => FALSE,
    'where' => 'civicrm_acl_cache.modified_date',
    'table_name' => 'civicrm_acl_cache',
    'entity' => 'ACLCache',
    'bao' => 'CRM_ACL_DAO_ACLCache',
    'localizable' => 0,
    'add' => '1.6',
  ],
  ];
  
