<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which site is this mailing for'),
    'where' => 'civicrm_mailing.domain_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '3.4',
  ],
  'header_id' => [
    'name' => 'header_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Header ID'),
    'description' => ts('FK to the header component.'),
    'where' => 'civicrm_mailing.header_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingComponent',
    'html' => [
      'label' => ts("Header"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_mailing_component',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
      'condition' => 'component_type = "Header"',
    ],
    'add' => NULL,
  ],
  'footer_id' => [
    'name' => 'footer_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Footer ID'),
    'description' => ts('FK to the footer component.'),
    'where' => 'civicrm_mailing.footer_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingComponent',
    'html' => [
      'label' => ts("Footer"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_mailing_component',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
      'condition' => 'component_type = "Footer"',
    ],
    'add' => NULL,
  ],
  'reply_id' => [
    'name' => 'reply_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Reply ID'),
    'description' => ts('FK to the auto-responder component.'),
    'where' => 'civicrm_mailing.reply_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingComponent',
    'html' => [
      'label' => ts("Reply"),
    ],
    'add' => NULL,
  ],
  'unsubscribe_id' => [
    'name' => 'unsubscribe_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Unsubscribe ID'),
    'description' => ts('FK to the unsubscribe component.'),
    'where' => 'civicrm_mailing.unsubscribe_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingComponent',
    'html' => [
      'label' => ts("Unsubscribe"),
    ],
    'add' => NULL,
  ],
  'resubscribe_id' => [
    'name' => 'resubscribe_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Resubscribe'),
    'where' => 'civicrm_mailing.resubscribe_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'add' => NULL,
  ],
  'optout_id' => [
    'name' => 'optout_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Opt Out ID'),
    'description' => ts('FK to the opt-out component.'),
    'where' => 'civicrm_mailing.optout_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingComponent',
    'html' => [
      'label' => ts("Opt Out"),
    ],
    'add' => NULL,
  ],
  'mailing_name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Name'),
    'description' => ts('Mailing Name.'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing.name',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => NULL,
  ],
  'mailing_type' => [
    'name' => 'mailing_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Type'),
    'description' => ts('differentiate between standalone mailings, A/B tests, and A/B final-winner'),
    'maxlength' => 32,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_mailing.mailing_type',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mailing_PseudoConstant::mailingTypes',
    ],
    'add' => '4.6',
  ],
  'from_name' => [
    'name' => 'from_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing From Name'),
    'description' => ts('From Header of mailing'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing.from_name',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => NULL,
  ],
  'from_email' => [
    'name' => 'from_email',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing From Email'),
    'description' => ts('From Email of mailing'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing.from_email',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => NULL,
  ],
  'replyto_email' => [
    'name' => 'replyto_email',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Replyto Email'),
    'description' => ts('Reply-To Email of mailing'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing.replyto_email',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
      'label' => ts("Reply-To Email"),
    ],
    'add' => NULL,
  ],
  'template_type' => [
    'name' => 'template_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Template Type'),
    'description' => ts('The language/processing system used for email templates.'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_mailing.template_type',
    'default' => 'traditional',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Mailing_BAO_Mailing::getTemplateTypeNames',
    ],
    'add' => '4.7.16',
  ],
  'template_options' => [
    'name' => 'template_options',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Template Options (JSON)'),
    'description' => ts('Advanced options used by the email templating system. (JSON encoded)'),
    'where' => 'civicrm_mailing.template_options',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_JSON,
    'add' => '4.7.16',
  ],
  'subject' => [
    'name' => 'subject',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Subject'),
    'description' => ts('Subject of mailing'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing.subject',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
      'label' => ts("Subject"),
    ],
    'add' => NULL,
  ],
  'body_text' => [
    'name' => 'body_text',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Body Text'),
    'description' => ts('Body of the mailing in text format.'),
    'where' => 'civicrm_mailing.body_text',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'label' => ts("Body Text"),
    ],
    'add' => NULL,
  ],
  'body_html' => [
    'name' => 'body_html',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Body Html'),
    'description' => ts('Body of the mailing in html format.'),
    'where' => 'civicrm_mailing.body_html',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'label' => ts("Body HTML"),
    ],
    'add' => NULL,
  ],
  'url_tracking' => [
    'name' => 'url_tracking',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Url Tracking'),
    'description' => ts('Should we track URL click-throughs for this mailing?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.url_tracking',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Url Tracking"),
    ],
    'add' => NULL,
  ],
  'forward_replies' => [
    'name' => 'forward_replies',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Forward Replies'),
    'description' => ts('Should we forward replies back to the author?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.forward_replies',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Forward Replies"),
    ],
    'add' => NULL,
  ],
  'auto_responder' => [
    'name' => 'auto_responder',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Auto Responder'),
    'description' => ts('Should we enable the auto-responder?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.auto_responder',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Auto Responder"),
    ],
    'add' => NULL,
  ],
  'open_tracking' => [
    'name' => 'open_tracking',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Track Mailing?'),
    'description' => ts('Should we track when recipients open/read this mailing?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.open_tracking',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'add' => NULL,
  ],
  'is_completed' => [
    'name' => 'is_completed',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Mailing Completed'),
    'description' => ts('Has at least one job associated with this mailing finished?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.is_completed',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => NULL,
  ],
  'msg_template_id' => [
    'name' => 'msg_template_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Message Template ID'),
    'description' => ts('FK to the message template.'),
    'where' => 'civicrm_mailing.msg_template_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_MessageTemplate',
    'html' => [
      'label' => ts("Message Template"),
    ],
    'add' => NULL,
  ],
  'override_verp' => [
    'name' => 'override_verp',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Override Verp'),
    'description' => ts('Overwrite the VERP address in Reply-To'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.override_verp',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Overwrite VERP"),
    ],
    'add' => '2.2',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to Contact ID who first created this mailing'),
    'where' => 'civicrm_mailing.created_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Creator"),
    ],
    'add' => NULL,
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Created Date'),
    'description' => ts('Date and time this mailing was created.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing.created_date',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '3.0',
  ],
  'mailing_modified_date' => [
    'name' => 'modified_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Modified Date'),
    'description' => ts('When the mailing (or closely related entity) was created or modified or deleted.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing.modified_date',
    'export' => TRUE,
    'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'label' => ts("Modified Date"),
    ],
    'readonly' => TRUE,
    'add' => '4.7',
  ],
  'scheduled_id' => [
    'name' => 'scheduled_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Scheduled By Contact ID'),
    'description' => ts('FK to Contact ID who scheduled this mailing'),
    'where' => 'civicrm_mailing.scheduled_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Scheduled By"),
    ],
    'add' => NULL,
  ],
  'scheduled_date' => [
    'name' => 'scheduled_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Scheduled Date'),
    'description' => ts('Date and time this mailing was scheduled.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing.scheduled_date',
    'default' => NULL,
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '3.3',
  ],
  'approver_id' => [
    'name' => 'approver_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Approved By Contact ID'),
    'description' => ts('FK to Contact ID who approved this mailing'),
    'where' => 'civicrm_mailing.approver_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Approved By"),
    ],
    'add' => NULL,
  ],
  'approval_date' => [
    'name' => 'approval_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Approved Date'),
    'description' => ts('Date and time this mailing was approved.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing.approval_date',
    'default' => NULL,
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '3.3',
  ],
  'approval_status_id' => [
    'name' => 'approval_status_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Approval Status'),
    'description' => ts('The status of this mailing. Values: none, approved, rejected'),
    'where' => 'civicrm_mailing.approval_status_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'mail_approval_status',
      'optionEditPath' => 'civicrm/admin/options/mail_approval_status',
    ],
    'add' => '3.3',
  ],
  'approval_note' => [
    'name' => 'approval_note',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Approval Note'),
    'description' => ts('Note behind the decision.'),
    'where' => 'civicrm_mailing.approval_note',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '3.3',
  ],
  'is_archived' => [
    'name' => 'is_archived',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Mailing Archived?'),
    'description' => ts('Is this mailing archived?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.is_archived',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '2.2',
  ],
  'visibility' => [
    'name' => 'visibility',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Visibility'),
    'description' => ts('In what context(s) is the mailing contents visible (online viewing)'),
    'maxlength' => 40,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_mailing.visibility',
    'default' => 'Public Pages',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::groupVisibility',
    ],
    'add' => '3.3',
  ],
  'campaign_id' => [
    'name' => 'campaign_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Campaign ID'),
    'description' => ts('The campaign for which this mailing has been initiated.'),
    'where' => 'civicrm_mailing.campaign_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Campaign_DAO_Campaign',
    'component' => 'CiviCampaign',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Campaign"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_campaign',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'prefetch' => 'FALSE',
    ],
    'add' => '3.4',
  ],
  'dedupe_email' => [
    'name' => 'dedupe_email',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('No Duplicate emails?'),
    'description' => ts('Remove duplicate emails?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing.dedupe_email',
    'default' => '0',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '4.1',
  ],
  'sms_provider_id' => [
    'name' => 'sms_provider_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('SMS Provider ID'),
    'where' => 'civicrm_mailing.sms_provider_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_SMS_DAO_Provider',
    'html' => [
      'type' => 'Select',
      'label' => ts("SMS Provider"),
    ],
    'add' => '4.2',
  ],
  'hash' => [
    'name' => 'hash',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Hash'),
    'description' => ts('Key for validating requests related to this mailing.'),
    'maxlength' => 16,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_mailing.hash',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '4.5',
  ],
  'location_type_id' => [
    'name' => 'location_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Location Type ID'),
    'description' => ts('With email_selection_method, determines which email address to use'),
    'where' => 'civicrm_mailing.location_type_id',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_LocationType',
    'html' => [
      'label' => ts("Location Type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_location_type',
      'keyColumn' => 'id',
      'labelColumn' => 'display_name',
    ],
    'add' => '4.6',
  ],
  'email_selection_method' => [
    'name' => 'email_selection_method',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Email Selection Method'),
    'description' => ts('With location_type_id, determine how to choose the email address to use.'),
    'maxlength' => 20,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_mailing.email_selection_method',
    'default' => 'automatic',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'label' => ts("Email Selection Method"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::emailSelectMethods',
    ],
    'add' => '4.6',
  ],
  'language' => [
    'name' => 'language',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Language'),
    'description' => ts('Language of the content of the mailing. Useful for tokens.'),
    'maxlength' => 5,
    'size' => CRM_Utils_Type::SIX,
    'where' => 'civicrm_mailing.language',
    'table_name' => 'civicrm_mailing',
    'entity' => 'Mailing',
    'bao' => 'CRM_Mailing_BAO_Mailing',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'languages',
      'keyColumn' => 'name',
      'optionEditPath' => 'civicrm/admin/options/languages',
    ],
    'add' => '4.6',
  ],
  ];
  
