<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('UF Join ID'),
    'description' => ts('Unique table ID'),
    'required' => TRUE,
    'where' => 'civicrm_uf_join.id',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.3',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Profile Use is active'),
    'description' => ts('Is this join currently active?'),
    'required' => TRUE,
    'where' => 'civicrm_uf_join.is_active',
    'default' => '1',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.3',
  ],
  'module' => [
    'name' => 'module',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Profile Module'),
    'description' => ts('Module which owns this uf_join instance, e.g. User Registration, CiviDonate, etc.'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_uf_join.module',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'add' => '1.3',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Profile Entity Table'),
    'description' => ts('Name of table where item being referenced is stored. Modules which only need a single collection of uf_join instances may choose not to populate entity_table and entity_id.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_uf_join.entity_table',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Core_BAO_UFJoin::entityTables',
    ],
    'add' => '1.3',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Profile Entity ID'),
    'description' => ts('Foreign key to the referenced item.'),
    'where' => 'civicrm_uf_join.entity_id',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'add' => '1.3',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('Controls display order when multiple user framework groups are setup for concurrent display.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_join.weight',
    'default' => '1',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'add' => '1.3',
  ],
  'uf_group_id' => [
    'name' => 'uf_group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Profile ID'),
    'description' => ts('Which form does this field belong to.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_join.uf_group_id',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_UFGroup',
    'html' => [
      'type' => 'Select',
      'label' => ts("Profile"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_uf_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '1.3',
  ],
  'module_data' => [
    'name' => 'module_data',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Profile Use Data'),
    'description' => ts('Json serialized array of data used by the ufjoin.module'),
    'where' => 'civicrm_uf_join.module_data',
    'table_name' => 'civicrm_uf_join',
    'entity' => 'UFJoin',
    'bao' => 'CRM_Core_BAO_UFJoin',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_JSON,
    'add' => '4.5',
  ],
  ];
  
