<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Queue Item ID'),
    'required' => TRUE,
    'where' => 'civicrm_queue_item.id',
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'queue_name' => [
    'name' => 'queue_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Queue Name'),
    'description' => ts('Name of the queue which includes this item'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_queue_item.queue_name',
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => NULL,
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'required' => TRUE,
    'where' => 'civicrm_queue_item.weight',
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => NULL,
  ],
  'submit_time' => [
    'name' => 'submit_time',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Submit Time'),
    'description' => ts('date on which this item was submitted to the queue'),
    'required' => TRUE,
    'where' => 'civicrm_queue_item.submit_time',
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => NULL,
  ],
  'release_time' => [
    'name' => 'release_time',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Release Time'),
    'description' => ts('date on which this job becomes available; null if ASAP'),
    'required' => FALSE,
    'where' => 'civicrm_queue_item.release_time',
    'default' => NULL,
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => NULL,
  ],
  'run_count' => [
    'name' => 'run_count',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Run Count'),
    'description' => ts('Number of times execution has been attempted.'),
    'required' => TRUE,
    'where' => 'civicrm_queue_item.run_count',
    'default' => '0',
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '5.48',
  ],
  'data' => [
    'name' => 'data',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Queue item data'),
    'description' => ts('Serialized queue data'),
    'where' => 'civicrm_queue_item.data',
    'table_name' => 'civicrm_queue_item',
    'entity' => 'QueueItem',
    'bao' => 'CRM_Queue_BAO_QueueItem',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'add' => NULL,
  ],
  ];
  
