<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Location Type ID'),
    'description' => ts('Location Type ID'),
    'required' => TRUE,
    'where' => 'civicrm_location_type.id',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Location Type'),
    'description' => ts('Location Type Name.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_location_type.name',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'display_name' => [
    'name' => 'display_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Display Name'),
    'description' => ts('Location Type Display Name.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_location_type.display_name',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 1,
    'add' => '4.1',
  ],
  'vcard_name' => [
    'name' => 'vcard_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('vCard Location Type'),
    'description' => ts('vCard Location Type Name.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_location_type.vcard_name',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Description'),
    'description' => ts('Location Type Description.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_location_type.description',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'html' => [
      'label' => ts("Description"),
    ],
    'add' => '1.1',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Location Type is Reserved?'),
    'description' => ts('Is this location type a predefined system location?'),
    'where' => 'civicrm_location_type.is_reserved',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Location Type is Active?'),
    'description' => ts('Is this property active?'),
    'where' => 'civicrm_location_type.is_active',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.1',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Default Location Type?'),
    'description' => ts('Is this location type the default?'),
    'where' => 'civicrm_location_type.is_default',
    'table_name' => 'civicrm_location_type',
    'entity' => 'LocationType',
    'bao' => 'CRM_Core_BAO_LocationType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '1.1',
  ],
  ];
  
