<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Date Preference ID'),
    'required' => TRUE,
    'where' => 'civicrm_preferences_date.id',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.0',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Date Preference Name'),
    'description' => ts('The meta name for this date (fixed in code)'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_preferences_date.name',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Description'),
    'description' => ts('Description of this date type.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_preferences_date.description',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'html' => [
      'label' => ts("Description"),
    ],
    'add' => '2.0',
  ],
  'start' => [
    'name' => 'start',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Start'),
    'description' => ts('The start offset relative to current year'),
    'required' => TRUE,
    'where' => 'civicrm_preferences_date.start',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'html' => [
      'label' => ts("Start"),
    ],
    'add' => '2.0',
  ],
  'end' => [
    'name' => 'end',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('End Offset'),
    'description' => ts('The end offset relative to current year, can be negative'),
    'required' => TRUE,
    'where' => 'civicrm_preferences_date.end',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'date_format' => [
    'name' => 'date_format',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Date Format'),
    'description' => ts('The date type'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_preferences_date.date_format',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'html' => [
      'label' => ts("Date Format"),
    ],
    'add' => '2.0',
  ],
  'time_format' => [
    'name' => 'time_format',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Time Format'),
    'description' => ts('time format'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_preferences_date.time_format',
    'table_name' => 'civicrm_preferences_date',
    'entity' => 'PreferencesDate',
    'bao' => 'CRM_Core_BAO_PreferencesDate',
    'localizable' => 0,
    'html' => [
      'label' => ts("Time Format"),
    ],
    'add' => '3.1',
  ],
  ];
  
