<?php
return [
  'contribution_soft_id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Soft Credit ID'),
    'description' => ts('Soft Credit ID'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_contribution_soft.id',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.2',
  ],
  'contribution_id' => [
    'name' => 'contribution_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contribution ID'),
    'description' => ts('FK to contribution table.'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_soft.contribution_id',
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_Contribution',
    'html' => [
      'label' => ts("Contribution"),
    ],
    'add' => '2.2',
  ],
  'contribution_soft_contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_contribution_soft.contact_id',
    'headerPattern' => '/contact(.?id)?/i',
    'dataPattern' => '/^\d+$/',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '2.2',
  ],
  'amount' => [
    'name' => 'amount',
    'type' => CRM_Utils_Type::T_MONEY,
    'title' => ts('Soft Credit Amount'),
    'description' => ts('Amount of this soft credit.'),
    'required' => TRUE,
    'precision' => [
      20,
      2,
    ],
    'import' => TRUE,
    'where' => 'civicrm_contribution_soft.amount',
    'headerPattern' => '/total(.?am(ou)?nt)?/i',
    'dataPattern' => '/^\d+(\.\d{2})?$/',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'currency' => [
    'name' => 'currency',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Soft Contribution Currency'),
    'description' => ts('3 character string, value from config setting or input via user.'),
    'maxlength' => 3,
    'size' => CRM_Utils_Type::FOUR,
    'where' => 'civicrm_contribution_soft.currency',
    'default' => NULL,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_currency',
      'keyColumn' => 'name',
      'labelColumn' => 'full_name',
      'nameColumn' => 'name',
      'abbrColumn' => 'symbol',
    ],
    'add' => '3.2',
  ],
  'pcp_id' => [
    'name' => 'pcp_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('PCP ID'),
    'description' => ts('FK to civicrm_pcp.id'),
    'where' => 'civicrm_contribution_soft.pcp_id',
    'default' => NULL,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'FKClassName' => 'CRM_PCP_DAO_PCP',
    'html' => [
      'label' => ts("PCP"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_pcp',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '2.2',
  ],
  'pcp_display_in_roll' => [
    'name' => 'pcp_display_in_roll',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Soft Contribution Display on PCP'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_soft.pcp_display_in_roll',
    'default' => '0',
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'pcp_roll_nickname' => [
    'name' => 'pcp_roll_nickname',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Soft Contribution PCP Nickname'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_soft.pcp_roll_nickname',
    'default' => NULL,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'pcp_personal_note' => [
    'name' => 'pcp_personal_note',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Soft Contribution PCP Note'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_soft.pcp_personal_note',
    'default' => NULL,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '2.2',
  ],
  'soft_credit_type_id' => [
    'name' => 'soft_credit_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Soft Credit Type'),
    'description' => ts('Soft Credit Type ID.Implicit FK to civicrm_option_value where option_group = soft_credit_type.'),
    'where' => 'civicrm_contribution_soft.soft_credit_type_id',
    'default' => NULL,
    'table_name' => 'civicrm_contribution_soft',
    'entity' => 'ContributionSoft',
    'bao' => 'CRM_Contribute_BAO_ContributionSoft',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'soft_credit_type',
      'optionEditPath' => 'civicrm/admin/options/soft_credit_type',
    ],
    'add' => '2.2',
  ],
  ];
  
