<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from xml/schema/CRM/Contact/RelationshipCache.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:9f16f118d8f9337260a05d6ccd374b94)
 */

/**
 * Database access object for the RelationshipCache entity.
 */
class CRM_Contact_DAO_RelationshipCache_Fields {

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Relationship Cache ID'),
          'description' => ts('Relationship Cache ID'),
          'required' => TRUE,
          'where' => 'civicrm_relationship_cache.id',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'relationship_id' => [
          'name' => 'relationship_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Relationship ID'),
          'description' => ts('id of the relationship (FK to civicrm_relationship.id)'),
          'required' => TRUE,
          'where' => 'civicrm_relationship_cache.relationship_id',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Relationship',
          'html' => [
            'label' => ts("Relationship"),
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'relationship_type_id' => [
          'name' => 'relationship_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Relationship Type ID'),
          'description' => ts('id of the relationship type'),
          'required' => TRUE,
          'where' => 'civicrm_relationship_cache.relationship_type_id',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_RelationshipType',
          'html' => [
            'label' => ts("Relationship Type"),
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'orientation' => [
          'name' => 'orientation',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Orientation (a_b or b_a)'),
          'description' => ts('The cache record is a permutation of the original relationship record. The orientation indicates whether it is forward (a_b) or reverse (b_a) relationship.'),
          'required' => TRUE,
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'where' => 'civicrm_relationship_cache.orientation',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'pseudoconstant' => [
            'callback' => 'CRM_Core_SelectValues::relationshipOrientation',
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'near_contact_id' => [
          'name' => 'near_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contact ID (Near side)'),
          'description' => ts('id of the first contact'),
          'required' => TRUE,
          'where' => 'civicrm_relationship_cache.near_contact_id',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => ts("Contact (Near side)"),
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'near_relation' => [
          'name' => 'near_relation',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Relationship Name (to related contact)'),
          'description' => ts('name for relationship of near_contact to far_contact.'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_relationship_cache.near_relation',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => ts("Relationship to contact"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Core_PseudoConstant::relationshipTypeOptions',
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'far_contact_id' => [
          'name' => 'far_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contact ID (Far side)'),
          'description' => ts('id of the second contact'),
          'required' => TRUE,
          'where' => 'civicrm_relationship_cache.far_contact_id',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => ts("Contact (Far side)"),
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'far_relation' => [
          'name' => 'far_relation',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Relationship Name (from related contact)'),
          'description' => ts('name for relationship of far_contact to near_contact.'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_relationship_cache.far_relation',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => ts("Relationship from contact"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Core_PseudoConstant::relationshipTypeOptions',
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Relationship Is Active'),
          'description' => ts('is the relationship active ?'),
          'required' => TRUE,
          'where' => 'civicrm_relationship_cache.is_active',
          'default' => '1',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => ts("Enabled"),
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'relationship_start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Relationship Start Date'),
          'description' => ts('date when the relationship started'),
          'where' => 'civicrm_relationship_cache.start_date',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDate',
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'relationship_end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Relationship End Date'),
          'description' => ts('date when the relationship ended'),
          'where' => 'civicrm_relationship_cache.end_date',
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDate',
          ],
          'readonly' => TRUE,
          'add' => '5.29',
        ],
        'case_id' => [
          'name' => 'case_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Case ID'),
          'description' => ts('FK to civicrm_case'),
          'where' => 'civicrm_relationship_cache.case_id',
          'default' => NULL,
          'table_name' => 'civicrm_relationship_cache',
          'entity' => 'RelationshipCache',
          'bao' => 'CRM_Contact_BAO_RelationshipCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_Case_DAO_Case',
          'component' => 'CiviCase',
          'html' => [
            'type' => 'EntityRef',
            'label' => ts("Case"),
          ],
          'readonly' => TRUE,
          'add' => '5.44',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

}
