<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Currency ID'),
    'description' => ts('Currency ID'),
    'required' => TRUE,
    'where' => 'civicrm_currency.id',
    'table_name' => 'civicrm_currency',
    'entity' => 'Currency',
    'bao' => 'CRM_Financial_DAO_Currency',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.7',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Currency'),
    'description' => ts('Currency Name'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_currency.name',
    'export' => TRUE,
    'table_name' => 'civicrm_currency',
    'entity' => 'Currency',
    'bao' => 'CRM_Financial_DAO_Currency',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.7',
  ],
  'symbol' => [
    'name' => 'symbol',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Currency Symbol'),
    'description' => ts('Currency Symbol'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_currency.symbol',
    'table_name' => 'civicrm_currency',
    'entity' => 'Currency',
    'bao' => 'CRM_Financial_DAO_Currency',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.7',
  ],
  'numeric_code' => [
    'name' => 'numeric_code',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Currency Numeric Code'),
    'description' => ts('Numeric currency code'),
    'maxlength' => 3,
    'size' => CRM_Utils_Type::FOUR,
    'import' => TRUE,
    'where' => 'civicrm_currency.numeric_code',
    'export' => TRUE,
    'table_name' => 'civicrm_currency',
    'entity' => 'Currency',
    'bao' => 'CRM_Financial_DAO_Currency',
    'localizable' => 0,
    'add' => '1.9',
  ],
  'full_name' => [
    'name' => 'full_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Full Currency Name'),
    'description' => ts('Full currency name'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_currency.full_name',
    'table_name' => 'civicrm_currency',
    'entity' => 'Currency',
    'bao' => 'CRM_Financial_DAO_Currency',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.9',
  ],
  ];
  
