<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('MailingAB ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_abtest.id',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Name'),
    'description' => ts('Name of the A/B test'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_abtest.name',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'status' => [
    'name' => 'status',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Status'),
    'description' => ts('Status'),
    'maxlength' => 32,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_mailing_abtest.status',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Mailing_PseudoConstant::abStatus',
    ],
    'add' => '4.6',
  ],
  'mailing_id_a' => [
    'name' => 'mailing_id_a',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing ID (A)'),
    'description' => ts('The first experimental mailing ("A" condition)'),
    'where' => 'civicrm_mailing_abtest.mailing_id_a',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'mailing_id_b' => [
    'name' => 'mailing_id_b',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing ID (B)'),
    'description' => ts('The second experimental mailing ("B" condition)'),
    'where' => 'civicrm_mailing_abtest.mailing_id_b',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'mailing_id_c' => [
    'name' => 'mailing_id_c',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing ID (C)'),
    'description' => ts('The final, general mailing (derived from A or B)'),
    'where' => 'civicrm_mailing_abtest.mailing_id_c',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which site is this mailing for'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_abtest.domain_id',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'testing_criteria' => [
    'name' => 'testing_criteria',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Testing Criteria'),
    'maxlength' => 32,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_mailing_abtest.testing_criteria',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Mailing_PseudoConstant::abTestCriteria',
    ],
    'add' => '4.6',
  ],
  'winner_criteria' => [
    'name' => 'winner_criteria',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Winner Criteria'),
    'maxlength' => 32,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_mailing_abtest.winner_criteria',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Mailing_PseudoConstant::abWinnerCriteria',
    ],
    'add' => '4.6',
  ],
  'specific_url' => [
    'name' => 'specific_url',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('URL for Winner Criteria'),
    'description' => ts('What specific url to track'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_abtest.specific_url',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'declare_winning_time' => [
    'name' => 'declare_winning_time',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Declaration Time'),
    'description' => ts('In how much time to declare winner'),
    'where' => 'civicrm_mailing_abtest.declare_winning_time',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'group_percentage' => [
    'name' => 'group_percentage',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group Percentage'),
    'where' => 'civicrm_mailing_abtest.group_percentage',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_mailing_abtest.created_id',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '4.6',
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('AB Test Created Date'),
    'description' => ts('When was this item created'),
    'required' => FALSE,
    'where' => 'civicrm_mailing_abtest.created_date',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_abtest',
    'entity' => 'MailingAB',
    'bao' => 'CRM_Mailing_BAO_MailingAB',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'mailing',
    ],
    'add' => '4.6',
  ],
  ];
  
