<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Membership Status ID'),
    'description' => ts('Membership ID'),
    'required' => TRUE,
    'where' => 'civicrm_membership_status.id',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.5',
  ],
  'membership_status' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Membership Status'),
    'description' => ts('Name for Membership Status'),
    'required' => TRUE,
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_membership_status.name',
    'export' => TRUE,
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Label'),
    'description' => ts('Label for Membership Status'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_membership_status.label',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.2',
  ],
  'start_event' => [
    'name' => 'start_event',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Start Event'),
    'description' => ts('Event when this status starts.'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_membership_status.start_event',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("Start Event"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::eventDate',
    ],
    'add' => '1.5',
  ],
  'start_event_adjust_unit' => [
    'name' => 'start_event_adjust_unit',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Start Event Adjust Unit'),
    'description' => ts('Unit used for adjusting from start_event.'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_membership_status.start_event_adjust_unit',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("Start Event Adjust Unit"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::unitList',
    ],
    'add' => '1.5',
  ],
  'start_event_adjust_interval' => [
    'name' => 'start_event_adjust_interval',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Start Event Adjust Interval'),
    'description' => ts('Status range begins this many units from start_event.'),
    'where' => 'civicrm_membership_status.start_event_adjust_interval',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'label' => ts("Start Event Adjust Interval"),
    ],
    'add' => '1.5',
  ],
  'end_event' => [
    'name' => 'end_event',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('End Event'),
    'description' => ts('Event after which this status ends.'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_membership_status.end_event',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("End Event"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::eventDate',
    ],
    'add' => '1.5',
  ],
  'end_event_adjust_unit' => [
    'name' => 'end_event_adjust_unit',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('End Event Adjust Unit'),
    'description' => ts('Unit used for adjusting from the ending event.'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_membership_status.end_event_adjust_unit',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("End Event Adjust Unit"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::unitList',
    ],
    'add' => '1.5',
  ],
  'end_event_adjust_interval' => [
    'name' => 'end_event_adjust_interval',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('End Event Adjust Interval'),
    'description' => ts('Status range ends this many units from end_event.'),
    'where' => 'civicrm_membership_status.end_event_adjust_interval',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'label' => ts("End Event Adjust Interval"),
    ],
    'add' => '1.5',
  ],
  'is_current_member' => [
    'name' => 'is_current_member',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Current Membership?'),
    'description' => ts('Does this status aggregate to current members (e.g. New, Renewed, Grace might all be TRUE... while Unrenewed, Lapsed, Inactive would be FALSE).'),
    'required' => TRUE,
    'where' => 'civicrm_membership_status.is_current_member',
    'default' => '0',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'is_admin' => [
    'name' => 'is_admin',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Administrator Only?'),
    'description' => ts('Is this status for admin/manual assignment only.'),
    'required' => TRUE,
    'where' => 'civicrm_membership_status.is_admin',
    'default' => '0',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '1.5',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'where' => 'civicrm_membership_status.weight',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Default Status?'),
    'description' => ts('Assign this status to a membership record if no other status match is found.'),
    'required' => TRUE,
    'where' => 'civicrm_membership_status.is_default',
    'default' => '0',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '1.5',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Active'),
    'description' => ts('Is this membership_status enabled.'),
    'required' => TRUE,
    'where' => 'civicrm_membership_status.is_active',
    'default' => '1',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.5',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Reserved'),
    'description' => ts('Is this membership_status reserved.'),
    'required' => TRUE,
    'where' => 'civicrm_membership_status.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_membership_status',
    'entity' => 'MembershipStatus',
    'bao' => 'CRM_Member_BAO_MembershipStatus',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '2.1',
  ],
  ];
  
