<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Participant Status Type ID'),
    'description' => ts('unique participant status type id'),
    'required' => TRUE,
    'where' => 'civicrm_participant_status_type.id',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.0',
  ],
  'participant_status' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Participant Status'),
    'description' => ts('non-localized name of the status type'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_participant_status_type.name',
    'export' => TRUE,
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'add' => '3.0',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Participant Status Label'),
    'description' => ts('localized label for display of this status type'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_participant_status_type.label',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 1,
    'add' => '3.0',
  ],
  'class' => [
    'name' => 'class',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Participant Status Class'),
    'description' => ts('the general group of status type this one belongs to'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_participant_status_type.class',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Event_PseudoConstant::participantStatusClassOptions',
    ],
    'add' => '3.0',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Participant Status Is Reserved?>'),
    'description' => ts('whether this is a status type required by the system'),
    'required' => TRUE,
    'where' => 'civicrm_participant_status_type.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'add' => '3.0',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Participant Status is Active'),
    'description' => ts('whether this status type is active'),
    'required' => TRUE,
    'where' => 'civicrm_participant_status_type.is_active',
    'default' => '1',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '3.0',
  ],
  'is_counted' => [
    'name' => 'is_counted',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Participant Status Counts?'),
    'description' => ts('whether this status type is counted against event size limit'),
    'required' => TRUE,
    'where' => 'civicrm_participant_status_type.is_counted',
    'default' => '0',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'add' => '3.0',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('controls sort order'),
    'required' => TRUE,
    'where' => 'civicrm_participant_status_type.weight',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'add' => '3.0',
  ],
  'visibility_id' => [
    'name' => 'visibility_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Participant Status Visibility'),
    'description' => ts('whether the status type is visible to the public, an implicit foreign key to option_value.value related to the `visibility` option_group'),
    'where' => 'civicrm_participant_status_type.visibility_id',
    'table_name' => 'civicrm_participant_status_type',
    'entity' => 'ParticipantStatusType',
    'bao' => 'CRM_Event_BAO_ParticipantStatusType',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'visibility',
      'optionEditPath' => 'civicrm/admin/options/visibility',
    ],
    'add' => '3.0',
  ],
  ];
  
