<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Location Block ID'),
    'description' => ts('Unique ID'),
    'required' => TRUE,
    'where' => 'civicrm_loc_block.id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.0',
  ],
  'address_id' => [
    'name' => 'address_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Address ID'),
    'where' => 'civicrm_loc_block.address_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Address',
    'html' => [
      'label' => ts("Address"),
    ],
    'add' => '2.0',
  ],
  'email_id' => [
    'name' => 'email_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Email ID'),
    'where' => 'civicrm_loc_block.email_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Email',
    'html' => [
      'label' => ts("Email"),
    ],
    'add' => '2.0',
  ],
  'phone_id' => [
    'name' => 'phone_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Phone ID'),
    'where' => 'civicrm_loc_block.phone_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Phone',
    'html' => [
      'label' => ts("Phone"),
    ],
    'add' => '2.0',
  ],
  'im_id' => [
    'name' => 'im_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('IM ID'),
    'where' => 'civicrm_loc_block.im_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_IM',
    'html' => [
      'label' => ts("Instant Messenger"),
    ],
    'add' => '2.0',
  ],
  'address_2_id' => [
    'name' => 'address_2_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Address 2 ID'),
    'where' => 'civicrm_loc_block.address_2_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Address',
    'html' => [
      'label' => ts("Address 2"),
    ],
    'add' => '2.0',
  ],
  'email_2_id' => [
    'name' => 'email_2_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Email 2 ID'),
    'where' => 'civicrm_loc_block.email_2_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Email',
    'html' => [
      'label' => ts("Email 2"),
    ],
    'add' => '2.0',
  ],
  'phone_2_id' => [
    'name' => 'phone_2_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Phone 2 ID'),
    'where' => 'civicrm_loc_block.phone_2_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Phone',
    'html' => [
      'label' => ts("Phone 2"),
    ],
    'add' => '2.0',
  ],
  'im_2_id' => [
    'name' => 'im_2_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('IM 2 ID'),
    'where' => 'civicrm_loc_block.im_2_id',
    'table_name' => 'civicrm_loc_block',
    'entity' => 'LocBlock',
    'bao' => 'CRM_Core_DAO_LocBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_IM',
    'html' => [
      'label' => ts("Instant Messenger 2"),
    ],
    'add' => '2.0',
  ],
  ];
  
