<?php
return [
  'activity_id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity ID'),
    'description' => ts('Unique  Other Activity ID'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_activity.id',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'source_record_id' => [
    'name' => 'source_record_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Source Record'),
    'description' => ts('Artificial FK to original transaction (e.g. contribution) IF it is not an Activity. Entity table is discovered by filtering by the appropriate activity_type_id.'),
    'where' => 'civicrm_activity.source_record_id',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '2.0',
  ],
  'activity_type_id' => [
    'name' => 'activity_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity Type ID'),
    'description' => ts('FK to civicrm_option_value.id, that has to be valid, registered activity type.'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_activity.activity_type_id',
    'headerPattern' => '/(activity.)?type(.id$)/i',
    'export' => TRUE,
    'default' => '1',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("Activity Type"),
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'activity_type',
      'optionEditPath' => 'civicrm/admin/options/activity_type',
    ],
    'add' => '1.1',
  ],
  'activity_subject' => [
    'name' => 'subject',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Subject'),
    'description' => ts('The subject/purpose/short description of the activity.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_activity.subject',
    'headerPattern' => '/(activity.)?subject/i',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'activity_date_time' => [
    'name' => 'activity_date_time',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Activity Date'),
    'description' => ts('Date and time this activity is scheduled to occur. Formerly named scheduled_date_time.'),
    'required' => FALSE,
    'import' => TRUE,
    'where' => 'civicrm_activity.activity_date_time',
    'headerPattern' => '/(activity.)?date(.time$)?/i',
    'export' => TRUE,
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '2.0',
  ],
  'activity_duration' => [
    'name' => 'duration',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Duration'),
    'description' => ts('Planned or actual duration of activity expressed in minutes. Conglomerate of former duration_hours and duration_minutes.'),
    'import' => TRUE,
    'where' => 'civicrm_activity.duration',
    'headerPattern' => '/(activity.)?duration(s)?$/i',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'add' => '2.0',
  ],
  'activity_location' => [
    'name' => 'location',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Location'),
    'description' => ts('Location of the activity (optional, open text).'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_activity.location',
    'headerPattern' => '/(activity.)?location$/i',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'phone_id' => [
    'name' => 'phone_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Phone ID (called)'),
    'description' => ts('Phone ID of the number called (optional - used if an existing phone number is selected).'),
    'where' => 'civicrm_activity.phone_id',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Phone',
    'deprecated' => TRUE,
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Phone (called)"),
    ],
    'add' => '2.0',
  ],
  'phone_number' => [
    'name' => 'phone_number',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Phone (called) Number'),
    'description' => ts('Phone number in case the number does not exist in the civicrm_phone table.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_activity.phone_number',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'deprecated' => TRUE,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'activity_details' => [
    'name' => 'details',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Details'),
    'description' => ts('Details about the activity (agenda, notes, etc).'),
    'import' => TRUE,
    'where' => 'civicrm_activity.details',
    'headerPattern' => '/(activity.)?detail(s)?$/i',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'RichTextEditor',
    ],
    'add' => '1.1',
  ],
  'activity_status_id' => [
    'name' => 'status_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity Status'),
    'description' => ts('ID of the status this activity is currently in. Foreign key to civicrm_option_value.'),
    'import' => TRUE,
    'where' => 'civicrm_activity.status_id',
    'headerPattern' => '/(activity.)?status(.label$)?/i',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'activity_status',
      'optionEditPath' => 'civicrm/admin/options/activity_status',
    ],
    'add' => '2.0',
  ],
  'priority_id' => [
    'name' => 'priority_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Priority'),
    'description' => ts('ID of the priority given to this activity. Foreign key to civicrm_option_value.'),
    'import' => TRUE,
    'where' => 'civicrm_activity.priority_id',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'priority',
      'optionEditPath' => 'civicrm/admin/options/priority',
    ],
    'add' => '2.0',
  ],
  'parent_id' => [
    'name' => 'parent_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Parent Activity ID'),
    'description' => ts('Parent meeting ID (if this is a follow-up item).'),
    'where' => 'civicrm_activity.parent_id',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'FKClassName' => 'CRM_Activity_DAO_Activity',
    'html' => [
      'label' => ts("Parent Activity"),
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'activity_is_test' => [
    'name' => 'is_test',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Test'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_activity.is_test',
    'headerPattern' => '/(is.)?test(.activity)?/i',
    'export' => TRUE,
    'default' => '0',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '2.0',
  ],
  'activity_medium_id' => [
    'name' => 'medium_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity Medium'),
    'description' => ts('Activity Medium, Implicit FK to civicrm_option_value where option_group = encounter_medium.'),
    'where' => 'civicrm_activity.medium_id',
    'default' => NULL,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'encounter_medium',
      'optionEditPath' => 'civicrm/admin/options/encounter_medium',
    ],
    'add' => '2.2',
  ],
  'is_auto' => [
    'name' => 'is_auto',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Auto'),
    'required' => TRUE,
    'where' => 'civicrm_activity.is_auto',
    'default' => '0',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'relationship_id' => [
    'name' => 'relationship_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Relationship ID'),
    'description' => ts('FK to Relationship ID'),
    'where' => 'civicrm_activity.relationship_id',
    'default' => NULL,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Relationship',
    'deprecated' => TRUE,
    'html' => [
      'label' => ts("Relationship"),
    ],
    'add' => '2.2',
  ],
  'is_current_revision' => [
    'name' => 'is_current_revision',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is current (unused)'),
    'description' => ts('Unused deprecated column.'),
    'required' => TRUE,
    'where' => 'civicrm_activity.is_current_revision',
    'default' => '1',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'deprecated' => TRUE,
    'add' => '2.2',
  ],
  'original_id' => [
    'name' => 'original_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Original ID (unused)'),
    'description' => ts('Unused deprecated column.'),
    'where' => 'civicrm_activity.original_id',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'FKClassName' => 'CRM_Activity_DAO_Activity',
    'deprecated' => TRUE,
    'html' => [
      'label' => ts("Original Activity"),
    ],
    'readonly' => TRUE,
    'add' => '2.2',
  ],
  'activity_result' => [
    'name' => 'result',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Result'),
    'description' => ts('Currently being used to store result id for survey activity, FK to option value.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_activity.result',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'activity_is_deleted' => [
    'name' => 'is_deleted',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Activity is in the Trash'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_activity.is_deleted',
    'headerPattern' => '/(activity.)?(trash|deleted)/i',
    'export' => TRUE,
    'default' => '0',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '2.2',
  ],
  'activity_campaign_id' => [
    'name' => 'campaign_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Campaign ID'),
    'description' => ts('The campaign for which this activity has been triggered.'),
    'import' => TRUE,
    'where' => 'civicrm_activity.campaign_id',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'FKClassName' => 'CRM_Campaign_DAO_Campaign',
    'component' => 'CiviCampaign',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Campaign"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_campaign',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'prefetch' => 'FALSE',
    ],
    'add' => '3.4',
  ],
  'activity_engagement_level' => [
    'name' => 'engagement_level',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Engagement Index'),
    'description' => ts('Assign a specific level of engagement to this activity. Used for tracking constituents in ladder of engagement.'),
    'import' => TRUE,
    'where' => 'civicrm_activity.engagement_level',
    'export' => TRUE,
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'engagement_index',
      'optionEditPath' => 'civicrm/admin/options/engagement_index',
    ],
    'add' => '3.4',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'where' => 'civicrm_activity.weight',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'is_star' => [
    'name' => 'is_star',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Starred'),
    'description' => ts('Activity marked as favorite.'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_activity.is_star',
    'headerPattern' => '/(activity.)?(star|favorite)/i',
    'export' => TRUE,
    'default' => '0',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Checkbox',
    ],
    'add' => '4.7',
  ],
  'activity_created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Created Date'),
    'description' => ts('When was the activity was created.'),
    'required' => FALSE,
    'where' => 'civicrm_activity.created_date',
    'export' => TRUE,
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'label' => ts("Created Date"),
    ],
    'add' => '4.7',
  ],
  'activity_modified_date' => [
    'name' => 'modified_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Modified Date'),
    'description' => ts('When was the activity (or closely related entity) was created or modified or deleted.'),
    'required' => FALSE,
    'where' => 'civicrm_activity.modified_date',
    'export' => TRUE,
    'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_activity',
    'entity' => 'Activity',
    'bao' => 'CRM_Activity_BAO_Activity',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'label' => ts("Modified Date"),
    ],
    'readonly' => TRUE,
    'add' => '4.7',
  ],
  ];
  
