<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Website ID'),
    'description' => ts('Unique Website ID'),
    'required' => TRUE,
    'where' => 'civicrm_website.id',
    'table_name' => 'civicrm_website',
    'entity' => 'Website',
    'bao' => 'CRM_Core_BAO_Website',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.2',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_website.contact_id',
    'table_name' => 'civicrm_website',
    'entity' => 'Website',
    'bao' => 'CRM_Core_BAO_Website',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '3.2',
  ],
  'url' => [
    'name' => 'url',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Website'),
    'description' => ts('Website'),
    'maxlength' => 255,
    'size' => 45,
    'import' => TRUE,
    'where' => 'civicrm_website.url',
    'headerPattern' => '/Website/i',
    'dataPattern' => '/^[A-Za-z][0-9A-Za-z]{20,}$/',
    'export' => TRUE,
    'table_name' => 'civicrm_website',
    'entity' => 'Website',
    'bao' => 'CRM_Core_BAO_Website',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.2',
  ],
  'website_type_id' => [
    'name' => 'website_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Website Type'),
    'description' => ts('Which Website type does this website belong to.'),
    'where' => 'civicrm_website.website_type_id',
    'table_name' => 'civicrm_website',
    'entity' => 'Website',
    'bao' => 'CRM_Core_BAO_Website',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'website_type',
      'optionEditPath' => 'civicrm/admin/options/website_type',
    ],
    'add' => '3.2',
  ],
  ];
  
