<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Job ID'),
    'description' => ts('Job ID'),
    'required' => TRUE,
    'where' => 'civicrm_job.id',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.1',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this scheduled job for'),
    'required' => TRUE,
    'where' => 'civicrm_job.domain_id',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '4.1',
  ],
  'run_frequency' => [
    'name' => 'run_frequency',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Job Frequency'),
    'description' => ts('Scheduled job run frequency.'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_job.run_frequency',
    'default' => 'Daily',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getJobFrequency',
    ],
    'add' => '4.1',
  ],
  'last_run' => [
    'name' => 'last_run',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Last Run'),
    'description' => ts('When was this cron entry last run'),
    'required' => FALSE,
    'where' => 'civicrm_job.last_run',
    'default' => NULL,
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'html' => [
      'label' => ts("Last Run"),
    ],
    'add' => '4.1',
  ],
  'scheduled_run_date' => [
    'name' => 'scheduled_run_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Scheduled Run Date'),
    'description' => ts('When is this cron entry scheduled to run'),
    'required' => FALSE,
    'where' => 'civicrm_job.scheduled_run_date',
    'default' => NULL,
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'html' => [
      'label' => ts("Scheduled Run Date"),
    ],
    'add' => '4.7',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Job Name'),
    'description' => ts('Title of the job'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job.name',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Job Description'),
    'description' => ts('Description of the job'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job.description',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'api_entity' => [
    'name' => 'api_entity',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('API Entity'),
    'description' => ts('Entity of the job api call'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job.api_entity',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'api_action' => [
    'name' => 'api_action',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('API Action'),
    'description' => ts('Action of the job api call'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job.api_action',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'parameters' => [
    'name' => 'parameters',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('API Parameters'),
    'description' => ts('List of parameters to the command.'),
    'rows' => 4,
    'cols' => 60,
    'where' => 'civicrm_job.parameters',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '4.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Job Is Active?'),
    'description' => ts('Is this job active?'),
    'required' => TRUE,
    'where' => 'civicrm_job.is_active',
    'default' => '1',
    'table_name' => 'civicrm_job',
    'entity' => 'Job',
    'bao' => 'CRM_Core_BAO_Job',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.1',
  ],
  ];
  
