<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Instant Messenger ID'),
    'description' => ts('Unique IM ID'),
    'required' => TRUE,
    'where' => 'civicrm_im.id',
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_im.contact_id',
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '2.0',
  ],
  'location_type_id' => [
    'name' => 'location_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('IM Location Type'),
    'description' => ts('Which Location does this email belong to.'),
    'where' => 'civicrm_im.location_type_id',
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_location_type',
      'keyColumn' => 'id',
      'labelColumn' => 'display_name',
    ],
    'add' => '2.0',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('IM Screen Name'),
    'description' => ts('IM screen name'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_im.name',
    'headerPattern' => '/I(nstant )?M(ess.*)?|screen(\s+)?name/i',
    'dataPattern' => '/^[A-Za-z][0-9A-Za-z]{20,}$/',
    'export' => TRUE,
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'provider_id' => [
    'name' => 'provider_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('IM Provider'),
    'description' => ts('Which IM Provider does this screen name belong to.'),
    'where' => 'civicrm_im.provider_id',
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'instant_messenger_service',
      'optionEditPath' => 'civicrm/admin/options/instant_messenger_service',
    ],
    'add' => '1.1',
  ],
  'is_primary' => [
    'name' => 'is_primary',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Primary'),
    'description' => ts('Is this the primary IM for this contact and location.'),
    'required' => TRUE,
    'where' => 'civicrm_im.is_primary',
    'default' => '0',
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'html' => [
      'type' => 'Radio',
    ],
    'add' => '1.1',
  ],
  'is_billing' => [
    'name' => 'is_billing',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is IM Billing?'),
    'description' => ts('Is this the billing?'),
    'required' => TRUE,
    'where' => 'civicrm_im.is_billing',
    'default' => '0',
    'table_name' => 'civicrm_im',
    'entity' => 'IM',
    'bao' => 'CRM_Core_BAO_IM',
    'localizable' => 0,
    'add' => '2.0',
  ],
  ];
  
