<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Price Set Entity ID'),
    'description' => ts('Price Set Entity'),
    'required' => TRUE,
    'where' => 'civicrm_price_set_entity.id',
    'table_name' => 'civicrm_price_set_entity',
    'entity' => 'PriceSetEntity',
    'bao' => 'CRM_Price_DAO_PriceSetEntity',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.8',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('Table which uses this price set'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_price_set_entity.entity_table',
    'table_name' => 'civicrm_price_set_entity',
    'entity' => 'PriceSetEntity',
    'bao' => 'CRM_Price_DAO_PriceSetEntity',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('Item in table'),
    'required' => TRUE,
    'where' => 'civicrm_price_set_entity.entity_id',
    'table_name' => 'civicrm_price_set_entity',
    'entity' => 'PriceSetEntity',
    'bao' => 'CRM_Price_DAO_PriceSetEntity',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'price_set_id' => [
    'name' => 'price_set_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Price Set ID'),
    'description' => ts('price set being used'),
    'required' => TRUE,
    'where' => 'civicrm_price_set_entity.price_set_id',
    'table_name' => 'civicrm_price_set_entity',
    'entity' => 'PriceSetEntity',
    'bao' => 'CRM_Price_DAO_PriceSetEntity',
    'localizable' => 0,
    'FKClassName' => 'CRM_Price_DAO_PriceSet',
    'html' => [
      'label' => ts("Price Set"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_price_set',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '1.8',
  ],
  ];
  
