<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Premium Product ID'),
    'description' => ts('Contribution ID'),
    'required' => TRUE,
    'where' => 'civicrm_premiums_product.id',
    'table_name' => 'civicrm_premiums_product',
    'entity' => 'PremiumsProduct',
    'bao' => 'CRM_Contribute_DAO_PremiumsProduct',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.4',
  ],
  'premiums_id' => [
    'name' => 'premiums_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Premium ID'),
    'description' => ts('Foreign key to premiums settings record.'),
    'required' => TRUE,
    'where' => 'civicrm_premiums_product.premiums_id',
    'table_name' => 'civicrm_premiums_product',
    'entity' => 'PremiumsProduct',
    'bao' => 'CRM_Contribute_DAO_PremiumsProduct',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_Premium',
    'html' => [
      'label' => ts("Premium"),
    ],
    'add' => '1.4',
  ],
  'product_id' => [
    'name' => 'product_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Product ID'),
    'description' => ts('Foreign key to each product object.'),
    'required' => TRUE,
    'where' => 'civicrm_premiums_product.product_id',
    'table_name' => 'civicrm_premiums_product',
    'entity' => 'PremiumsProduct',
    'bao' => 'CRM_Contribute_DAO_PremiumsProduct',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_Product',
    'html' => [
      'label' => ts("Product"),
    ],
    'add' => '1.4',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'required' => TRUE,
    'where' => 'civicrm_premiums_product.weight',
    'table_name' => 'civicrm_premiums_product',
    'entity' => 'PremiumsProduct',
    'bao' => 'CRM_Contribute_DAO_PremiumsProduct',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'financial_type_id' => [
    'name' => 'financial_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Financial Type ID'),
    'description' => ts('FK to Financial Type.'),
    'where' => 'civicrm_premiums_product.financial_type_id',
    'default' => NULL,
    'table_name' => 'civicrm_premiums_product',
    'entity' => 'PremiumsProduct',
    'bao' => 'CRM_Contribute_DAO_PremiumsProduct',
    'localizable' => 0,
    'FKClassName' => 'CRM_Financial_DAO_FinancialType',
    'html' => [
      'label' => ts("Financial Type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_financial_type',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '4.3',
  ],
  ];
  
