<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Financial Type ID'),
    'description' => ts('ID of original financial_type so you can search this table by the financial_type.id and then select the relevant version based on the timestamp'),
    'required' => TRUE,
    'where' => 'civicrm_financial_type.id',
    'table_name' => 'civicrm_financial_type',
    'entity' => 'FinancialType',
    'bao' => 'CRM_Financial_BAO_FinancialType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.3',
  ],
  'financial_type' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Financial Type'),
    'description' => ts('Financial Type Name.'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_financial_type.name',
    'headerPattern' => '/(finan(cial)?)?type/i',
    'dataPattern' => '/donation|member|campaign/i',
    'export' => TRUE,
    'table_name' => 'civicrm_financial_type',
    'entity' => 'FinancialType',
    'bao' => 'CRM_Financial_BAO_FinancialType',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
      'label' => ts("Name"),
    ],
    'add' => '1.3',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Description'),
    'description' => ts('Financial Type Description.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_financial_type.description',
    'table_name' => 'civicrm_financial_type',
    'entity' => 'FinancialType',
    'bao' => 'CRM_Financial_BAO_FinancialType',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
      'label' => ts("Description"),
    ],
    'add' => '1.3',
  ],
  'is_deductible' => [
    'name' => 'is_deductible',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Tax Deductible?'),
    'description' => ts('Is this financial type tax-deductible? If true, contributions of this type may be fully OR partially deductible - non-deductible amount is stored in the Contribution record.'),
    'required' => TRUE,
    'where' => 'civicrm_financial_type.is_deductible',
    'default' => '0',
    'table_name' => 'civicrm_financial_type',
    'entity' => 'FinancialType',
    'bao' => 'CRM_Financial_BAO_FinancialType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Tax-Deductible?"),
    ],
    'add' => '1.3',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Financial Type is Reserved?'),
    'description' => ts('Is this a predefined system object?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_type.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_financial_type',
    'entity' => 'FinancialType',
    'bao' => 'CRM_Financial_BAO_FinancialType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Reserved?"),
    ],
    'add' => '1.3',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Financial Type Is Active?'),
    'description' => ts('Is this property active?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_type.is_active',
    'default' => '1',
    'table_name' => 'civicrm_financial_type',
    'entity' => 'FinancialType',
    'bao' => 'CRM_Financial_BAO_FinancialType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.3',
  ],
  ];
  
