<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Prev Next Cache ID'),
    'required' => TRUE,
    'where' => 'civicrm_prevnext_cache.id',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.4',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Prev Next Entity Table'),
    'description' => ts('physical tablename for entity being joined to discount, e.g. civicrm_event'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_prevnext_cache.entity_table',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'entity_id1' => [
    'name' => 'entity_id1',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Prev Next Entity ID 1'),
    'description' => ts('FK to entity table specified in entity_table column.'),
    'required' => TRUE,
    'where' => 'civicrm_prevnext_cache.entity_id1',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'entity_id2' => [
    'name' => 'entity_id2',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Prev Next Entity ID 2'),
    'description' => ts('FK to entity table specified in entity_table column.'),
    'required' => FALSE,
    'where' => 'civicrm_prevnext_cache.entity_id2',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'cachekey' => [
    'name' => 'cachekey',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Cache Key'),
    'description' => ts('Unique path name for cache element of the searched item'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_prevnext_cache.cachekey',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'data' => [
    'name' => 'data',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Prev Next Data'),
    'description' => ts('cached snapshot of the serialized data'),
    'where' => 'civicrm_prevnext_cache.data',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'add' => '3.4',
  ],
  'is_selected' => [
    'name' => 'is_selected',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Selected'),
    'required' => TRUE,
    'where' => 'civicrm_prevnext_cache.is_selected',
    'default' => '0',
    'table_name' => 'civicrm_prevnext_cache',
    'entity' => 'PrevNextCache',
    'bao' => 'CRM_Core_BAO_PrevNextCache',
    'localizable' => 0,
    'add' => '4.2',
  ],
  ];
  
