<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from xml/schema/CRM/Contribute/Premium.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:b9ad8bd1ae2ab323070563a87ada3037)
 */

/**
 * Database access object for the Premium entity.
 */
class CRM_Contribute_DAO_Premium_Fields {

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Premium ID'),
          'required' => TRUE,
          'where' => 'civicrm_premiums.id',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '1.4',
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Premium Entity'),
          'description' => ts('Joins these premium settings to another object. Always civicrm_contribution_page for now.'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_premiums.entity_table',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '1.4',
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Premium entity ID'),
          'required' => TRUE,
          'where' => 'civicrm_premiums.entity_id',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '1.4',
        ],
        'premiums_active' => [
          'name' => 'premiums_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is Premium Active?'),
          'description' => ts('Is the Premiums feature enabled for this page?'),
          'required' => TRUE,
          'where' => 'civicrm_premiums.premiums_active',
          'default' => '0',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '1.4',
        ],
        'premiums_intro_title' => [
          'name' => 'premiums_intro_title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Title for Premiums section'),
          'description' => ts('Title for Premiums section.'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_premiums.premiums_intro_title',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 1,
          'add' => '1.4',
        ],
        'premiums_intro_text' => [
          'name' => 'premiums_intro_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Premium Introductory Text'),
          'description' => ts('Displayed in <div> at top of Premiums section of page. Text and HTML allowed.'),
          'where' => 'civicrm_premiums.premiums_intro_text',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 1,
          'add' => '1.4',
        ],
        'premiums_contact_email' => [
          'name' => 'premiums_contact_email',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Premium Contact Email'),
          'description' => ts('This email address is included in receipts if it is populated and a premium has been selected.'),
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_premiums.premiums_contact_email',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '1.4',
        ],
        'premiums_contact_phone' => [
          'name' => 'premiums_contact_phone',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Premiums Contact Phone'),
          'description' => ts('This phone number is included in receipts if it is populated and a premium has been selected.'),
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_premiums.premiums_contact_phone',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '1.4',
        ],
        'premiums_display_min_contribution' => [
          'name' => 'premiums_display_min_contribution',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Display Minimum Contribution?'),
          'description' => ts('Boolean. Should we automatically display minimum contribution amount text after the premium descriptions.'),
          'required' => TRUE,
          'where' => 'civicrm_premiums.premiums_display_min_contribution',
          'default' => '0',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '1.4',
        ],
        'premiums_nothankyou_label' => [
          'name' => 'premiums_nothankyou_label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('No Thank-you Text'),
          'description' => ts('Label displayed for No Thank-you option in premiums block (e.g. No thank you)'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_premiums.premiums_nothankyou_label',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 1,
          'add' => '4.3',
        ],
        'premiums_nothankyou_position' => [
          'name' => 'premiums_nothankyou_position',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('No Thank-you Position'),
          'where' => 'civicrm_premiums.premiums_nothankyou_position',
          'default' => '1',
          'table_name' => 'civicrm_premiums',
          'entity' => 'Premium',
          'bao' => 'CRM_Contribute_BAO_Premium',
          'localizable' => 0,
          'add' => '4.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

}
