<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group ID'),
    'description' => ts('Group ID'),
    'required' => TRUE,
    'where' => 'civicrm_group.id',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Name'),
    'description' => ts('Internal name of Group.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_group.name',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Title'),
    'description' => ts('Name of Group.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_group.title',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Group Description'),
    'description' => ts('Optional verbose description of the group.'),
    'rows' => 2,
    'cols' => 60,
    'where' => 'civicrm_group.description',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '1.1',
  ],
  'source' => [
    'name' => 'source',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Source'),
    'description' => ts('Module or process which created this group.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_group.source',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'saved_search_id' => [
    'name' => 'saved_search_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Saved Search ID'),
    'description' => ts('FK to saved search table.'),
    'where' => 'civicrm_group.saved_search_id',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_SavedSearch',
    'html' => [
      'label' => ts("Saved Search"),
    ],
    'add' => '1.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Group Enabled'),
    'description' => ts('Is this group active?'),
    'required' => TRUE,
    'where' => 'civicrm_group.is_active',
    'default' => '1',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.1',
  ],
  'visibility' => [
    'name' => 'visibility',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Visibility Setting'),
    'description' => ts('In what context(s) is this field visible.'),
    'maxlength' => 24,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_group.visibility',
    'default' => 'User and User Admin Only',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::groupVisibility',
    ],
    'add' => '1.2',
  ],
  'where_clause' => [
    'name' => 'where_clause',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Group Where Clause'),
    'description' => ts('the sql where clause if a saved search acl'),
    'where' => 'civicrm_group.where_clause',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '1.6',
  ],
  'select_tables' => [
    'name' => 'select_tables',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Tables For Select Clause'),
    'description' => ts('the tables to be included in a select data'),
    'where' => 'civicrm_group.select_tables',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'readonly' => TRUE,
    'add' => '1.6',
  ],
  'where_tables' => [
    'name' => 'where_tables',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Tables For Where Clause'),
    'description' => ts('the tables to be included in the count statement'),
    'where' => 'civicrm_group.where_tables',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'readonly' => TRUE,
    'add' => '1.6',
  ],
  'group_type' => [
    'name' => 'group_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Type'),
    'description' => ts('FK to group type'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_group.group_type',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_SEPARATOR_BOOKEND,
    'pseudoconstant' => [
      'optionGroupName' => 'group_type',
      'optionEditPath' => 'civicrm/admin/options/group_type',
    ],
    'add' => '1.9',
  ],
  'cache_date' => [
    'name' => 'cache_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Group Cache Date'),
    'description' => ts('Date when we created the cache for a smart group'),
    'required' => FALSE,
    'where' => 'civicrm_group.cache_date',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '2.1',
  ],
  'refresh_date' => [
    'name' => 'refresh_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Next Group Refresh Time'),
    'description' => ts('Date and time when we need to refresh the cache next.'),
    'required' => FALSE,
    'where' => 'civicrm_group.refresh_date',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '4.3',
  ],
  'parents' => [
    'name' => 'parents',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Group Parents'),
    'description' => ts('IDs of the parent(s)'),
    'where' => 'civicrm_group.parents',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_COMMA,
    'pseudoconstant' => [
      'callback' => 'CRM_Core_PseudoConstant::allGroup',
    ],
    'add' => '2.1',
  ],
  'children' => [
    'name' => 'children',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Group Children'),
    'description' => ts('IDs of the child(ren)'),
    'where' => 'civicrm_group.children',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'add' => '2.1',
  ],
  'is_hidden' => [
    'name' => 'is_hidden',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Group is Hidden'),
    'description' => ts('Is this group hidden?'),
    'required' => TRUE,
    'where' => 'civicrm_group.is_hidden',
    'default' => '0',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Group is Reserved'),
    'required' => TRUE,
    'where' => 'civicrm_group.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to contact table.'),
    'where' => 'civicrm_group.created_id',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '4.3',
  ],
  'modified_id' => [
    'name' => 'modified_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Modified By Contact ID'),
    'description' => ts('FK to contact table.'),
    'where' => 'civicrm_group.modified_id',
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Modified By"),
    ],
    'readonly' => TRUE,
    'add' => '4.5',
  ],
  'frontend_title' => [
    'name' => 'frontend_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Public Group Title'),
    'description' => ts('Alternative public title for this Group.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_group.frontend_title',
    'default' => NULL,
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '5.31',
  ],
  'frontend_description' => [
    'name' => 'frontend_description',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Public Group Description'),
    'description' => ts('Alternative public description of the group.'),
    'rows' => 2,
    'cols' => 60,
    'where' => 'civicrm_group.frontend_description',
    'default' => NULL,
    'table_name' => 'civicrm_group',
    'entity' => 'Group',
    'bao' => 'CRM_Contact_BAO_Group',
    'localizable' => 1,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '5.31',
  ],
  ];
  
