<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Word Replacement ID'),
    'description' => ts('Word replacement ID'),
    'required' => TRUE,
    'where' => 'civicrm_word_replacement.id',
    'table_name' => 'civicrm_word_replacement',
    'entity' => 'WordReplacement',
    'bao' => 'CRM_Core_BAO_WordReplacement',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.4',
  ],
  'find_word' => [
    'name' => 'find_word',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Replaced Word'),
    'description' => ts('Word which need to be replaced'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_word_replacement.find_word',
    'table_name' => 'civicrm_word_replacement',
    'entity' => 'WordReplacement',
    'bao' => 'CRM_Core_BAO_WordReplacement',
    'localizable' => 0,
    'add' => '4.4',
  ],
  'replace_word' => [
    'name' => 'replace_word',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Replacement Word'),
    'description' => ts('Word which will replace the word in find'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_word_replacement.replace_word',
    'table_name' => 'civicrm_word_replacement',
    'entity' => 'WordReplacement',
    'bao' => 'CRM_Core_BAO_WordReplacement',
    'localizable' => 0,
    'add' => '4.4',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Word Replacement is Active'),
    'description' => ts('Is this entry active?'),
    'required' => TRUE,
    'where' => 'civicrm_word_replacement.is_active',
    'default' => '1',
    'table_name' => 'civicrm_word_replacement',
    'entity' => 'WordReplacement',
    'bao' => 'CRM_Core_BAO_WordReplacement',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.4',
  ],
  'match_type' => [
    'name' => 'match_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Word Replacement Match Type'),
    'maxlength' => 16,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_word_replacement.match_type',
    'default' => 'wildcardMatch',
    'table_name' => 'civicrm_word_replacement',
    'entity' => 'WordReplacement',
    'bao' => 'CRM_Core_BAO_WordReplacement',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getWordReplacementMatchType',
    ],
    'add' => '4.4',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('FK to Domain ID. This is for Domain specific word replacement'),
    'where' => 'civicrm_word_replacement.domain_id',
    'table_name' => 'civicrm_word_replacement',
    'entity' => 'WordReplacement',
    'bao' => 'CRM_Core_BAO_WordReplacement',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '1.1',
  ],
  ];
  
