<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('File ID'),
    'description' => ts('Unique ID'),
    'required' => TRUE,
    'where' => 'civicrm_file.id',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.5',
  ],
  'file_type_id' => [
    'name' => 'file_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('File Type'),
    'description' => ts('Type of file (e.g. Transcript, Income Tax Return, etc). FK to civicrm_option_value.'),
    'where' => 'civicrm_file.file_type_id',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'mime_type' => [
    'name' => 'mime_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mime Type'),
    'description' => ts('mime type of the document'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_file.mime_type',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'uri' => [
    'name' => 'uri',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Path'),
    'description' => ts('uri of the file on disk'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_file.uri',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'document' => [
    'name' => 'document',
    'type' => CRM_Utils_Type::T_MEDIUMBLOB,
    'title' => ts('File Contents'),
    'description' => ts('contents of the document'),
    'where' => 'civicrm_file.document',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('File Description'),
    'description' => ts('Additional descriptive text regarding this attachment (optional).'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_file.description',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'upload_date' => [
    'name' => 'upload_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('File Upload Date'),
    'description' => ts('Date and time that this attachment was uploaded or written to server.'),
    'where' => 'civicrm_file.upload_date',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to civicrm_contact, who uploaded this file'),
    'where' => 'civicrm_file.created_id',
    'table_name' => 'civicrm_file',
    'entity' => 'File',
    'bao' => 'CRM_Core_BAO_File',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '5.3',
  ],
  ];
  
