<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Friend ID'),
    'description' => ts('Friend ID'),
    'required' => TRUE,
    'where' => 'civicrm_tell_friend.id',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.0',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('Name of table where item being referenced is stored.'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_tell_friend.entity_table',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('Foreign key to the referenced item.'),
    'required' => TRUE,
    'where' => 'civicrm_tell_friend.entity_id',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Title'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_tell_friend.title',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'intro' => [
    'name' => 'intro',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Intro'),
    'description' => ts('Introductory message to contributor or participant displayed on the Tell a Friend form.'),
    'where' => 'civicrm_tell_friend.intro',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'suggested_message' => [
    'name' => 'suggested_message',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Suggested Message'),
    'description' => ts('Suggested message to friends, provided as default on the Tell A Friend form.'),
    'where' => 'civicrm_tell_friend.suggested_message',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'general_link' => [
    'name' => 'general_link',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('General Link'),
    'description' => ts('URL for general info about the organization - included in the email sent to friends.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_tell_friend.general_link',
    'export' => TRUE,
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'thankyou_title' => [
    'name' => 'thankyou_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Thank You Title'),
    'description' => ts('Text for Tell a Friend thank you page header and HTML title.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_tell_friend.thankyou_title',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'thankyou_text' => [
    'name' => 'thankyou_text',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Thank You Text'),
    'description' => ts('Thank you message displayed on success page.'),
    'where' => 'civicrm_tell_friend.thankyou_text',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.0',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Enabled?'),
    'required' => TRUE,
    'where' => 'civicrm_tell_friend.is_active',
    'default' => '1',
    'table_name' => 'civicrm_tell_friend',
    'entity' => 'Friend',
    'bao' => 'CRM_Friend_BAO_Friend',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '2.0',
  ],
  ];
  
