<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Note ID'),
    'description' => ts('Note ID'),
    'required' => TRUE,
    'where' => 'civicrm_note.id',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Note Entity'),
    'description' => ts('Name of table where item being referenced is stored.'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_note.entity_table',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'note_used_for',
      'optionEditPath' => 'civicrm/admin/options/note_used_for',
    ],
    'add' => '1.1',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Note Entity ID'),
    'description' => ts('Foreign key to the referenced item.'),
    'required' => TRUE,
    'where' => 'civicrm_note.entity_id',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'note' => [
    'name' => 'note',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Note'),
    'description' => ts('Note and/or Comment.'),
    'rows' => 4,
    'cols' => 60,
    'import' => TRUE,
    'where' => 'civicrm_note.note',
    'headerPattern' => '/Note|Comment/i',
    'dataPattern' => '//',
    'export' => TRUE,
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '1.1',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to Contact ID creator'),
    'where' => 'civicrm_note.contact_id',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '1.1',
  ],
  'note_date' => [
    'name' => 'note_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Note Date'),
    'description' => ts('Date attached to the note'),
    'where' => 'civicrm_note.note_date',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '5.36',
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Created Date'),
    'description' => ts('When the note was created.'),
    'required' => TRUE,
    'where' => 'civicrm_note.created_date',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'add' => '5.36',
  ],
  'modified_date' => [
    'name' => 'modified_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Note Modified By'),
    'description' => ts('When was this note last modified/edited'),
    'where' => 'civicrm_note.modified_date',
    'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'subject' => [
    'name' => 'subject',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Subject'),
    'description' => ts('subject of note description'),
    'maxlength' => 255,
    'size' => 60,
    'where' => 'civicrm_note.subject',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.5',
  ],
  'privacy' => [
    'name' => 'privacy',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Privacy'),
    'description' => ts('Foreign Key to Note Privacy Level (which is an option value pair and hence an implicit FK)'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_note.privacy',
    'table_name' => 'civicrm_note',
    'entity' => 'Note',
    'bao' => 'CRM_Core_BAO_Note',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'note_privacy',
      'optionEditPath' => 'civicrm/admin/options/note_privacy',
    ],
    'add' => '3.3',
  ],
  ];
  
