<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Domain ID'),
    'required' => TRUE,
    'where' => 'civicrm_domain.id',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Domain Name'),
    'description' => ts('Name of Domain / Organization'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_domain.name',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Domain Description'),
    'description' => ts('Description of Domain.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_domain.description',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'version' => [
    'name' => 'version',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('CiviCRM Version'),
    'description' => ts('The civicrm version this instance is running'),
    'maxlength' => 32,
    'size' => CRM_Utils_Type::MEDIUM,
    'where' => 'civicrm_domain.version',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID. This is specifically not an FK to avoid circular constraints'),
    'where' => 'civicrm_domain.contact_id',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '4.3',
  ],
  'locales' => [
    'name' => 'locales',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Supported Languages'),
    'description' => ts('list of locales supported by the current db state (NULL for single-lang install)'),
    'where' => 'civicrm_domain.locales',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_SEPARATOR_TRIMMED,
    'add' => '2.1',
  ],
  'locale_custom_strings' => [
    'name' => 'locale_custom_strings',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Language Customizations'),
    'description' => ts('Locale specific string overrides'),
    'where' => 'civicrm_domain.locale_custom_strings',
    'table_name' => 'civicrm_domain',
    'entity' => 'Domain',
    'bao' => 'CRM_Core_BAO_Domain',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'add' => '3.2',
  ],
  ];
  
