<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Dedupe Exception ID'),
    'description' => ts('Unique dedupe exception id'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_exception.id',
    'table_name' => 'civicrm_dedupe_exception',
    'entity' => 'DedupeException',
    'bao' => 'CRM_Dedupe_BAO_DedupeException',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.3',
  ],
  'contact_id1' => [
    'name' => 'contact_id1',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('First Dupe Contact ID'),
    'description' => ts('FK to Contact ID'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_exception.contact_id1',
    'table_name' => 'civicrm_dedupe_exception',
    'entity' => 'DedupeException',
    'bao' => 'CRM_Dedupe_BAO_DedupeException',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("First Dupe Contact"),
    ],
    'add' => '3.3',
  ],
  'contact_id2' => [
    'name' => 'contact_id2',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Second Dupe Contact ID'),
    'description' => ts('FK to Contact ID'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_exception.contact_id2',
    'table_name' => 'civicrm_dedupe_exception',
    'entity' => 'DedupeException',
    'bao' => 'CRM_Dedupe_BAO_DedupeException',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Second Dupe Contact"),
    ],
    'add' => '3.3',
  ],
  ];
  
