<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Rule Group ID'),
    'description' => ts('Unique dedupe rule group id'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_rule_group.id',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.8',
  ],
  'contact_type' => [
    'name' => 'contact_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Type'),
    'description' => ts('The type of contacts this group applies to'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_dedupe_rule_group.contact_type',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_contact_type',
      'keyColumn' => 'name',
      'labelColumn' => 'label',
      'condition' => 'parent_id IS NULL',
    ],
    'add' => '1.8',
  ],
  'threshold' => [
    'name' => 'threshold',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Threshold'),
    'description' => ts('The weight threshold the sum of the rule weights has to cross to consider two contacts the same'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_rule_group.threshold',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'used' => [
    'name' => 'used',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Length'),
    'description' => ts('Whether the rule should be used for cases where usage is Unsupervised, Supervised OR General(programatically)'),
    'required' => TRUE,
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_dedupe_rule_group.used',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Radio',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getDedupeRuleTypes',
    ],
    'add' => '4.3',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Name'),
    'description' => ts('Unique name of rule group'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dedupe_rule_group.name',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'add' => '2.1',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Title'),
    'description' => ts('Label of the rule group'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dedupe_rule_group.title',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.1',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Reserved?'),
    'description' => ts('Is this a reserved rule - a rule group that has been optimized and cannot be changed by the admin'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_rule_group.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_dedupe_rule_group',
    'entity' => 'DedupeRuleGroup',
    'bao' => 'CRM_Dedupe_BAO_DedupeRuleGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '4.1',
  ],
  ];
  
