<?php
extract(array (
  'generated' => 'DO NOT EDIT.  Generated by CRM_Core_CodeGen',
  'table' => 
  array (
    'name' => 'civicrm_case',
    'base' => 'CRM/Case/DAO/',
    'sourceFile' => 'xml/schema/CRM/Case/Case.xml',
    'fileName' => 'Case.php',
    'objectName' => 'Case',
    'title' => 'Case',
    'titlePlural' => 'Cases',
    'icon' => 'fa-folder-open',
    'labelField' => 'subject',
    'add' => '1.8',
    'component' => 'CiviCase',
    'paths' => 
    array (
    ),
    'labelName' => 'case',
    'className' => 'CRM_Case_DAO_Case',
    'bao' => 'CRM_Case_BAO_Case',
    'entity' => 'Case',
    'attributes_simple' => 'TYPE=InnoDB',
    'attributes_modern' => 'ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC',
    'comment' => 'This table stores information about cases grouping activities.',
    'description' => 'Collections of activities and relationships for a given purpose.',
    'localizable' => false,
    'log' => 'true',
    'archive' => 'false',
    'fields' => 
    array (
      'id' => 
      array (
        'name' => 'id',
        'localizable' => 0,
        'phpType' => 'int',
        'sqlType' => 'int unsigned',
        'crmType' => 'CRM_Utils_Type::T_INT',
        'required' => 'true',
        'collate' => NULL,
        'comment' => 'Unique Case ID',
        'default' => NULL,
        'import' => 'true',
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Case ID',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_id',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'Number',
        ),
        'contactType' => NULL,
        'add' => '1.8',
        'pseudoconstant' => NULL,
        'autoincrement' => 'true',
      ),
      'case_type_id' => 
      array (
        'name' => 'case_type_id',
        'localizable' => 0,
        'phpType' => 'int',
        'sqlType' => 'int unsigned',
        'crmType' => 'CRM_Utils_Type::T_INT',
        'required' => 'true',
        'collate' => NULL,
        'comment' => 'FK to civicrm_case_type.id',
        'default' => NULL,
        'import' => 'true',
        'export' => 'false',
        'rule' => NULL,
        'title' => 'Case Type ID',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => NULL,
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'Select',
          'label' => 'Case Type',
        ),
        'contactType' => NULL,
        'add' => '2.0',
        'pseudoconstant' => 
        array (
          'table' => 'civicrm_case_type',
          'keyColumn' => 'id',
          'labelColumn' => 'title',
        ),
        'FKClassName' => 'CRM_Case_DAO_CaseType',
      ),
      'subject' => 
      array (
        'name' => 'subject',
        'localizable' => 0,
        'length' => 128,
        'sqlType' => 'varchar(128)',
        'phpType' => 'string',
        'crmType' => 'CRM_Utils_Type::T_STRING',
        'size' => 'CRM_Utils_Type::HUGE',
        'required' => NULL,
        'collate' => NULL,
        'comment' => 'Short name of the case.',
        'default' => NULL,
        'import' => 'true',
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Case Subject',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_subject',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'Text',
        ),
        'contactType' => NULL,
        'add' => '1.8',
        'pseudoconstant' => NULL,
      ),
      'start_date' => 
      array (
        'name' => 'start_date',
        'localizable' => 0,
        'phpType' => 'date',
        'sqlType' => 'date',
        'crmType' => 'CRM_Utils_Type::T_DATE',
        'required' => NULL,
        'collate' => NULL,
        'comment' => 'Date on which given case starts.',
        'default' => NULL,
        'import' => 'true',
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Case Start Date',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_start_date',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'Select Date',
          'formatType' => 'activityDateTime',
        ),
        'contactType' => NULL,
        'add' => '1.8',
        'pseudoconstant' => NULL,
      ),
      'end_date' => 
      array (
        'name' => 'end_date',
        'localizable' => 0,
        'phpType' => 'date',
        'sqlType' => 'date',
        'crmType' => 'CRM_Utils_Type::T_DATE',
        'required' => NULL,
        'collate' => NULL,
        'comment' => 'Date on which given case ends.',
        'default' => NULL,
        'import' => 'true',
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Case End Date',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_end_date',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'Select Date',
          'formatType' => 'activityDateTime',
        ),
        'contactType' => NULL,
        'add' => '1.8',
        'pseudoconstant' => NULL,
      ),
      'details' => 
      array (
        'name' => 'details',
        'localizable' => 0,
        'phpType' => 'text',
        'sqlType' => 'text',
        'crmType' => 'CRM_Utils_Type::T_TEXT',
        'rows' => '8',
        'cols' => '60',
        'required' => NULL,
        'collate' => NULL,
        'comment' => 'Details populated from Open Case. Only used in the CiviCase extension.',
        'default' => NULL,
        'import' => NULL,
        'export' => NULL,
        'rule' => NULL,
        'title' => 'Details',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => NULL,
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'TextArea',
          'label' => 'Details',
        ),
        'contactType' => NULL,
        'add' => '1.8',
        'pseudoconstant' => NULL,
      ),
      'status_id' => 
      array (
        'name' => 'status_id',
        'localizable' => 0,
        'phpType' => 'int',
        'sqlType' => 'int unsigned',
        'crmType' => 'CRM_Utils_Type::T_INT',
        'required' => 'true',
        'collate' => NULL,
        'comment' => 'ID of case status.',
        'default' => NULL,
        'import' => 'true',
        'export' => 'false',
        'rule' => NULL,
        'title' => 'Case Status',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_status_id',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'Select',
        ),
        'contactType' => NULL,
        'add' => '1.8',
        'pseudoconstant' => 
        array (
          'optionGroupName' => 'case_status',
          'optionEditPath' => 'civicrm/admin/options/case_status',
        ),
      ),
      'is_deleted' => 
      array (
        'name' => 'is_deleted',
        'localizable' => 0,
        'sqlType' => 'tinyint',
        'phpType' => 'bool',
        'crmType' => 'CRM_Utils_Type::T_BOOLEAN',
        'required' => NULL,
        'collate' => NULL,
        'comment' => NULL,
        'default' => '0',
        'import' => 'true',
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Case is in the Trash',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_deleted',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'type' => 'CheckBox',
        ),
        'contactType' => NULL,
        'add' => '2.2',
        'pseudoconstant' => NULL,
      ),
      'created_date' => 
      array (
        'name' => 'created_date',
        'localizable' => 0,
        'phpType' => 'timestamp',
        'sqlType' => 'timestamp',
        'crmType' => 'CRM_Utils_Type::T_TIMESTAMP',
        'required' => 'false',
        'collate' => NULL,
        'comment' => 'When was the case was created.',
        'default' => 'NULL',
        'import' => NULL,
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Created Date',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => NULL,
        'uniqueName' => 'case_created_date',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'label' => 'Created Date',
        ),
        'contactType' => NULL,
        'add' => '4.7',
        'pseudoconstant' => NULL,
      ),
      'modified_date' => 
      array (
        'name' => 'modified_date',
        'localizable' => 0,
        'phpType' => 'timestamp',
        'sqlType' => 'timestamp',
        'crmType' => 'CRM_Utils_Type::T_TIMESTAMP',
        'required' => 'false',
        'collate' => NULL,
        'comment' => 'When was the case (or closely related entity) was created or modified or deleted.',
        'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
        'import' => NULL,
        'export' => 'true',
        'rule' => NULL,
        'title' => 'Modified Date',
        'headerPattern' => NULL,
        'dataPattern' => NULL,
        'readonly' => 'true',
        'uniqueName' => 'case_modified_date',
        'uniqueTitle' => NULL,
        'serialize' => NULL,
        'component' => NULL,
        'html' => 
        array (
          'label' => 'Modified Date',
        ),
        'contactType' => NULL,
        'add' => '4.7',
        'pseudoconstant' => NULL,
      ),
    ),
    'primaryKey' => 
    array (
      'name' => 'id',
      'autoincrement' => 'true',
      'field' => 
      array (
        0 => 'id',
      ),
    ),
    'index' => 
    array (
      'index_case_type_id' => 
      array (
        'name' => 'index_case_type_id',
        'field' => 
        array (
          0 => 'case_type_id',
        ),
        'localizable' => false,
        'sig' => 'civicrm_case::0::case_type_id',
      ),
      'index_is_deleted' => 
      array (
        'name' => 'index_is_deleted',
        'field' => 
        array (
          0 => 'is_deleted',
        ),
        'localizable' => false,
        'sig' => 'civicrm_case::0::is_deleted',
      ),
    ),
    'foreignKey' => 
    array (
      'case_type_id' => 
      array (
        'name' => 'case_type_id',
        'table' => 'civicrm_case_type',
        'uniqName' => 'FK_civicrm_case_case_type_id',
        'key' => 'id',
        'import' => false,
        'export' => false,
        'className' => 'CRM_Case_DAO_CaseType',
        'onDelete' => false,
        'fileName' => 'CRM/Case/DAO/CaseType.php',
      ),
    ),
  ),
  'indicesPhp' => 'array (
  \'index_case_type_id\' => 
  array (
    \'name\' => \'index_case_type_id\',
    \'field\' => 
    array (
      0 => \'case_type_id\',
    ),
    \'localizable\' => false,
    \'sig\' => \'civicrm_case::0::case_type_id\',
  ),
  \'index_is_deleted\' => 
  array (
    \'name\' => \'index_is_deleted\',
    \'field\' => 
    array (
      0 => \'is_deleted\',
    ),
    \'localizable\' => false,
    \'sig\' => \'civicrm_case::0::is_deleted\',
  ),
)',
  'tsFunctionName' => 'ts',
  'ext' => '\'civicrm\'',
  'useHelper' => '',
  'genCodeChecksum' => '1ae35a7a60938212678c1585defc3506',
));
echo '<?php'."\n";
echo '/' . '**'."\n";
echo ' * @package CRM'."\n";
echo ' * @copyright CiviCRM LLC https://civicrm.org/licensing'."\n";
echo ' *'."\n";
echo ' * Generated from ' . $table["sourceFile"] .''."\n";
echo ' * ' . $generated .''."\n";
echo ' * (GenCodeChecksum:' . $genCodeChecksum .')'."\n";
echo ' */'."\n";
 echo $useHelper;
echo ''."\n";
echo '/' . '**'."\n";
echo ' * Database access object for the ' . $table["entity"] .' entity.'."\n";
echo ' */'."\n";
echo 'class ' . $table["className"] .' extends CRM_Core_DAO {'."\n";
echo '  const EXT = ' . $ext .';'."\n";
echo '  const TABLE_ADDED = ' . var_export($table["add"], 1) .';'."\n";
 if (!empty($table['component'])) printf("  const COMPONENT = %s;\n", var_export($table['component'], 1));
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Static instance to hold the table name.'."\n";
echo '   *'."\n";
echo '   * @var string'."\n";
echo '   */'."\n";
echo '  public static $_tableName = ' . var_export($table["name"], 1) .';'."\n";
echo ''."\n";
 if (!empty($table['icon'])) {
echo '  /' . '**'."\n";
echo '   * Icon associated with this entity.'."\n";
echo '   *'."\n";
echo '   * @var string'."\n";
echo '   */'."\n";
echo '  public static $_icon = ' . var_export($table["icon"], 1) .';'."\n";
 }
echo ''."\n";
 if (!empty($table['labelField'])) {
echo '  /' . '**'."\n";
echo '   * Field to show when displaying a record.'."\n";
echo '   *'."\n";
echo '   * @var string'."\n";
echo '   */'."\n";
echo '  public static $_labelField = ' . var_export($table["labelField"], 1) .';'."\n";
 }
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Should CiviCRM log any modifications to this table in the civicrm_log table.'."\n";
echo '   *'."\n";
echo '   * @var bool'."\n";
echo '   */'."\n";
 printf("  public static \$_log = %s;\n", strtoupper($table['log']));
echo ''."\n";
 foreach($table['fields'] as $field) {
   printf("  /**\n");
   if ($field['comment']) printf("   * %s\n   *\n", preg_replace("/\n[ ]*/", "\n* ", $field['comment']));
   printf("   * @var %s\n", $field['phpType']);
   printf("   */\n");
   printf("  public \$%s;\n", $field['name']);
 }
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Class constructor.'."\n";
echo '   */'."\n";
echo '  public function __construct() {'."\n";
echo '    $this->__table = ' . var_export($table["name"], 1) .';'."\n";
echo '    parent::__construct();'."\n";
echo '  }'."\n";
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Returns localized title of this entity.'."\n";
echo '   *'."\n";
echo '   * @param bool $plural'."\n";
echo '   *   Whether to return the plural version of the title.'."\n";
echo '   */'."\n";
echo '  public static function getEntityTitle($plural = FALSE) {'."\n";
echo '    return $plural ? ' . $tsFunctionName .'(' . var_export($table["titlePlural"], 1) .') : ' . $tsFunctionName .'(' . var_export($table["title"], 1) .');'."\n";
echo '  }'."\n";
echo ''."\n";
 if (!empty($table['description'])) {
echo '  /' . '**'."\n";
echo '   * Returns user-friendly description of this entity.'."\n";
echo '   *'."\n";
echo '   * @return string'."\n";
echo '   */'."\n";
echo '  public static function getEntityDescription() {'."\n";
echo '    return ' . $tsFunctionName .'(' . var_export($table["description"], 1) .');'."\n";
echo '  }'."\n";
 }
echo ''."\n";
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Return a mapping from field-name to the corresponding key (as used in fields()).'."\n";
echo '   *'."\n";
echo '   * @return array'."\n";
echo '   *   Array(string $name => string $uniqueName).'."\n";
echo '   */'."\n";
echo '  public static function &fieldKeys() {'."\n";
echo '    if (!isset(Civi::$statics[__CLASS__][\'fieldKeys\'])) {'."\n";
echo '      Civi::$statics[__CLASS__][\'fieldKeys\'] = array_flip(CRM_Utils_Array::collect(\'name\', self::fields()));'."\n";
echo '    }'."\n";
echo '    return Civi::$statics[__CLASS__][\'fieldKeys\'];'."\n";
echo '  }'."\n";
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Returns if this table needs to be logged'."\n";
echo '   *'."\n";
echo '   * @return bool'."\n";
echo '   */'."\n";
echo '  public function getLog() {'."\n";
echo '    return self::$_log;'."\n";
echo '  }'."\n";
echo ''."\n";
echo '  /' . '**'."\n";
echo '   * Returns the list of indices'."\n";
echo '   *'."\n";
echo '   * @param bool $localize'."\n";
echo '   *'."\n";
echo '   * @return array'."\n";
echo '   */'."\n";
echo '  public static function indices($localize = TRUE) {'."\n";
echo '    $indices = ' . $indicesPhp .';'."\n";
echo '    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;'."\n";
echo '  }'."\n";
echo ''."\n";
echo '}'."\n";
