<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Payment Processor ID'),
    'description' => ts('Payment Processor ID'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.id',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.8',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this match entry for'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.domain_id',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '3.0',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Payment Processor'),
    'description' => ts('Payment Processor Name.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_payment_processor.name',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Payment Processor Title'),
    'description' => ts('Payment Processor Descriptive Name.'),
    'maxlength' => 127,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.title',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '5.13',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Processor Description'),
    'description' => ts('Payment Processor Description.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.description',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'payment_processor_type_id' => [
    'name' => 'payment_processor_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Type ID'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.payment_processor_type_id',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'FKClassName' => 'CRM_Financial_DAO_PaymentProcessorType',
    'html' => [
      'label' => ts("Type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_payment_processor_type',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '4.3',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Processor is Active?'),
    'description' => ts('Is this processor active?'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.is_active',
    'default' => '1',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.8',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Processor Is Default?'),
    'description' => ts('Is this processor the default?'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.is_default',
    'default' => '0',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '1.8',
  ],
  'is_test' => [
    'name' => 'is_test',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Test Processor?'),
    'description' => ts('Is this processor for a test site?'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.is_test',
    'default' => '0',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'user_name' => [
    'name' => 'user_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('User Name'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.user_name',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'password' => [
    'name' => 'password',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Password'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.password',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Password',
    ],
    'add' => '1.8',
  ],
  'signature' => [
    'name' => 'signature',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Signature'),
    'rows' => 4,
    'cols' => 40,
    'where' => 'civicrm_payment_processor.signature',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '1.8',
  ],
  'url_site' => [
    'name' => 'url_site',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Site URL'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.url_site',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'url_api' => [
    'name' => 'url_api',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('API URL'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.url_api',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'url_recur' => [
    'name' => 'url_recur',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Recurring Payments URL'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.url_recur',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'url_button' => [
    'name' => 'url_button',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Button URL'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.url_button',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'subject' => [
    'name' => 'subject',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Subject'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.subject',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'class_name' => [
    'name' => 'class_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Suffix for PHP class name implementation'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_payment_processor.class_name',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'billing_mode' => [
    'name' => 'billing_mode',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Processor Billing Mode'),
    'description' => ts('Billing Mode (deprecated)'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.billing_mode',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'is_recur' => [
    'name' => 'is_recur',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Processor Supports Recurring?'),
    'description' => ts('Can process recurring contributions'),
    'required' => TRUE,
    'where' => 'civicrm_payment_processor.is_recur',
    'default' => '0',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'payment_type' => [
    'name' => 'payment_type',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Payment Type'),
    'description' => ts('Payment Type: Credit or Debit (deprecated)'),
    'where' => 'civicrm_payment_processor.payment_type',
    'default' => '1',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'add' => '3.0',
  ],
  'payment_instrument_id' => [
    'name' => 'payment_instrument_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Payment Method'),
    'description' => ts('Payment Instrument ID'),
    'where' => 'civicrm_payment_processor.payment_instrument_id',
    'default' => '1',
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'payment_instrument',
      'optionEditPath' => 'civicrm/admin/options/payment_instrument',
    ],
    'add' => '4.7',
  ],
  'accepted_credit_cards' => [
    'name' => 'accepted_credit_cards',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Accepted Credit Cards'),
    'description' => ts('array of accepted credit card types'),
    'where' => 'civicrm_payment_processor.accepted_credit_cards',
    'default' => NULL,
    'table_name' => 'civicrm_payment_processor',
    'entity' => 'PaymentProcessor',
    'bao' => 'CRM_Financial_BAO_PaymentProcessor',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_JSON,
    'add' => '4.7',
  ],
  ];
  
