<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Membership Block ID'),
    'description' => ts('Membership ID'),
    'required' => TRUE,
    'where' => 'civicrm_membership_block.id',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.5',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Membership Block Entity Table'),
    'description' => ts('Name for Membership Status'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_membership_block.entity_table',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('FK to civicrm_contribution_page.id'),
    'required' => TRUE,
    'where' => 'civicrm_membership_block.entity_id',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_ContributionPage',
    'html' => [
      'label' => ts("Entity"),
    ],
    'add' => '1.5',
  ],
  'membership_types' => [
    'name' => 'membership_types',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Membership Block Membership Types'),
    'description' => ts('Membership types to be exposed by this block'),
    'maxlength' => 1024,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_membership_block.membership_types',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'add' => '1.5',
  ],
  'membership_type_default' => [
    'name' => 'membership_type_default',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Default Type ID'),
    'description' => ts('Optional foreign key to membership_type'),
    'where' => 'civicrm_membership_block.membership_type_default',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'FKClassName' => 'CRM_Member_DAO_MembershipType',
    'html' => [
      'label' => ts("Default Type"),
    ],
    'add' => '1.5',
  ],
  'display_min_fee' => [
    'name' => 'display_min_fee',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Membership Block Display Minimum Fee'),
    'description' => ts('Display minimum membership fee'),
    'required' => TRUE,
    'where' => 'civicrm_membership_block.display_min_fee',
    'default' => '1',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'is_separate_payment' => [
    'name' => 'is_separate_payment',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Membership Block Is Separate Payment'),
    'description' => ts('Should membership transactions be processed separately'),
    'required' => TRUE,
    'where' => 'civicrm_membership_block.is_separate_payment',
    'default' => '1',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'new_title' => [
    'name' => 'new_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Membership Block New Title'),
    'description' => ts('Title to display at top of block'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_membership_block.new_title',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 1,
    'add' => '1.5',
  ],
  'new_text' => [
    'name' => 'new_text',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Membership Block New Text'),
    'description' => ts('Text to display below title'),
    'where' => 'civicrm_membership_block.new_text',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 1,
    'add' => '1.5',
  ],
  'renewal_title' => [
    'name' => 'renewal_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Membership Block Renewal Title'),
    'description' => ts('Title for renewal'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_membership_block.renewal_title',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 1,
    'add' => '1.5',
  ],
  'renewal_text' => [
    'name' => 'renewal_text',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Membership Block Renewal Text'),
    'description' => ts('Text to display for member renewal'),
    'where' => 'civicrm_membership_block.renewal_text',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 1,
    'add' => '1.5',
  ],
  'is_required' => [
    'name' => 'is_required',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Required'),
    'description' => ts('Is membership sign up optional'),
    'required' => TRUE,
    'where' => 'civicrm_membership_block.is_required',
    'default' => '0',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Active'),
    'description' => ts('Is this membership_block enabled'),
    'required' => TRUE,
    'where' => 'civicrm_membership_block.is_active',
    'default' => '1',
    'table_name' => 'civicrm_membership_block',
    'entity' => 'MembershipBlock',
    'bao' => 'CRM_Member_BAO_MembershipBlock',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.5',
  ],
  ];
  
