<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Timezone ID'),
    'description' => ts('Timezone ID'),
    'required' => TRUE,
    'where' => 'civicrm_timezone.id',
    'table_name' => 'civicrm_timezone',
    'entity' => 'Timezone',
    'bao' => 'CRM_Core_DAO_Timezone',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.8',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Timezone Name'),
    'description' => ts('Timezone full name'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_timezone.name',
    'table_name' => 'civicrm_timezone',
    'entity' => 'Timezone',
    'bao' => 'CRM_Core_DAO_Timezone',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'abbreviation' => [
    'name' => 'abbreviation',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Timezone Abbreviation'),
    'description' => ts('ISO Code for timezone abbreviation'),
    'maxlength' => 3,
    'size' => CRM_Utils_Type::FOUR,
    'where' => 'civicrm_timezone.abbreviation',
    'table_name' => 'civicrm_timezone',
    'entity' => 'Timezone',
    'bao' => 'CRM_Core_DAO_Timezone',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'gmt' => [
    'name' => 'gmt',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('GMT Name of Timezone'),
    'description' => ts('GMT name of the timezone'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_timezone.gmt',
    'table_name' => 'civicrm_timezone',
    'entity' => 'Timezone',
    'bao' => 'CRM_Core_DAO_Timezone',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'offset' => [
    'name' => 'offset',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('GMT Offset'),
    'where' => 'civicrm_timezone.offset',
    'table_name' => 'civicrm_timezone',
    'entity' => 'Timezone',
    'bao' => 'CRM_Core_DAO_Timezone',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'country_id' => [
    'name' => 'country_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Country ID'),
    'description' => ts('Country ID'),
    'required' => TRUE,
    'where' => 'civicrm_timezone.country_id',
    'table_name' => 'civicrm_timezone',
    'entity' => 'Timezone',
    'bao' => 'CRM_Core_DAO_Timezone',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Country',
    'html' => [
      'label' => ts("Country"),
    ],
    'add' => '1.8',
  ],
  ];
  
