<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Subscribe ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_subscribe.id',
    'table_name' => 'civicrm_mailing_event_subscribe',
    'entity' => 'MailingEventSubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventSubscribe',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'group_id' => [
    'name' => 'group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group ID'),
    'description' => ts('FK to Group'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_subscribe.group_id',
    'table_name' => 'civicrm_mailing_event_subscribe',
    'entity' => 'MailingEventSubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventSubscribe',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Group',
    'html' => [
      'type' => 'Select',
      'label' => ts("Group"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => NULL,
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_subscribe.contact_id',
    'table_name' => 'civicrm_mailing_event_subscribe',
    'entity' => 'MailingEventSubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventSubscribe',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => NULL,
  ],
  'hash' => [
    'name' => 'hash',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Subscribe Hash'),
    'description' => ts('Security hash'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_event_subscribe.hash',
    'table_name' => 'civicrm_mailing_event_subscribe',
    'entity' => 'MailingEventSubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventSubscribe',
    'localizable' => 0,
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Subscribe Timestamp'),
    'description' => ts('When this subscription event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_subscribe.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_subscribe',
    'entity' => 'MailingEventSubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventSubscribe',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
