<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Bounce ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_bounce.id',
    'table_name' => 'civicrm_mailing_event_bounce',
    'entity' => 'MailingEventBounce',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventBounce',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'event_queue_id' => [
    'name' => 'event_queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Event Queue ID'),
    'description' => ts('FK to EventQueue'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_bounce.event_queue_id',
    'table_name' => 'civicrm_mailing_event_bounce',
    'entity' => 'MailingEventBounce',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventBounce',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventQueue',
    'html' => [
      'label' => ts("Recipient"),
    ],
    'add' => NULL,
  ],
  'bounce_type_id' => [
    'name' => 'bounce_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Bounce Type ID'),
    'description' => ts('What type of bounce was it?'),
    'where' => 'civicrm_mailing_event_bounce.bounce_type_id',
    'table_name' => 'civicrm_mailing_event_bounce',
    'entity' => 'MailingEventBounce',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventBounce',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("Bounce Type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_mailing_bounce_type',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => NULL,
  ],
  'bounce_reason' => [
    'name' => 'bounce_reason',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Bounce Reason'),
    'description' => ts('The reason the email bounced.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_event_bounce.bounce_reason',
    'table_name' => 'civicrm_mailing_event_bounce',
    'entity' => 'MailingEventBounce',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventBounce',
    'localizable' => 0,
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Timestamp'),
    'description' => ts('When this bounce event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_bounce.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_bounce',
    'entity' => 'MailingEventBounce',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventBounce',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
