<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Survey ID'),
    'description' => ts('Survey id.'),
    'required' => TRUE,
    'where' => 'civicrm_survey.id',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.3',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Survey Title'),
    'description' => ts('Title of the Survey.'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_survey.title',
    'export' => TRUE,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.3',
  ],
  'campaign_id' => [
    'name' => 'campaign_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Campaign ID'),
    'description' => ts('Foreign key to the Campaign.'),
    'where' => 'civicrm_survey.campaign_id',
    'default' => NULL,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'FKClassName' => 'CRM_Campaign_DAO_Campaign',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Campaign"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_campaign',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'prefetch' => 'FALSE',
    ],
    'add' => '3.3',
  ],
  'activity_type_id' => [
    'name' => 'activity_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity Type'),
    'description' => ts('Implicit FK to civicrm_option_value where option_group = activity_type'),
    'import' => TRUE,
    'where' => 'civicrm_survey.activity_type_id',
    'export' => TRUE,
    'default' => NULL,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'activity_type',
      'optionEditPath' => 'civicrm/admin/options/activity_type',
    ],
    'add' => '3.3',
  ],
  'recontact_interval' => [
    'name' => 'recontact_interval',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Follow up Interval'),
    'description' => ts('Recontact intervals for each status.'),
    'rows' => 20,
    'cols' => 80,
    'where' => 'civicrm_survey.recontact_interval',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '3.3',
  ],
  'instructions' => [
    'name' => 'instructions',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Instructions'),
    'description' => ts('Script instructions for volunteers to use for the survey.'),
    'rows' => 20,
    'cols' => 80,
    'where' => 'civicrm_survey.instructions',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 1,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '3.3',
  ],
  'release_frequency' => [
    'name' => 'release_frequency',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Survey Hold Duration'),
    'description' => ts('Number of days for recurrence of release.'),
    'where' => 'civicrm_survey.release_frequency',
    'default' => NULL,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'max_number_of_contacts' => [
    'name' => 'max_number_of_contacts',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Maximum number of contacts'),
    'description' => ts('Maximum number of contacts to allow for survey.'),
    'where' => 'civicrm_survey.max_number_of_contacts',
    'default' => NULL,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'default_number_of_contacts' => [
    'name' => 'default_number_of_contacts',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Default number of contacts'),
    'description' => ts('Default number of contacts to allow for survey.'),
    'where' => 'civicrm_survey.default_number_of_contacts',
    'default' => NULL,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Survey Is Active'),
    'description' => ts('Is this survey enabled or disabled/cancelled?'),
    'required' => TRUE,
    'where' => 'civicrm_survey.is_active',
    'default' => '1',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '3.3',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Default Survey'),
    'description' => ts('Is this default survey?'),
    'required' => TRUE,
    'where' => 'civicrm_survey.is_default',
    'default' => '0',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '3.3',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to civicrm_contact, who created this Survey.'),
    'where' => 'civicrm_survey.created_id',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '3.3',
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Campaign Created Date'),
    'description' => ts('Date and time that Survey was created.'),
    'where' => 'civicrm_survey.created_date',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'last_modified_id' => [
    'name' => 'last_modified_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Modified By Contact ID'),
    'description' => ts('FK to civicrm_contact, who recently edited this Survey.'),
    'where' => 'civicrm_survey.last_modified_id',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Modified By"),
    ],
    'add' => '3.3',
  ],
  'last_modified_date' => [
    'name' => 'last_modified_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Survey Modified On'),
    'description' => ts('Date and time that Survey was edited last time.'),
    'where' => 'civicrm_survey.last_modified_date',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'result_id' => [
    'name' => 'result_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Survey Result'),
    'description' => ts('Used to store option group id.'),
    'where' => 'civicrm_survey.result_id',
    'default' => NULL,
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'pseudoconstant' => [
      'table' => 'civicrm_option_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'nameColumn' => 'name',
      'condition' => 'name LIKE "civicrm_survey_%"',
    ],
    'add' => '3.3',
  ],
  'bypass_confirm' => [
    'name' => 'bypass_confirm',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('No Email Verification'),
    'description' => ts('Bypass the email verification.'),
    'required' => TRUE,
    'where' => 'civicrm_survey.bypass_confirm',
    'default' => '0',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'thankyou_title' => [
    'name' => 'thankyou_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Thank-you Title'),
    'description' => ts('Title for Thank-you page (header title tag, and display at the top of the page).'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_survey.thankyou_title',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 1,
    'add' => '4.2',
  ],
  'thankyou_text' => [
    'name' => 'thankyou_text',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Thank-you Text'),
    'description' => ts('text and html allowed. displayed above result on success page'),
    'rows' => 8,
    'cols' => 60,
    'where' => 'civicrm_survey.thankyou_text',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 1,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '4.2',
  ],
  'is_share' => [
    'name' => 'is_share',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is shared through social media'),
    'description' => ts('Can people share the petition through social media?'),
    'required' => TRUE,
    'where' => 'civicrm_survey.is_share',
    'default' => '1',
    'table_name' => 'civicrm_survey',
    'entity' => 'Survey',
    'bao' => 'CRM_Campaign_BAO_Survey',
    'localizable' => 0,
    'add' => '4.4',
  ],
  ];
  
