<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('EntityBatch ID'),
    'description' => ts('primary key'),
    'required' => TRUE,
    'where' => 'civicrm_entity_batch.id',
    'table_name' => 'civicrm_entity_batch',
    'entity' => 'EntityBatch',
    'bao' => 'CRM_Batch_BAO_EntityBatch',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.3',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('EntityBatch Table'),
    'description' => ts('physical tablename for entity being joined to file, e.g. civicrm_contact'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_entity_batch.entity_table',
    'table_name' => 'civicrm_entity_batch',
    'entity' => 'EntityBatch',
    'bao' => 'CRM_Batch_BAO_EntityBatch',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'entity_batch_extends',
      'optionEditPath' => 'civicrm/admin/options/entity_batch_extends',
    ],
    'add' => '3.3',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('FK to entity table specified in entity_table column.'),
    'required' => TRUE,
    'where' => 'civicrm_entity_batch.entity_id',
    'table_name' => 'civicrm_entity_batch',
    'entity' => 'EntityBatch',
    'bao' => 'CRM_Batch_BAO_EntityBatch',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'batch_id' => [
    'name' => 'batch_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch ID'),
    'description' => ts('FK to civicrm_batch'),
    'required' => TRUE,
    'where' => 'civicrm_entity_batch.batch_id',
    'table_name' => 'civicrm_entity_batch',
    'entity' => 'EntityBatch',
    'bao' => 'CRM_Batch_BAO_EntityBatch',
    'localizable' => 0,
    'FKClassName' => 'CRM_Batch_DAO_Batch',
    'html' => [
      'label' => ts("Batch"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_batch',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '3.3',
  ],
  ];
  
