<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('User Job ID'),
    'description' => ts('Job ID'),
    'required' => TRUE,
    'where' => 'civicrm_user_job.id',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '5.50',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('User job name'),
    'description' => ts('Unique name for job.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_user_job.name',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'add' => '5.50',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to contact table.'),
    'where' => 'civicrm_user_job.created_id',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '5.50',
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Import Job Created Date'),
    'description' => ts('Date and time this job was created.'),
    'required' => TRUE,
    'where' => 'civicrm_user_job.created_date',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'readonly' => TRUE,
    'add' => '5.50',
  ],
  'start_date' => [
    'name' => 'start_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Import Job Started Date'),
    'description' => ts('Date and time this import job started.'),
    'required' => FALSE,
    'where' => 'civicrm_user_job.start_date',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'readonly' => TRUE,
    'add' => '5.50',
  ],
  'end_date' => [
    'name' => 'end_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Job Ended Date'),
    'description' => ts('Date and time this import job ended.'),
    'required' => FALSE,
    'where' => 'civicrm_user_job.end_date',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '5.50',
  ],
  'expires_date' => [
    'name' => 'expires_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Import Job Expires Date'),
    'description' => ts('Date and time to clean up after this import job (temp table deletion date).'),
    'required' => FALSE,
    'where' => 'civicrm_user_job.expires_date',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '5.50',
  ],
  'status_id' => [
    'name' => 'status_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('User Job Status ID'),
    'required' => TRUE,
    'where' => 'civicrm_user_job.status_id',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'label' => ts("Job Status"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_BAO_UserJob::getStatuses',
    ],
    'add' => '5.50',
  ],
  'job_type' => [
    'name' => 'job_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('User Job Type'),
    'description' => ts('Name of the job type, which will allow finding the correct class'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_user_job.job_type',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'label' => ts("Job Type"),
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_BAO_UserJob::getTypes',
    ],
    'add' => '5.50',
  ],
  'queue_id' => [
    'name' => 'queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Queue ID'),
    'description' => ts('FK to Queue'),
    'where' => 'civicrm_user_job.queue_id',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'FKClassName' => 'CRM_Queue_DAO_Queue',
    'html' => [
      'label' => ts("Queue"),
    ],
    'add' => NULL,
  ],
  'metadata' => [
    'name' => 'metadata',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Job metadata'),
    'description' => ts('Data pertaining to job configuration'),
    'where' => 'civicrm_user_job.metadata',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_JSON,
    'add' => '5.50',
  ],
  'is_template' => [
    'name' => 'is_template',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Template'),
    'description' => ts('Is this a template configuration (for use by other/future jobs)?'),
    'required' => TRUE,
    'where' => 'civicrm_user_job.is_template',
    'default' => '0',
    'table_name' => 'civicrm_user_job',
    'entity' => 'UserJob',
    'bao' => 'CRM_Core_BAO_UserJob',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Is Template"),
    ],
    'add' => '5.51',
  ],
  ];
  
