<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('UF Match ID'),
    'description' => ts('System generated ID.'),
    'required' => TRUE,
    'where' => 'civicrm_uf_match.id',
    'table_name' => 'civicrm_uf_match',
    'entity' => 'UFMatch',
    'bao' => 'CRM_Core_BAO_UFMatch',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this match entry for'),
    'required' => TRUE,
    'where' => 'civicrm_uf_match.domain_id',
    'table_name' => 'civicrm_uf_match',
    'entity' => 'UFMatch',
    'bao' => 'CRM_Core_BAO_UFMatch',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '3.0',
  ],
  'uf_id' => [
    'name' => 'uf_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('CMS ID'),
    'description' => ts('UF ID'),
    'required' => TRUE,
    'where' => 'civicrm_uf_match.uf_id',
    'table_name' => 'civicrm_uf_match',
    'entity' => 'UFMatch',
    'bao' => 'CRM_Core_BAO_UFMatch',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'uf_name' => [
    'name' => 'uf_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('CMS Unique Identifier'),
    'description' => ts('UF Name'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_uf_match.uf_name',
    'table_name' => 'civicrm_uf_match',
    'entity' => 'UFMatch',
    'bao' => 'CRM_Core_BAO_UFMatch',
    'localizable' => 0,
    'add' => '1.9.kabissa',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_uf_match.contact_id',
    'table_name' => 'civicrm_uf_match',
    'entity' => 'UFMatch',
    'bao' => 'CRM_Core_BAO_UFMatch',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '1.1',
  ],
  'language' => [
    'name' => 'language',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Preferred Language'),
    'description' => ts('UI language preferred by the given user/contact'),
    'maxlength' => 5,
    'size' => CRM_Utils_Type::SIX,
    'where' => 'civicrm_uf_match.language',
    'table_name' => 'civicrm_uf_match',
    'entity' => 'UFMatch',
    'bao' => 'CRM_Core_BAO_UFMatch',
    'localizable' => 0,
    'add' => '2.1',
  ],
  ];
  
