<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Campaign Group ID'),
    'description' => ts('Campaign Group id.'),
    'required' => TRUE,
    'where' => 'civicrm_campaign_group.id',
    'table_name' => 'civicrm_campaign_group',
    'entity' => 'CampaignGroup',
    'bao' => 'CRM_Campaign_DAO_CampaignGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.3',
  ],
  'campaign_id' => [
    'name' => 'campaign_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Campaign ID'),
    'description' => ts('Foreign key to the activity Campaign.'),
    'required' => TRUE,
    'where' => 'civicrm_campaign_group.campaign_id',
    'table_name' => 'civicrm_campaign_group',
    'entity' => 'CampaignGroup',
    'bao' => 'CRM_Campaign_DAO_CampaignGroup',
    'localizable' => 0,
    'FKClassName' => 'CRM_Campaign_DAO_Campaign',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Campaign"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_campaign',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'prefetch' => 'FALSE',
    ],
    'add' => '3.3',
  ],
  'group_type' => [
    'name' => 'group_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Campaign Group Type'),
    'description' => ts('Type of Group.'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_campaign_group.group_type',
    'default' => NULL,
    'table_name' => 'civicrm_campaign_group',
    'entity' => 'CampaignGroup',
    'bao' => 'CRM_Campaign_DAO_CampaignGroup',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getCampaignGroupTypes',
    ],
    'add' => NULL,
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('Name of table where item being referenced is stored.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_campaign_group.entity_table',
    'default' => NULL,
    'table_name' => 'civicrm_campaign_group',
    'entity' => 'CampaignGroup',
    'bao' => 'CRM_Campaign_DAO_CampaignGroup',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('Entity id of referenced table.'),
    'where' => 'civicrm_campaign_group.entity_id',
    'default' => NULL,
    'table_name' => 'civicrm_campaign_group',
    'entity' => 'CampaignGroup',
    'bao' => 'CRM_Campaign_DAO_CampaignGroup',
    'localizable' => 0,
    'add' => '3.3',
  ],
  ];
  
