<?php
return [
  'membership_id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Membership ID'),
    'description' => ts('Membership ID'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.id',
    'headerPattern' => '/^(m(embership\s)?id)$/i',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.5',
  ],
  'membership_contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.contact_id',
    'headerPattern' => '/contact(.?id)?/i',
    'dataPattern' => '/^\d+$/',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Contact"),
    ],
    'add' => '1.5',
  ],
  'membership_type_id' => [
    'name' => 'membership_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Membership Type ID'),
    'description' => ts('FK to Membership Type'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.membership_type_id',
    'headerPattern' => '/^(m(embership\s)?type)$/i',
    'export' => FALSE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'FKClassName' => 'CRM_Member_DAO_MembershipType',
    'html' => [
      'type' => 'Select',
      'label' => ts("Membership Type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_membership_type',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '1.5',
  ],
  'membership_join_date' => [
    'name' => 'join_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Member Since'),
    'description' => ts('Beginning of initial membership period (member since...).'),
    'import' => TRUE,
    'where' => 'civicrm_membership.join_date',
    'headerPattern' => '/^join|(j(oin\s)?date)$/i',
    'dataPattern' => '/\d{4}-?\d{2}-?\d{2}/',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDate',
    ],
    'add' => '1.5',
  ],
  'membership_start_date' => [
    'name' => 'start_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Membership Start Date'),
    'description' => ts('Beginning of current uninterrupted membership period.'),
    'import' => TRUE,
    'where' => 'civicrm_membership.start_date',
    'headerPattern' => '/(member(ship)?.)?start(s)?(.date$)?/i',
    'dataPattern' => '/\d{4}-?\d{2}-?\d{2}/',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDate',
    ],
    'add' => '1.5',
  ],
  'membership_end_date' => [
    'name' => 'end_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Membership Expiration Date'),
    'description' => ts('Current membership period expire date.'),
    'import' => TRUE,
    'where' => 'civicrm_membership.end_date',
    'headerPattern' => '/(member(ship)?.)?end(s)?(.date$)?/i',
    'dataPattern' => '/\d{4}-?\d{2}-?\d{2}/',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDate',
    ],
    'add' => '1.5',
  ],
  'membership_source' => [
    'name' => 'source',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Source'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_membership.source',
    'headerPattern' => '/^(member(ship?))?source$/i',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.5',
  ],
  'status_id' => [
    'name' => 'status_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Status ID'),
    'description' => ts('FK to Membership Status'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.status_id',
    'headerPattern' => '/(member(ship|).)?(status)$/i',
    'export' => FALSE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'FKClassName' => 'CRM_Member_DAO_MembershipStatus',
    'html' => [
      'type' => 'Select',
      'label' => ts("Status"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_membership_status',
      'keyColumn' => 'id',
      'labelColumn' => 'label',
    ],
    'add' => '1.5',
  ],
  'member_is_override' => [
    'name' => 'is_override',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Status Override'),
    'description' => ts('Admin users may set a manual status which overrides the calculated status. When this flag is true, automated status update scripts should NOT modify status for the record.'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.is_override',
    'headerPattern' => '/override$/i',
    'export' => TRUE,
    'default' => '0',
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '1.5',
  ],
  'status_override_end_date' => [
    'name' => 'status_override_end_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Status Override End Date'),
    'description' => ts('Then end date of membership status override if \'Override until selected date\' override type is selected.'),
    'import' => TRUE,
    'where' => 'civicrm_membership.status_override_end_date',
    'export' => TRUE,
    'default' => NULL,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDate',
    ],
    'add' => '4.7',
  ],
  'owner_membership_id' => [
    'name' => 'owner_membership_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Primary Member ID'),
    'description' => ts('Optional FK to Parent Membership.'),
    'where' => 'civicrm_membership.owner_membership_id',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'FKClassName' => 'CRM_Member_DAO_Membership',
    'html' => [
      'label' => ts("Primary Member"),
    ],
    'add' => '1.7',
  ],
  'max_related' => [
    'name' => 'max_related',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Max Related'),
    'description' => ts('Maximum number of related memberships (membership_type override).'),
    'where' => 'civicrm_membership.max_related',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
      'label' => ts("Maximum number of related memberships"),
    ],
    'add' => '4.3',
  ],
  'member_is_test' => [
    'name' => 'is_test',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Test'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.is_test',
    'headerPattern' => '/(is.)?test(.member(ship)?)?/i',
    'export' => TRUE,
    'default' => '0',
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => NULL,
  ],
  'member_is_pay_later' => [
    'name' => 'is_pay_later',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Pay Later'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_membership.is_pay_later',
    'headerPattern' => '/(is.)?(pay(.)?later)$/i',
    'export' => TRUE,
    'default' => '0',
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '2.1',
  ],
  'membership_recur_id' => [
    'name' => 'contribution_recur_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Recurring Contribution ID'),
    'description' => ts('Conditional foreign key to civicrm_contribution_recur id. Each membership in connection with a recurring contribution carries a foreign key to the recurring contribution record. This assumes we can track these processor initiated events.'),
    'where' => 'civicrm_membership.contribution_recur_id',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_ContributionRecur',
    'html' => [
      'label' => ts("Recurring Contribution"),
    ],
    'add' => '3.3',
  ],
  'member_campaign_id' => [
    'name' => 'campaign_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Campaign ID'),
    'description' => ts('The campaign for which this membership is attached.'),
    'import' => TRUE,
    'where' => 'civicrm_membership.campaign_id',
    'export' => TRUE,
    'table_name' => 'civicrm_membership',
    'entity' => 'Membership',
    'bao' => 'CRM_Member_BAO_Membership',
    'localizable' => 0,
    'FKClassName' => 'CRM_Campaign_DAO_Campaign',
    'component' => 'CiviCampaign',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Campaign"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_campaign',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'prefetch' => 'FALSE',
    ],
    'add' => '3.4',
  ],
  ];
  
