<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Component ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_component.id',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Component Name'),
    'description' => ts('The name of this component'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_mailing_component.name',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'add' => NULL,
  ],
  'component_type' => [
    'name' => 'component_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Component Type'),
    'description' => ts('Type of Component.'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_mailing_component.component_type',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::mailingComponents',
    ],
    'add' => NULL,
  ],
  'subject' => [
    'name' => 'subject',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Subject'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_component.subject',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'label' => ts("Subject"),
    ],
    'add' => NULL,
  ],
  'body_html' => [
    'name' => 'body_html',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Mailing Component Body HTML'),
    'description' => ts('Body of the component in html format.'),
    'rows' => 8,
    'cols' => 80,
    'where' => 'civicrm_mailing_component.body_html',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => NULL,
  ],
  'body_text' => [
    'name' => 'body_text',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Body Text'),
    'description' => ts('Body of the component in text format.'),
    'rows' => 8,
    'cols' => 80,
    'where' => 'civicrm_mailing_component.body_text',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
      'label' => ts("Body in Text Format"),
    ],
    'add' => NULL,
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Mailing Component is Default?'),
    'description' => ts('Is this the default component for this component_type?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_component.is_default',
    'default' => '0',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => NULL,
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Mailing Component Is Active?'),
    'description' => ts('Is this property active?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_component.is_active',
    'default' => '1',
    'table_name' => 'civicrm_mailing_component',
    'entity' => 'MailingComponent',
    'bao' => 'CRM_Mailing_BAO_MailingComponent',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => NULL,
  ],
  ];
  
