<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity Contact ID'),
    'description' => ts('Activity contact id'),
    'required' => TRUE,
    'where' => 'civicrm_activity_contact.id',
    'table_name' => 'civicrm_activity_contact',
    'entity' => 'ActivityContact',
    'bao' => 'CRM_Activity_BAO_ActivityContact',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.4',
  ],
  'activity_id' => [
    'name' => 'activity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity ID'),
    'description' => ts('Foreign key to the activity for this record.'),
    'required' => TRUE,
    'where' => 'civicrm_activity_contact.activity_id',
    'table_name' => 'civicrm_activity_contact',
    'entity' => 'ActivityContact',
    'bao' => 'CRM_Activity_BAO_ActivityContact',
    'localizable' => 0,
    'FKClassName' => 'CRM_Activity_DAO_Activity',
    'html' => [
      'label' => ts("Activity"),
    ],
    'add' => '4.4',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('Foreign key to the contact for this record.'),
    'required' => TRUE,
    'import' => TRUE,
    'where' => 'civicrm_activity_contact.contact_id',
    'export' => TRUE,
    'table_name' => 'civicrm_activity_contact',
    'entity' => 'ActivityContact',
    'bao' => 'CRM_Activity_BAO_ActivityContact',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '4.4',
  ],
  'record_type_id' => [
    'name' => 'record_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Activity Contact Type'),
    'description' => ts('Determines the contact\'s role in the activity (source, target, or assignee).'),
    'where' => 'civicrm_activity_contact.record_type_id',
    'table_name' => 'civicrm_activity_contact',
    'entity' => 'ActivityContact',
    'bao' => 'CRM_Activity_BAO_ActivityContact',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
      'label' => ts("Contact Role"),
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'activity_contacts',
      'optionEditPath' => 'civicrm/admin/options/activity_contacts',
    ],
    'add' => '4.4',
  ],
  ];
  
