<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch ID'),
    'description' => ts('Unique Address ID'),
    'required' => TRUE,
    'where' => 'civicrm_batch.id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.3',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Batch Name'),
    'description' => ts('Variable name/programmatic handle for this batch.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_batch.name',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.3',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Batch Title'),
    'description' => ts('Friendly Name.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_batch.title',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Batch Description'),
    'description' => ts('Description of this batch set.'),
    'rows' => 4,
    'cols' => 80,
    'where' => 'civicrm_batch.description',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 1,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '3.3',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_batch.created_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '3.3',
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Batch Created Date'),
    'description' => ts('When was this item created'),
    'where' => 'civicrm_batch.created_date',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => '3.3',
  ],
  'modified_id' => [
    'name' => 'modified_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Modified By Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_batch.modified_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Modified By"),
    ],
    'add' => '3.3',
  ],
  'modified_date' => [
    'name' => 'modified_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Batch Modified Date'),
    'description' => ts('When was this item modified'),
    'where' => 'civicrm_batch.modified_date',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '3.3',
  ],
  'saved_search_id' => [
    'name' => 'saved_search_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Smart Group ID'),
    'description' => ts('FK to Saved Search ID'),
    'where' => 'civicrm_batch.saved_search_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_SavedSearch',
    'html' => [
      'type' => 'EntityRef',
      'label' => ts("Smart Group"),
    ],
    'add' => '4.1',
  ],
  'status_id' => [
    'name' => 'status_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch Status'),
    'description' => ts('fk to Batch Status options in civicrm_option_values'),
    'required' => TRUE,
    'where' => 'civicrm_batch.status_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'batch_status',
      'optionEditPath' => 'civicrm/admin/options/batch_status',
    ],
    'add' => '4.2',
  ],
  'type_id' => [
    'name' => 'type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch Type'),
    'description' => ts('fk to Batch Type options in civicrm_option_values'),
    'where' => 'civicrm_batch.type_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'batch_type',
      'optionEditPath' => 'civicrm/admin/options/batch_type',
    ],
    'add' => '4.2',
  ],
  'mode_id' => [
    'name' => 'mode_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch Mode'),
    'description' => ts('fk to Batch mode options in civicrm_option_values'),
    'where' => 'civicrm_batch.mode_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'batch_mode',
      'optionEditPath' => 'civicrm/admin/options/batch_mode',
    ],
    'add' => '4.2',
  ],
  'total' => [
    'name' => 'total',
    'type' => CRM_Utils_Type::T_MONEY,
    'title' => ts('Batch Total'),
    'description' => ts('Total amount for this batch.'),
    'precision' => [
      20,
      2,
    ],
    'where' => 'civicrm_batch.total',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'item_count' => [
    'name' => 'item_count',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch Number of Items'),
    'description' => ts('Number of items in a batch.'),
    'where' => 'civicrm_batch.item_count',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'payment_instrument_id' => [
    'name' => 'payment_instrument_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Batch Payment Method'),
    'description' => ts('fk to Payment Instrument options in civicrm_option_values'),
    'where' => 'civicrm_batch.payment_instrument_id',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'payment_instrument',
      'optionEditPath' => 'civicrm/admin/options/payment_instrument',
    ],
    'add' => '4.3',
  ],
  'exported_date' => [
    'name' => 'exported_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Batch Exported Date'),
    'where' => 'civicrm_batch.exported_date',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'data' => [
    'name' => 'data',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Batch Data'),
    'description' => ts('cache entered data'),
    'where' => 'civicrm_batch.data',
    'table_name' => 'civicrm_batch',
    'entity' => 'Batch',
    'bao' => 'CRM_Batch_BAO_Batch',
    'localizable' => 0,
    'add' => '4.4',
  ],
  ];
  
