<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Message Template ID'),
    'description' => ts('Message Template ID'),
    'required' => TRUE,
    'where' => 'civicrm_msg_template.id',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.6',
  ],
  'msg_title' => [
    'name' => 'msg_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Message Template Title'),
    'description' => ts('Descriptive title of message'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_msg_template.msg_title',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.6',
  ],
  'msg_subject' => [
    'name' => 'msg_subject',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Message Template Subject'),
    'description' => ts('Subject for email message.'),
    'where' => 'civicrm_msg_template.msg_subject',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.6',
  ],
  'msg_text' => [
    'name' => 'msg_text',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Message Template Text'),
    'description' => ts('Text formatted message'),
    'where' => 'civicrm_msg_template.msg_text',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '1.6',
  ],
  'msg_html' => [
    'name' => 'msg_html',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Message Template HTML'),
    'description' => ts('HTML formatted message'),
    'where' => 'civicrm_msg_template.msg_html',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'RichTextEditor',
    ],
    'add' => '1.6',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Active'),
    'required' => TRUE,
    'where' => 'civicrm_msg_template.is_active',
    'default' => '1',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.6',
  ],
  'workflow_id' => [
    'name' => 'workflow_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Deprecated field for Message Template Workflow.'),
    'description' => ts('a pseudo-FK to civicrm_option_value'),
    'where' => 'civicrm_msg_template.workflow_id',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'add' => '3.1',
  ],
  'workflow_name' => [
    'name' => 'workflow_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Message Template Workflow Name'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_msg_template.workflow_name',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'add' => '5.26',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Message Template Is Default?'),
    'description' => ts('is this the default message template for the workflow referenced by workflow_id?'),
    'required' => TRUE,
    'where' => 'civicrm_msg_template.is_default',
    'default' => '1',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '3.1',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Message Template Is Reserved?'),
    'description' => ts('is this the reserved message template which we ship for the workflow referenced by workflow_id?'),
    'required' => TRUE,
    'where' => 'civicrm_msg_template.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'add' => '3.1',
  ],
  'is_sms' => [
    'name' => 'is_sms',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Message Template is used for SMS?'),
    'description' => ts('Is this message template used for sms?'),
    'required' => TRUE,
    'where' => 'civicrm_msg_template.is_sms',
    'default' => '0',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'add' => '4.5',
  ],
  'pdf_format_id' => [
    'name' => 'pdf_format_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Message Template Format'),
    'description' => ts('a pseudo-FK to civicrm_option_value containing PDF Page Format.'),
    'where' => 'civicrm_msg_template.pdf_format_id',
    'table_name' => 'civicrm_msg_template',
    'entity' => 'MessageTemplate',
    'bao' => 'CRM_Core_BAO_MessageTemplate',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'pdf_format',
      'keyColumn' => 'id',
      'optionEditPath' => 'civicrm/admin/options/pdf_format',
    ],
    'add' => '3.4',
  ],
  ];
  
