<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('SMS Provider ID'),
    'description' => ts('SMS Provider ID'),
    'required' => TRUE,
    'where' => 'civicrm_sms_provider.id',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.2',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('SMS Provider Name'),
    'description' => ts('Provider internal name points to option_value of option_group sms_provider_name'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_sms_provider.name',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('SMS Provider Title'),
    'description' => ts('Provider name visible to user'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_sms_provider.title',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'username' => [
    'name' => 'username',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('SMS Provider Username'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_sms_provider.username',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'password' => [
    'name' => 'password',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('SMS Provider Password'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_sms_provider.password',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'api_type' => [
    'name' => 'api_type',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('SMS Provider API'),
    'description' => ts('points to value in civicrm_option_value for group sms_api_type'),
    'required' => TRUE,
    'where' => 'civicrm_sms_provider.api_type',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'sms_api_type',
      'optionEditPath' => 'civicrm/admin/options/sms_api_type',
    ],
    'add' => '4.2',
  ],
  'api_url' => [
    'name' => 'api_url',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('SMS Provider API URL'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_sms_provider.api_url',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'api_params' => [
    'name' => 'api_params',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('SMS Provider API Params'),
    'description' => ts('the api params in xml, http or smtp format'),
    'where' => 'civicrm_sms_provider.api_params',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.2',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('SMS Provider is Default?'),
    'required' => TRUE,
    'where' => 'civicrm_sms_provider.is_default',
    'default' => '0',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '4.2',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('SMS Provider is Active?'),
    'required' => TRUE,
    'where' => 'civicrm_sms_provider.is_active',
    'default' => '1',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.2',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this sms provider for'),
    'where' => 'civicrm_sms_provider.domain_id',
    'table_name' => 'civicrm_sms_provider',
    'entity' => 'Provider',
    'bao' => 'CRM_SMS_BAO_Provider',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '4.7',
  ],
  ];
  
