<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Unsubscribe ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_unsubscribe.id',
    'table_name' => 'civicrm_mailing_event_unsubscribe',
    'entity' => 'MailingEventUnsubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventUnsubscribe',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'event_queue_id' => [
    'name' => 'event_queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Event Queue ID'),
    'description' => ts('FK to EventQueue'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_unsubscribe.event_queue_id',
    'table_name' => 'civicrm_mailing_event_unsubscribe',
    'entity' => 'MailingEventUnsubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventUnsubscribe',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventQueue',
    'html' => [
      'label' => ts("Recipient"),
    ],
    'add' => NULL,
  ],
  'org_unsubscribe' => [
    'name' => 'org_unsubscribe',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Unsubscribe is for Organization?'),
    'description' => ts('Unsubscribe at org- or group-level'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_unsubscribe.org_unsubscribe',
    'table_name' => 'civicrm_mailing_event_unsubscribe',
    'entity' => 'MailingEventUnsubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventUnsubscribe',
    'localizable' => 0,
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Unsubscribe Timestamp'),
    'description' => ts('When this delivery event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_unsubscribe.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_unsubscribe',
    'entity' => 'MailingEventUnsubscribe',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventUnsubscribe',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
