<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('State ID'),
    'description' => ts('State/Province ID'),
    'required' => TRUE,
    'where' => 'civicrm_state_province.id',
    'table_name' => 'civicrm_state_province',
    'entity' => 'StateProvince',
    'bao' => 'CRM_Core_DAO_StateProvince',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('State'),
    'description' => ts('Name of State/Province'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_state_province.name',
    'headerPattern' => '/state|prov(ince)?/i',
    'dataPattern' => '/[A-Z]{2}/',
    'export' => TRUE,
    'table_name' => 'civicrm_state_province',
    'entity' => 'StateProvince',
    'bao' => 'CRM_Core_DAO_StateProvince',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'abbreviation' => [
    'name' => 'abbreviation',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('State Abbreviation'),
    'description' => ts('2-4 Character Abbreviation of State/Province'),
    'maxlength' => 4,
    'size' => CRM_Utils_Type::FOUR,
    'where' => 'civicrm_state_province.abbreviation',
    'table_name' => 'civicrm_state_province',
    'entity' => 'StateProvince',
    'bao' => 'CRM_Core_DAO_StateProvince',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'country_id' => [
    'name' => 'country_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Country ID'),
    'description' => ts('ID of Country that State/Province belong'),
    'required' => TRUE,
    'where' => 'civicrm_state_province.country_id',
    'table_name' => 'civicrm_state_province',
    'entity' => 'StateProvince',
    'bao' => 'CRM_Core_DAO_StateProvince',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Country',
    'html' => [
      'label' => ts("Country"),
    ],
    'add' => '1.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('StateProvince Is Active'),
    'description' => ts('Is this StateProvince active?'),
    'required' => TRUE,
    'where' => 'civicrm_state_province.is_active',
    'default' => '1',
    'table_name' => 'civicrm_state_province',
    'entity' => 'StateProvince',
    'bao' => 'CRM_Core_DAO_StateProvince',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '5.35',
  ],
  ];
  
