<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Job ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_job.id',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'mailing_id' => [
    'name' => 'mailing_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing ID'),
    'description' => ts('The ID of the mailing this Job will send.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_job.mailing_id',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_Mailing',
    'html' => [
      'label' => ts("Mailing"),
    ],
    'add' => NULL,
  ],
  'scheduled_date' => [
    'name' => 'scheduled_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Scheduled Date'),
    'description' => ts('date on which this job was scheduled.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing_job.scheduled_date',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => NULL,
  ],
  'mailing_job_start_date' => [
    'name' => 'start_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Job Start Date'),
    'description' => ts('date on which this job was started.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing_job.start_date',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'unique_title' => ts('Mailing Start Date'),
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => NULL,
  ],
  'end_date' => [
    'name' => 'end_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Mailing Job End Date'),
    'description' => ts('date on which this job ended.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing_job.end_date',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
    ],
    'add' => NULL,
  ],
  'mailing_job_status' => [
    'name' => 'status',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Job Status'),
    'description' => ts('The state of this job'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_mailing_job.status',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getMailingJobStatus',
    ],
    'add' => NULL,
  ],
  'is_test' => [
    'name' => 'is_test',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Mailing Job Is Test?'),
    'description' => ts('Is this job for a test mail?'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_job.is_test',
    'default' => '0',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'add' => '1.9',
  ],
  'job_type' => [
    'name' => 'job_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Mailing Job Type'),
    'description' => ts('Type of mailling job: null | child '),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_job.job_type',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'parent_id' => [
    'name' => 'parent_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Parent ID'),
    'description' => ts('Parent job id'),
    'where' => 'civicrm_mailing_job.parent_id',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingJob',
    'html' => [
      'label' => ts("Parent"),
    ],
    'add' => '3.3',
  ],
  'job_offset' => [
    'name' => 'job_offset',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Job Offset'),
    'description' => ts('Offset of the child job'),
    'where' => 'civicrm_mailing_job.job_offset',
    'default' => '0',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'add' => '3.3',
  ],
  'job_limit' => [
    'name' => 'job_limit',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Job Limit'),
    'description' => ts('Queue size limit for each child job'),
    'where' => 'civicrm_mailing_job.job_limit',
    'default' => '0',
    'table_name' => 'civicrm_mailing_job',
    'entity' => 'MailingJob',
    'bao' => 'CRM_Mailing_BAO_MailingJob',
    'localizable' => 0,
    'add' => '3.3',
  ],
  ];
  
