<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Event Queue ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_queue.id',
    'table_name' => 'civicrm_mailing_event_queue',
    'entity' => 'MailingEventQueue',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventQueue',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'job_id' => [
    'name' => 'job_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Job ID'),
    'description' => ts('Mailing Job'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_queue.job_id',
    'table_name' => 'civicrm_mailing_event_queue',
    'entity' => 'MailingEventQueue',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventQueue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingJob',
    'html' => [
      'label' => ts("Outbound Mailing"),
    ],
    'add' => NULL,
  ],
  'email_id' => [
    'name' => 'email_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Email ID'),
    'description' => ts('FK to Email'),
    'where' => 'civicrm_mailing_event_queue.email_id',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_event_queue',
    'entity' => 'MailingEventQueue',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventQueue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Email',
    'html' => [
      'label' => ts("Email"),
    ],
    'add' => NULL,
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_queue.contact_id',
    'table_name' => 'civicrm_mailing_event_queue',
    'entity' => 'MailingEventQueue',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventQueue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => NULL,
  ],
  'hash' => [
    'name' => 'hash',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Security Hash'),
    'description' => ts('Security hash'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mailing_event_queue.hash',
    'table_name' => 'civicrm_mailing_event_queue',
    'entity' => 'MailingEventQueue',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventQueue',
    'localizable' => 0,
    'add' => NULL,
  ],
  'phone_id' => [
    'name' => 'phone_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Phone ID'),
    'description' => ts('FK to Phone'),
    'where' => 'civicrm_mailing_event_queue.phone_id',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_event_queue',
    'entity' => 'MailingEventQueue',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventQueue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Phone',
    'html' => [
      'label' => ts("Phone"),
    ],
    'add' => NULL,
  ],
  ];
  
