<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Extension ID'),
    'description' => ts('Local Extension ID'),
    'required' => TRUE,
    'where' => 'civicrm_extension.id',
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.2',
  ],
  'type' => [
    'name' => 'type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Type'),
    'required' => TRUE,
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_extension.type',
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getExtensionTypes',
    ],
    'add' => '4.2',
  ],
  'full_name' => [
    'name' => 'full_name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Key'),
    'description' => ts('Fully qualified extension name'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_extension.full_name',
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Name'),
    'description' => ts('Short name'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_extension.name',
    'export' => TRUE,
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Label'),
    'description' => ts('Short, printable name'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_extension.label',
    'export' => TRUE,
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'file' => [
    'name' => 'file',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('File'),
    'description' => ts('Primary PHP file'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_extension.file',
    'export' => TRUE,
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'schema_version' => [
    'name' => 'schema_version',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Schema Version'),
    'description' => ts('Revision code of the database schema; the format is module-defined'),
    'maxlength' => 63,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_extension.schema_version',
    'export' => TRUE,
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'add' => '4.2',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Extension is Active?'),
    'description' => ts('Is this extension active?'),
    'where' => 'civicrm_extension.is_active',
    'default' => '1',
    'table_name' => 'civicrm_extension',
    'entity' => 'Extension',
    'bao' => 'CRM_Core_BAO_Extension',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.2',
  ],
  ];
  
