<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('ID'),
    'required' => TRUE,
    'where' => 'civicrm_recurring_entity.id',
    'table_name' => 'civicrm_recurring_entity',
    'entity' => 'RecurringEntity',
    'bao' => 'CRM_Core_BAO_RecurringEntity',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.6',
  ],
  'parent_id' => [
    'name' => 'parent_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Parent ID'),
    'description' => ts('Recurring Entity Parent ID'),
    'required' => TRUE,
    'where' => 'civicrm_recurring_entity.parent_id',
    'table_name' => 'civicrm_recurring_entity',
    'entity' => 'RecurringEntity',
    'bao' => 'CRM_Core_BAO_RecurringEntity',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('Recurring Entity Child ID'),
    'where' => 'civicrm_recurring_entity.entity_id',
    'table_name' => 'civicrm_recurring_entity',
    'entity' => 'RecurringEntity',
    'bao' => 'CRM_Core_BAO_RecurringEntity',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('Physical tablename for entity, e.g. civicrm_event'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_recurring_entity.entity_table',
    'table_name' => 'civicrm_recurring_entity',
    'entity' => 'RecurringEntity',
    'bao' => 'CRM_Core_BAO_RecurringEntity',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'mode' => [
    'name' => 'mode',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Cascade Type'),
    'description' => ts('1-this entity, 2-this and the following entities, 3-all the entities'),
    'required' => TRUE,
    'where' => 'civicrm_recurring_entity.mode',
    'default' => '1',
    'table_name' => 'civicrm_recurring_entity',
    'entity' => 'RecurringEntity',
    'bao' => 'CRM_Core_BAO_RecurringEntity',
    'localizable' => 0,
    'add' => '4.6',
  ],
  ];
  
