<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Option Value ID'),
    'description' => ts('Option ID'),
    'required' => TRUE,
    'where' => 'civicrm_option_value.id',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'readonly' => TRUE,
    'add' => '1.5',
  ],
  'option_group_id' => [
    'name' => 'option_group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Option Group ID'),
    'description' => ts('Group which this option belongs to.'),
    'required' => TRUE,
    'where' => 'civicrm_option_value.option_group_id',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_OptionGroup',
    'html' => [
      'type' => 'Select',
      'label' => ts("Option Group"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_option_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
      'nameColumn' => 'name',
    ],
    'add' => '1.5',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Option Label'),
    'description' => ts('Option string as displayed to users - e.g. the label in an HTML OPTION tag.'),
    'required' => TRUE,
    'maxlength' => 512,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_option_value.label',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 1,
    'add' => '1.5',
  ],
  'value' => [
    'name' => 'value',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Option Value'),
    'description' => ts('The actual value stored (as a foreign key) in the data record. Functions which need lookup option_value.title should use civicrm_option_value.option_group_id plus civicrm_option_value.value as the key.'),
    'required' => TRUE,
    'maxlength' => 512,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_option_value.value',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Option Name'),
    'description' => ts('Stores a fixed (non-translated) name for this option value. Lookup functions should use the name as the key for the option value row.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_option_value.name',
    'export' => TRUE,
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'grouping' => [
    'name' => 'grouping',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Option Grouping Name'),
    'description' => ts('Use to sort and/or set display properties for sub-set(s) of options within an option group. EXAMPLE: Use for college_interest field, to differentiate partners from non-partners.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_option_value.grouping',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'filter' => [
    'name' => 'filter',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Filter'),
    'description' => ts('Bitwise logic can be used to create subsets of options within an option_group for different uses.'),
    'where' => 'civicrm_option_value.filter',
    'default' => '0',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'html' => [
      'label' => ts("Filter"),
    ],
    'add' => '1.5',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Option is Default?'),
    'description' => ts('Is this the default option for the group?'),
    'where' => 'civicrm_option_value.is_default',
    'default' => '0',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '1.5',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('Controls display sort order.'),
    'required' => TRUE,
    'where' => 'civicrm_option_value.weight',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Option Description'),
    'description' => ts('Optional description.'),
    'rows' => 8,
    'cols' => 60,
    'where' => 'civicrm_option_value.description',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 1,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '1.5',
  ],
  'is_optgroup' => [
    'name' => 'is_optgroup',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Option is Header?'),
    'description' => ts('Is this row simply a display header? Expected usage is to render these as OPTGROUP tags within a SELECT field list of options?'),
    'where' => 'civicrm_option_value.is_optgroup',
    'default' => '0',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Option Is Reserved?'),
    'description' => ts('Is this a predefined system object?'),
    'where' => 'civicrm_option_value.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Option Is Active'),
    'description' => ts('Is this option active?'),
    'where' => 'civicrm_option_value.is_active',
    'default' => '1',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.5',
  ],
  'component_id' => [
    'name' => 'component_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Component ID'),
    'description' => ts('Component that this option value belongs/caters to.'),
    'where' => 'civicrm_option_value.component_id',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Component',
    'html' => [
      'type' => 'Select',
      'label' => ts("Component"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_component',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '2.0',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this option value for'),
    'where' => 'civicrm_option_value.domain_id',
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '3.1',
  ],
  'visibility_id' => [
    'name' => 'visibility_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Option Visibility'),
    'where' => 'civicrm_option_value.visibility_id',
    'default' => NULL,
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'visibility',
      'optionEditPath' => 'civicrm/admin/options/visibility',
    ],
    'add' => '2.2',
  ],
  'icon' => [
    'name' => 'icon',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Icon'),
    'description' => ts('crm-i icon class'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_option_value.icon',
    'default' => NULL,
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '4.7',
  ],
  'color' => [
    'name' => 'color',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Color'),
    'description' => ts('Hex color value e.g. #ffffff'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_option_value.color',
    'default' => NULL,
    'table_name' => 'civicrm_option_value',
    'entity' => 'OptionValue',
    'bao' => 'CRM_Core_BAO_OptionValue',
    'localizable' => 0,
    'add' => '4.7',
  ],
  ];
  
