<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group Membership History ID'),
    'description' => ts('Internal ID'),
    'required' => TRUE,
    'where' => 'civicrm_subscription_history.id',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('Contact ID'),
    'required' => TRUE,
    'where' => 'civicrm_subscription_history.contact_id',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '1.1',
  ],
  'group_id' => [
    'name' => 'group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group ID'),
    'description' => ts('Group ID'),
    'where' => 'civicrm_subscription_history.group_id',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Group',
    'html' => [
      'type' => 'Select',
      'label' => ts("Group"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '1.1',
  ],
  'date' => [
    'name' => 'date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Group Membership Action Date'),
    'description' => ts('Date of the (un)subscription'),
    'required' => TRUE,
    'where' => 'civicrm_subscription_history.date',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDateTime',
      'label' => ts("Group Membership Action Date"),
    ],
    'add' => '1.1',
  ],
  'method' => [
    'name' => 'method',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Membership Action'),
    'description' => ts('How the (un)subscription was triggered'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_subscription_history.method',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getSubscriptionHistoryMethods',
    ],
    'add' => '1.1',
  ],
  'status' => [
    'name' => 'status',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Membership Status'),
    'description' => ts('The state of the contact within the group'),
    'maxlength' => 8,
    'size' => CRM_Utils_Type::EIGHT,
    'where' => 'civicrm_subscription_history.status',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::groupContactStatus',
    ],
    'add' => '1.1',
  ],
  'tracking' => [
    'name' => 'tracking',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Group Membership Tracking'),
    'description' => ts('IP address or other tracking info'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_subscription_history.tracking',
    'table_name' => 'civicrm_subscription_history',
    'entity' => 'SubscriptionHistory',
    'bao' => 'CRM_Contact_BAO_SubscriptionHistory',
    'localizable' => 0,
    'add' => '1.1',
  ],
  ];
  
