<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Connection ID'),
    'description' => ts('Connection ID'),
    'required' => TRUE,
    'where' => 'civicrm_cxn.id',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.6',
  ],
  'app_guid' => [
    'name' => 'app_guid',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Application GUID'),
    'description' => ts('Application GUID'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_cxn.app_guid',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'app_meta' => [
    'name' => 'app_meta',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Application Metadata (JSON)'),
    'description' => ts('Application Metadata (JSON)'),
    'where' => 'civicrm_cxn.app_meta',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'cxn_guid' => [
    'name' => 'cxn_guid',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Connection GUID'),
    'description' => ts('Connection GUID'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_cxn.cxn_guid',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'add' => '4.6',
  ],
  'secret' => [
    'name' => 'secret',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Secret'),
    'description' => ts('Shared secret'),
    'where' => 'civicrm_cxn.secret',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'label' => ts("Secret"),
    ],
    'add' => '4.6',
  ],
  'perm' => [
    'name' => 'perm',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Perm'),
    'description' => ts('Permissions approved for the service (JSON)'),
    'where' => 'civicrm_cxn.perm',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'label' => ts("Permissions"),
    ],
    'add' => '4.6',
  ],
  'options' => [
    'name' => 'options',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Options'),
    'description' => ts('Options for the service (JSON)'),
    'where' => 'civicrm_cxn.options',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_JSON,
    'html' => [
      'label' => ts("Options"),
    ],
    'add' => '4.6',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Active'),
    'description' => ts('Is connection currently enabled?'),
    'required' => TRUE,
    'where' => 'civicrm_cxn.is_active',
    'default' => '1',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.6',
  ],
  'created_date' => [
    'name' => 'created_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Created Date'),
    'description' => ts('When was the connection was created.'),
    'required' => FALSE,
    'where' => 'civicrm_cxn.created_date',
    'default' => NULL,
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'label' => ts("Created Date"),
    ],
    'add' => '4.6',
  ],
  'modified_date' => [
    'name' => 'modified_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Modified Date'),
    'description' => ts('When the connection was created or modified.'),
    'required' => FALSE,
    'where' => 'civicrm_cxn.modified_date',
    'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'label' => ts("Modified Date"),
    ],
    'readonly' => TRUE,
    'add' => '4.6',
  ],
  'fetched_date' => [
    'name' => 'fetched_date',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Fetched Date'),
    'description' => ts('The last time the application metadata was fetched.'),
    'required' => FALSE,
    'where' => 'civicrm_cxn.fetched_date',
    'default' => NULL,
    'table_name' => 'civicrm_cxn',
    'entity' => 'Cxn',
    'bao' => 'CRM_Cxn_BAO_Cxn',
    'localizable' => 0,
    'html' => [
      'label' => ts("Fetched Date"),
    ],
    'add' => '4.6',
  ],
  ];
  
