<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from xml/schema/CRM/Core/EntityTag.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:34d286015dc73849f21721ca37eb2266)
 */

/**
 * Database access object for the EntityTag entity.
 */
class CRM_Core_DAO_EntityTag_Fields {

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Entity Tag ID'),
          'description' => ts('primary key'),
          'required' => TRUE,
          'where' => 'civicrm_entity_tag.id',
          'table_name' => 'civicrm_entity_tag',
          'entity' => 'EntityTag',
          'bao' => 'CRM_Core_BAO_EntityTag',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '1.1',
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Entity Table'),
          'description' => ts('physical tablename for entity being joined to file, e.g. civicrm_contact'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_entity_tag.entity_table',
          'table_name' => 'civicrm_entity_tag',
          'entity' => 'EntityTag',
          'bao' => 'CRM_Core_BAO_EntityTag',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'tag_used_for',
            'optionEditPath' => 'civicrm/admin/options/tag_used_for',
          ],
          'add' => '3.2',
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Entity ID'),
          'description' => ts('FK to entity table specified in entity_table column.'),
          'required' => TRUE,
          'where' => 'civicrm_entity_tag.entity_id',
          'table_name' => 'civicrm_entity_tag',
          'entity' => 'EntityTag',
          'bao' => 'CRM_Core_BAO_EntityTag',
          'localizable' => 0,
          'add' => '3.2',
        ],
        'tag_id' => [
          'name' => 'tag_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Tag ID'),
          'description' => ts('FK to civicrm_tag'),
          'required' => TRUE,
          'where' => 'civicrm_entity_tag.tag_id',
          'table_name' => 'civicrm_entity_tag',
          'entity' => 'EntityTag',
          'bao' => 'CRM_Core_BAO_EntityTag',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_Tag',
          'html' => [
            'type' => 'Select',
            'label' => ts("Tag"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_tag',
            'keyColumn' => 'id',
            'labelColumn' => 'name',
            'condition' => 'is_tagset != 1',
          ],
          'add' => '1.1',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

}
