<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Recipients ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_recipients.id',
    'table_name' => 'civicrm_mailing_recipients',
    'entity' => 'MailingRecipients',
    'bao' => 'CRM_Mailing_BAO_MailingRecipients',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'mailing_id' => [
    'name' => 'mailing_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing ID'),
    'description' => ts('The ID of the mailing this Job will send.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_recipients.mailing_id',
    'table_name' => 'civicrm_mailing_recipients',
    'entity' => 'MailingRecipients',
    'bao' => 'CRM_Mailing_BAO_MailingRecipients',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_Mailing',
    'html' => [
      'label' => ts("Mailing"),
    ],
    'add' => NULL,
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Recipient ID'),
    'description' => ts('FK to Contact'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_recipients.contact_id',
    'table_name' => 'civicrm_mailing_recipients',
    'entity' => 'MailingRecipients',
    'bao' => 'CRM_Mailing_BAO_MailingRecipients',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Recipient"),
    ],
    'add' => NULL,
  ],
  'email_id' => [
    'name' => 'email_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Email ID'),
    'description' => ts('FK to Email'),
    'where' => 'civicrm_mailing_recipients.email_id',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_recipients',
    'entity' => 'MailingRecipients',
    'bao' => 'CRM_Mailing_BAO_MailingRecipients',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Email',
    'html' => [
      'label' => ts("Email"),
    ],
    'add' => NULL,
  ],
  'phone_id' => [
    'name' => 'phone_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Phone ID'),
    'description' => ts('FK to Phone'),
    'where' => 'civicrm_mailing_recipients.phone_id',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_recipients',
    'entity' => 'MailingRecipients',
    'bao' => 'CRM_Mailing_BAO_MailingRecipients',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Phone',
    'html' => [
      'label' => ts("Phone"),
    ],
    'add' => NULL,
  ],
  ];
  
