<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mapping Field ID'),
    'description' => ts('Mapping Field ID'),
    'required' => TRUE,
    'where' => 'civicrm_mapping_field.id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.2',
  ],
  'mapping_id' => [
    'name' => 'mapping_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mapping ID'),
    'description' => ts('Mapping to which this field belongs'),
    'required' => TRUE,
    'where' => 'civicrm_mapping_field.mapping_id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Mapping',
    'html' => [
      'label' => ts("Mapping"),
    ],
    'add' => '1.2',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Field Name (or unique reference)'),
    'description' => ts('Mapping field key'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mapping_field.name',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'add' => '1.2',
  ],
  'contact_type' => [
    'name' => 'contact_type',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Type'),
    'description' => ts('Contact Type in mapping'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_mapping_field.contact_type',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'add' => '1.2',
  ],
  'column_number' => [
    'name' => 'column_number',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Column Number to map to'),
    'description' => ts('Column number for mapping set'),
    'required' => TRUE,
    'where' => 'civicrm_mapping_field.column_number',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'add' => '1.2',
  ],
  'location_type_id' => [
    'name' => 'location_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Location type ID'),
    'description' => ts('Location type of this mapping, if required'),
    'where' => 'civicrm_mapping_field.location_type_id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_LocationType',
    'html' => [
      'label' => ts("Location type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_location_type',
      'keyColumn' => 'id',
      'labelColumn' => 'display_name',
    ],
    'add' => '1.2',
  ],
  'phone_type_id' => [
    'name' => 'phone_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Phone type ID'),
    'description' => ts('Which type of phone does this number belongs.'),
    'where' => 'civicrm_mapping_field.phone_type_id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'add' => '2.2',
  ],
  'im_provider_id' => [
    'name' => 'im_provider_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('IM provider ID'),
    'description' => ts('Which type of IM Provider does this name belong.'),
    'where' => 'civicrm_mapping_field.im_provider_id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'instant_messenger_service',
      'optionEditPath' => 'civicrm/admin/options/instant_messenger_service',
    ],
    'add' => '3.0',
  ],
  'website_type_id' => [
    'name' => 'website_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Website type ID'),
    'description' => ts('Which type of website does this site belong'),
    'where' => 'civicrm_mapping_field.website_type_id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'website_type',
      'optionEditPath' => 'civicrm/admin/options/website_type',
    ],
    'add' => '3.2',
  ],
  'relationship_type_id' => [
    'name' => 'relationship_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Relationship type ID'),
    'description' => ts('Relationship type, if required'),
    'where' => 'civicrm_mapping_field.relationship_type_id',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_RelationshipType',
    'html' => [
      'label' => ts("Relationship type"),
    ],
    'add' => '1.2',
  ],
  'relationship_direction' => [
    'name' => 'relationship_direction',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Relationship Direction'),
    'maxlength' => 6,
    'size' => CRM_Utils_Type::SIX,
    'where' => 'civicrm_mapping_field.relationship_direction',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'add' => '1.7',
  ],
  'grouping' => [
    'name' => 'grouping',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Field Grouping'),
    'description' => ts('Used to group mapping_field records into related sets (e.g. for criteria sets in search builder
      mappings).'),
    'where' => 'civicrm_mapping_field.grouping',
    'default' => '1',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'add' => '1.5',
  ],
  'operator' => [
    'name' => 'operator',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Operator'),
    'description' => ts('SQL WHERE operator for search-builder mapping fields (search criteria).'),
    'maxlength' => 16,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_mapping_field.operator',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::getSearchBuilderOperators',
    ],
    'add' => '1.5',
  ],
  'value' => [
    'name' => 'value',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Search builder where clause'),
    'description' => ts('SQL WHERE value for search-builder mapping fields.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_mapping_field.value',
    'table_name' => 'civicrm_mapping_field',
    'entity' => 'MappingField',
    'bao' => 'CRM_Core_DAO_MappingField',
    'localizable' => 0,
    'add' => '1.5',
  ],
  ];
  
