<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from xml/schema/CRM/Core/Worldregion.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:2604f3d61e573a996ee6f5d7bf4d04dc)
 */

/**
 * Database access object for the WorldRegion entity.
 */
class CRM_Core_DAO_Worldregion_Fields {

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('World Region ID'),
          'description' => ts('Country ID'),
          'required' => TRUE,
          'where' => 'civicrm_worldregion.id',
          'table_name' => 'civicrm_worldregion',
          'entity' => 'WorldRegion',
          'bao' => 'CRM_Core_DAO_Worldregion',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '1.8',
        ],
        'world_region' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('World Region'),
          'description' => ts('Region name to be associated with countries'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_worldregion.name',
          'export' => TRUE,
          'table_name' => 'civicrm_worldregion',
          'entity' => 'WorldRegion',
          'bao' => 'CRM_Core_DAO_Worldregion',
          'localizable' => 0,
          'add' => '1.8',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

}
