<?php

// Generate the "upgrade-base@1.x" mixin by concatentating files from `CRM/Upgrade/*`.
//
// Usage: php build.php MAJOR.MINOR
// Example: php build.php 1.2

if (!(php_sapi_name() == 'cli' || (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0))) {
  header("HTTP/1.0 404 Not Found");
  return;
}

ini_set('display_errors', 1);
main($argv);

function main($argv) {
  $mixinNamespace = 'Civi\Mixin\UpgraderBaseV1';
  $majorMinor = $argv[1] ?? NULL;

  if (empty($majorMinor)) {
    throw new \RuntimeException('Missing argument MAJOR.MINOR');
  }

  $headers = [
    'mixinName' => 'upgrader-base',
    'mixinVersion' => 'AUTO-REPLACE',
    'since' => '5.52',
  ];
  $classMap = [
    'Base' => 'CRM_Extension_Upgrader_Base',
    'IdentityTrait' => 'CRM_Extension_Upgrader_IdentityTrait',
    'UpgraderInterface' => 'CRM_Extension_Upgrader_Interface',
    'QueueTrait' => 'CRM_Extension_Upgrader_QueueTrait',
    'RevisionsTrait' => 'CRM_Extension_Upgrader_RevisionsTrait',
    'SchemaTrait' => 'CRM_Extension_Upgrader_SchemaTrait',
    'TasksTrait' => 'CRM_Extension_Upgrader_TasksTrait',
  ];

  // Generate two versions of the mixin:
  // - `mixin.backport.php` is a statically linked and has lower version# (eg `1.2.0`).
  // - `mixin.php` relies on autoloader to get latest class and has higher version# (eg `1.2.1`).
  file_put_contents(__DIR__ . '/mixin.backport.php', capture(function() use ($majorMinor, $mixinNamespace, $headers, $classMap) {
    $headers['mixinVersion'] = $majorMinor . '.0';

    printFileHeader($mixinNamespace, $majorMinor);
    foreach ($classMap as $newClass => $srcClass) {
      printFilteredClass($srcClass, function(string $line) use ($classMap) {
        return strtr($line, array_flip($classMap));
      });
    }
    printEmptyMixin($headers);
  }));

  file_put_contents(__DIR__ . '/mixin.php', capture(function() use ($majorMinor, $mixinNamespace, $headers, $classMap) {
    $headers['mixinVersion'] = $majorMinor . '.1';

    printFileHeader($mixinNamespace, $majorMinor);
    printFunction('registerClassAliases');
    print("\n");
    $fullAliasClasses = [];
    foreach ($classMap as $newClass => $srcClass) {
      $fullAliasClasses[$mixinNamespace . '\\' . $newClass] = $srcClass;
    }
    printf("registerClassAliases(%s);\n", capture('printData', $fullAliasClasses, '  '));
    printEmptyMixin($headers);
  }));
}

/**
 * Run a function and capture its output.
 *
 * @param callable $callback
 * @return string
 *   Any output generated by the function
 */
function capture($callback, ...$args): string {
  ob_start();
  try {
    $callback(...$args);
  }
  finally {
    return ob_get_clean();
  }
}

/**
 * @param string $mixinNamespace
 */
function printFileHeader(string $mixinNamespace, string $majorMinor): void {
  printf("<" . "?php\n");
  printf("// Generated via \"%s %s\"\n",
    str_replace(realpath(findCivicrmRoot()) . DIRECTORY_SEPARATOR, '', realpath(__FILE__)),
    $majorMinor
  );
  printf("namespace %s;\n", $mixinNamespace);
  printf("\n");
}

/**
 * @param array $headers
 */
function printEmptyMixin(array $headers): void {
  printf("/**\n");
  printf(" * Upgrader Base Class\n");
  foreach ($headers as $key => $value) {
    printf(" * @%s %s\n", $key, $value);
  }
  printf(" */\n");
  printf("return function(\$mixInfo, \$bootCache) {\n");
  printf("};\n");
}

function printFilteredClass(string $srcClass, $srcFilter = NULL) {
  $srcFile = str_replace('_', '/', $srcClass) . '.php';
  $srcLines = explode("\n", file_get_contents(findCivicrmRoot() . '/' . $srcFile));

  // Skip initial <?php declaration
  array_shift($srcLines);

  // Add a header
  array_unshift($srcLines, "// SOURCE: $srcFile\n");

  if ($srcFilter) {
    $srcLines = array_map($srcFilter, $srcLines);
  }

  echo implode("\n", $srcLines);
}

/**
 * @return string
 */
function findCivicrmRoot(): string {
  return dirname(__DIR__, 2);
}

function printFunction(string $funcName) {
  $function = new ReflectionFunction($funcName);
  $srcFile = $function->getFileName();
  $srcLines = explode("\n", file_get_contents($srcFile));
  $funcLines = array_slice($srcLines, $function->getStartLine() - 1, $function->getEndLine() - $function->getStartLine() + 1);
  echo implode("\n", $funcLines) . "\n";
}

function printData($data, string $prefix = '') {
  switch (gettype($data)) {
    case 'array':
      $isNumericArray = (range(0, count($data) - 1) == array_keys($data));
      echo "[\n";
      foreach ($data as $key => $value) {
        echo $prefix;
        if (!$isNumericArray) {
          printData($key);
          echo ' => ';
        }
        printData($value);
        echo ",\n";
      }
      echo "]";
      break;

    default:
      var_export($data);
  }
}

/**
 * @param array $classMap
 *   Ex: ['AliasClass' => 'OriginalClass']
 */
function registerClassAliases(array $classMap) {
  spl_autoload_register(function($requestedClass) use ($classMap) {
    if (isset($classMap[$requestedClass])) {
      class_alias($classMap[$requestedClass], $requestedClass);
    }
  });
}
