<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity Financial Transaction ID'),
    'description' => ts('ID'),
    'required' => TRUE,
    'where' => 'civicrm_entity_financial_trxn.id',
    'table_name' => 'civicrm_entity_financial_trxn',
    'entity' => 'EntityFinancialTrxn',
    'bao' => 'CRM_Financial_BAO_EntityFinancialTrxn',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.2',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('May contain civicrm_financial_item, civicrm_contribution, civicrm_financial_trxn, civicrm_grant, etc'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'import' => TRUE,
    'where' => 'civicrm_entity_financial_trxn.entity_table',
    'export' => TRUE,
    'table_name' => 'civicrm_entity_financial_trxn',
    'entity' => 'EntityFinancialTrxn',
    'bao' => 'CRM_Financial_BAO_EntityFinancialTrxn',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Financial_BAO_EntityFinancialTrxn::entityTables',
    ],
    'add' => '3.2',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'required' => TRUE,
    'where' => 'civicrm_entity_financial_trxn.entity_id',
    'table_name' => 'civicrm_entity_financial_trxn',
    'entity' => 'EntityFinancialTrxn',
    'bao' => 'CRM_Financial_BAO_EntityFinancialTrxn',
    'localizable' => 0,
    'add' => '3.2',
  ],
  'financial_trxn_id' => [
    'name' => 'financial_trxn_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Financial Transaction ID'),
    'where' => 'civicrm_entity_financial_trxn.financial_trxn_id',
    'table_name' => 'civicrm_entity_financial_trxn',
    'entity' => 'EntityFinancialTrxn',
    'bao' => 'CRM_Financial_BAO_EntityFinancialTrxn',
    'localizable' => 0,
    'FKClassName' => 'CRM_Financial_DAO_FinancialTrxn',
    'html' => [
      'label' => ts("Financial Transaction"),
    ],
    'add' => '3.2',
  ],
  'amount' => [
    'name' => 'amount',
    'type' => CRM_Utils_Type::T_MONEY,
    'title' => ts('Amount'),
    'description' => ts('allocated amount of transaction to this entity'),
    'required' => TRUE,
    'precision' => [
      20,
      2,
    ],
    'import' => TRUE,
    'where' => 'civicrm_entity_financial_trxn.amount',
    'headerPattern' => '/amount/i',
    'dataPattern' => '/^\d+(\.\d{2})?$/',
    'export' => TRUE,
    'table_name' => 'civicrm_entity_financial_trxn',
    'entity' => 'EntityFinancialTrxn',
    'bao' => 'CRM_Financial_BAO_EntityFinancialTrxn',
    'localizable' => 0,
    'add' => '3.2',
  ],
  ];
  
