<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Mailing Opened ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_opened.id',
    'table_name' => 'civicrm_mailing_event_opened',
    'entity' => 'MailingEventOpened',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventOpened',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'event_queue_id' => [
    'name' => 'event_queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Event Queue ID'),
    'description' => ts('FK to EventQueue'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_opened.event_queue_id',
    'table_name' => 'civicrm_mailing_event_opened',
    'entity' => 'MailingEventOpened',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventOpened',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventQueue',
    'html' => [
      'label' => ts("Recipient"),
    ],
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Timestamp'),
    'description' => ts('When this open event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_opened.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_opened',
    'entity' => 'MailingEventOpened',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventOpened',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
