<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contribution Product ID'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_product.id',
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.4',
  ],
  'product_id' => [
    'name' => 'product_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Product ID'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_product.product_id',
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_Product',
    'add' => '1.4',
  ],
  'contribution_id' => [
    'name' => 'contribution_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contribution ID'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_product.contribution_id',
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_Contribution',
    'html' => [
      'label' => ts("Contribution"),
    ],
    'add' => '1.4',
  ],
  'product_option' => [
    'name' => 'product_option',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Product Option'),
    'description' => ts('Option value selected if applicable - e.g. color, size etc.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_product.product_option',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'quantity' => [
    'name' => 'quantity',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Quantity'),
    'where' => 'civicrm_contribution_product.quantity',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'fulfilled_date' => [
    'name' => 'fulfilled_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Fulfilled Date'),
    'description' => ts('Optional. Can be used to record the date this product was fulfilled or shipped.'),
    'where' => 'civicrm_contribution_product.fulfilled_date',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'html' => [
      'type' => 'Select Date',
      'formatType' => 'activityDate',
    ],
    'add' => '1.4',
  ],
  'contribution_start_date' => [
    'name' => 'start_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Start date for premium'),
    'description' => ts('Actual start date for a time-delimited premium (subscription, service or membership)'),
    'where' => 'civicrm_contribution_product.start_date',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'contribution_end_date' => [
    'name' => 'end_date',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('End date for premium'),
    'description' => ts('Actual end date for a time-delimited premium (subscription, service or membership)'),
    'where' => 'civicrm_contribution_product.end_date',
    'export' => TRUE,
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'comment' => [
    'name' => 'comment',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Premium comment'),
    'where' => 'civicrm_contribution_product.comment',
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'add' => '1.4',
  ],
  'financial_type_id' => [
    'name' => 'financial_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Financial Type ID'),
    'description' => ts('FK to Financial Type(for membership price sets only).'),
    'where' => 'civicrm_contribution_product.financial_type_id',
    'default' => NULL,
    'table_name' => 'civicrm_contribution_product',
    'entity' => 'ContributionProduct',
    'bao' => 'CRM_Contribute_DAO_ContributionProduct',
    'localizable' => 0,
    'FKClassName' => 'CRM_Financial_DAO_FinancialType',
    'html' => [
      'label' => ts("Financial Type"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_financial_type',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '4.3',
  ],
  ];
  
