<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Financial Account ID'),
    'description' => ts('ID'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.id',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.2',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Financial Account Name'),
    'description' => ts('Financial Account Name.'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_financial_account.name',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '3.2',
  ],
  'financial_account_contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID that is responsible for the funds in this account'),
    'where' => 'civicrm_financial_account.contact_id',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '4.3',
  ],
  'financial_account_type_id' => [
    'name' => 'financial_account_type_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Financial Account Type'),
    'description' => ts('pseudo FK into civicrm_option_value.'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.financial_account_type_id',
    'default' => '3',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'optionGroupName' => 'financial_account_type',
      'optionEditPath' => 'civicrm/admin/options/financial_account_type',
    ],
    'add' => '4.3',
  ],
  'accounting_code' => [
    'name' => 'accounting_code',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Accounting Code'),
    'description' => ts('Optional value for mapping monies owed and received to accounting system codes.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_financial_account.accounting_code',
    'export' => TRUE,
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'account_type_code' => [
    'name' => 'account_type_code',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Account Type Code'),
    'description' => ts('Optional value for mapping account types to accounting system account categories (QuickBooks Account Type Codes for example).'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_financial_account.account_type_code',
    'export' => TRUE,
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Financial Account Description'),
    'description' => ts('Financial Type Description.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_financial_account.description',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'parent_id' => [
    'name' => 'parent_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Parent ID'),
    'description' => ts('Parent ID in account hierarchy'),
    'where' => 'civicrm_financial_account.parent_id',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'FKClassName' => 'CRM_Financial_DAO_FinancialAccount',
    'html' => [
      'label' => ts("Parent"),
    ],
    'add' => '4.3',
  ],
  'is_header_account' => [
    'name' => 'is_header_account',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Header Financial Account?'),
    'description' => ts('Is this a header account which does not allow transactions to be posted against it directly, but only to its sub-accounts?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.is_header_account',
    'default' => '0',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'is_deductible' => [
    'name' => 'is_deductible',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Deductible Financial Account?'),
    'description' => ts('Is this account tax-deductible?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.is_deductible',
    'default' => '0',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'is_tax' => [
    'name' => 'is_tax',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Tax Financial Account?'),
    'description' => ts('Is this account for taxes?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.is_tax',
    'default' => '0',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'tax_rate' => [
    'name' => 'tax_rate',
    'type' => CRM_Utils_Type::T_MONEY,
    'title' => ts('Financial Account Tax Rate'),
    'description' => ts('The percentage of the total_amount that is due for this tax.'),
    'precision' => [
      10,
      8,
    ],
    'where' => 'civicrm_financial_account.tax_rate',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Reserved Financial Account?'),
    'description' => ts('Is this a predefined system object?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'add' => '4.3',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Financial Account is Active'),
    'description' => ts('Is this property active?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.is_active',
    'default' => '1',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.3',
  ],
  'is_default' => [
    'name' => 'is_default',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Default Financial Account'),
    'description' => ts('Is this account the default one (or default tax one) for its financial_account_type?'),
    'required' => TRUE,
    'where' => 'civicrm_financial_account.is_default',
    'default' => '0',
    'table_name' => 'civicrm_financial_account',
    'entity' => 'FinancialAccount',
    'bao' => 'CRM_Financial_BAO_FinancialAccount',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Default"),
    ],
    'add' => '4.3',
  ],
  ];
  
