<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Job Log ID'),
    'description' => ts('Job log entry ID'),
    'required' => TRUE,
    'where' => 'civicrm_job_log.id',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.1',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this scheduled job for'),
    'required' => TRUE,
    'where' => 'civicrm_job_log.domain_id',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '4.1',
  ],
  'run_time' => [
    'name' => 'run_time',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Timestamp'),
    'description' => ts('Log entry date'),
    'where' => 'civicrm_job_log.run_time',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'job_id' => [
    'name' => 'job_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Job ID'),
    'description' => ts('Pointer to job id'),
    'where' => 'civicrm_job_log.job_id',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Job',
    'html' => [
      'type' => 'Number',
    ],
    'add' => '4.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Job Name'),
    'description' => ts('Title of the job'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job_log.name',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'command' => [
    'name' => 'command',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Command'),
    'description' => ts('Full path to file containing job script'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job_log.command',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Description'),
    'description' => ts('Title line of log entry'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_job_log.description',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'add' => '4.1',
  ],
  'data' => [
    'name' => 'data',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Extended Data'),
    'description' => ts('Potential extended data for specific job run (e.g. tracebacks).'),
    'where' => 'civicrm_job_log.data',
    'table_name' => 'civicrm_job_log',
    'entity' => 'JobLog',
    'bao' => 'CRM_Core_DAO_JobLog',
    'localizable' => 0,
    'add' => '4.1',
  ],
  ];
  
