<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Reply ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_reply.id',
    'table_name' => 'civicrm_mailing_event_reply',
    'entity' => 'MailingEventReply',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventReply',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'event_queue_id' => [
    'name' => 'event_queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Event Queue ID'),
    'description' => ts('FK to EventQueue'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_reply.event_queue_id',
    'table_name' => 'civicrm_mailing_event_reply',
    'entity' => 'MailingEventReply',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventReply',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventQueue',
    'html' => [
      'label' => ts("Recipient"),
    ],
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Reply Timestamp'),
    'description' => ts('When this reply event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_reply.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_reply',
    'entity' => 'MailingEventReply',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventReply',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
