<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity Role'),
    'description' => ts('Unique table ID'),
    'required' => TRUE,
    'where' => 'civicrm_acl_entity_role.id',
    'table_name' => 'civicrm_acl_entity_role',
    'entity' => 'ACLEntityRole',
    'bao' => 'CRM_ACL_BAO_ACLEntityRole',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.6',
  ],
  'acl_role_id' => [
    'name' => 'acl_role_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('ACL Role ID'),
    'description' => ts('Foreign Key to ACL Role (which is an option value pair and hence an implicit FK)'),
    'required' => TRUE,
    'where' => 'civicrm_acl_entity_role.acl_role_id',
    'table_name' => 'civicrm_acl_entity_role',
    'entity' => 'ACLEntityRole',
    'bao' => 'CRM_ACL_BAO_ACLEntityRole',
    'localizable' => 0,
    'pseudoconstant' => [
      'optionGroupName' => 'acl_role',
      'optionEditPath' => 'civicrm/admin/options/acl_role',
    ],
    'add' => '1.6',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('Table of the object joined to the ACL Role (Contact or Group)'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_acl_entity_role.entity_table',
    'table_name' => 'civicrm_acl_entity_role',
    'entity' => 'ACLEntityRole',
    'bao' => 'CRM_ACL_BAO_ACLEntityRole',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_ACL_BAO_ACLEntityRole::entityTables',
    ],
    'add' => '1.6',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('ACL Entity ID'),
    'description' => ts('ID of the group/contact object being joined'),
    'required' => TRUE,
    'where' => 'civicrm_acl_entity_role.entity_id',
    'table_name' => 'civicrm_acl_entity_role',
    'entity' => 'ACLEntityRole',
    'bao' => 'CRM_ACL_BAO_ACLEntityRole',
    'localizable' => 0,
    'add' => '1.6',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('ACL Entity Role is Active'),
    'description' => ts('Is this property active?'),
    'required' => TRUE,
    'where' => 'civicrm_acl_entity_role.is_active',
    'default' => '1',
    'table_name' => 'civicrm_acl_entity_role',
    'entity' => 'ACLEntityRole',
    'bao' => 'CRM_ACL_BAO_ACLEntityRole',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.6',
  ],
  ];
  
