<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('DashletID'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard.id',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.1',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Domain for dashboard'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard.domain_id',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '3.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Dashlet Name'),
    'description' => ts('Internal name of dashlet.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_dashboard.name',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'add' => '4.4',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Dashlet Title'),
    'description' => ts('dashlet title'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dashboard.label',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 1,
    'add' => '3.1',
  ],
  'url' => [
    'name' => 'url',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Dashlet URL'),
    'description' => ts('url in case of external dashlet'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dashboard.url',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'add' => '3.1',
  ],
  'permission' => [
    'name' => 'permission',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Dashlet Permission'),
    'description' => ts('Permission for the dashlet'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dashboard.permission',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_COMMA,
    'add' => '3.1',
  ],
  'permission_operator' => [
    'name' => 'permission_operator',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Dashlet Permission Operator'),
    'description' => ts('Permission Operator'),
    'maxlength' => 3,
    'size' => CRM_Utils_Type::FOUR,
    'where' => 'civicrm_dashboard.permission_operator',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Core_SelectValues::andOr',
    ],
    'add' => '3.1',
  ],
  'fullscreen_url' => [
    'name' => 'fullscreen_url',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Fullscreen URL'),
    'description' => ts('fullscreen url for dashlet'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dashboard.fullscreen_url',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Dashlet Active?'),
    'description' => ts('Is this dashlet active?'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard.is_active',
    'default' => '0',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '3.1',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Is Dashlet Reserved?'),
    'description' => ts('Is this dashlet reserved?'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'add' => '3.1',
  ],
  'cache_minutes' => [
    'name' => 'cache_minutes',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Cache Minutes'),
    'description' => ts('Number of minutes to cache dashlet content in browser localStorage.'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard.cache_minutes',
    'default' => '60',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'add' => '4.7',
  ],
  'directive' => [
    'name' => 'directive',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Angular directive'),
    'description' => ts('Element name of angular directive to invoke (lowercase hyphenated format)'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_dashboard.directive',
    'table_name' => 'civicrm_dashboard',
    'entity' => 'Dashboard',
    'bao' => 'CRM_Core_BAO_Dashboard',
    'localizable' => 0,
    'add' => '5.33',
  ],
  ];
  
