<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group Contact Cache ID'),
    'description' => ts('primary key'),
    'required' => TRUE,
    'where' => 'civicrm_group_contact_cache.id',
    'table_name' => 'civicrm_group_contact_cache',
    'entity' => 'GroupContactCache',
    'bao' => 'CRM_Contact_BAO_GroupContactCache',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.1',
  ],
  'group_id' => [
    'name' => 'group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group ID'),
    'description' => ts('FK to civicrm_group'),
    'required' => TRUE,
    'where' => 'civicrm_group_contact_cache.group_id',
    'table_name' => 'civicrm_group_contact_cache',
    'entity' => 'GroupContactCache',
    'bao' => 'CRM_Contact_BAO_GroupContactCache',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Group',
    'html' => [
      'type' => 'Select',
      'label' => ts("Group"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '2.1',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to civicrm_contact'),
    'required' => TRUE,
    'where' => 'civicrm_group_contact_cache.contact_id',
    'table_name' => 'civicrm_group_contact_cache',
    'entity' => 'GroupContactCache',
    'bao' => 'CRM_Contact_BAO_GroupContactCache',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '2.1',
  ],
  ];
  
