<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Report Instance ID'),
    'description' => ts('Report Instance ID'),
    'required' => TRUE,
    'where' => 'civicrm_report_instance.id',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.2',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this instance for'),
    'required' => TRUE,
    'where' => 'civicrm_report_instance.domain_id',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '3.1',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report Instance Title'),
    'description' => ts('Report Instance Title.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.title',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.2',
  ],
  'report_id' => [
    'name' => 'report_id',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report template ID'),
    'description' => ts('FK to civicrm_option_value for the report template'),
    'required' => TRUE,
    'maxlength' => 512,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.report_id',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'add' => '2.2',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report instance Name'),
    'description' => ts('when combined with report_id/template uniquely identifies the instance'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.name',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.2',
  ],
  'args' => [
    'name' => 'args',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report Instance Arguments'),
    'description' => ts('arguments that are passed in the url when invoking the instance'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.args',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.2',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report Instance description'),
    'description' => ts('Report Instance description.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.description',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.2',
  ],
  'permission' => [
    'name' => 'permission',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report Instance Permissions'),
    'description' => ts('permission required to be able to run this instance'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.permission',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.2',
  ],
  'grouprole' => [
    'name' => 'grouprole',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report Instance Assigned to Roles'),
    'description' => ts('role required to be able to run this instance'),
    'maxlength' => 1024,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.grouprole',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.1',
  ],
  'form_values' => [
    'name' => 'form_values',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Submitted Form Values'),
    'description' => ts('Submitted form values for this report'),
    'import' => TRUE,
    'where' => 'civicrm_report_instance.form_values',
    'export' => TRUE,
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'serialize' => CRM_Core_DAO::SERIALIZE_PHP,
    'add' => '2.2',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Report Instance is Active'),
    'description' => ts('Is this entry active?'),
    'required' => TRUE,
    'where' => 'civicrm_report_instance.is_active',
    'default' => '1',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '2.2',
  ],
  'created_id' => [
    'name' => 'created_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Created By Contact ID'),
    'description' => ts('FK to contact table.'),
    'where' => 'civicrm_report_instance.created_id',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Created By"),
    ],
    'add' => '4.6',
  ],
  'owner_id' => [
    'name' => 'owner_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Owned By Contact ID'),
    'description' => ts('FK to contact table.'),
    'where' => 'civicrm_report_instance.owner_id',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Owned By"),
    ],
    'add' => '4.6',
  ],
  'email_subject' => [
    'name' => 'email_subject',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Report Instance email Subject'),
    'description' => ts('Subject of email'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_report_instance.email_subject',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => NULL,
  ],
  'email_to' => [
    'name' => 'email_to',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Email Report Instance To'),
    'description' => ts('comma-separated list of email addresses to send the report to'),
    'where' => 'civicrm_report_instance.email_to',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.2',
  ],
  'email_cc' => [
    'name' => 'email_cc',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('cc Email Report Instance To'),
    'description' => ts('comma-separated list of email addresses to send the report to'),
    'where' => 'civicrm_report_instance.email_cc',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '2.2',
  ],
  'header' => [
    'name' => 'header',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Report Instance Header'),
    'description' => ts('comma-separated list of email addresses to send the report to'),
    'rows' => 4,
    'cols' => 60,
    'where' => 'civicrm_report_instance.header',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '2.2',
  ],
  'footer' => [
    'name' => 'footer',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Report Instance Footer'),
    'description' => ts('comma-separated list of email addresses to send the report to'),
    'rows' => 4,
    'cols' => 60,
    'where' => 'civicrm_report_instance.footer',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '2.2',
  ],
  'navigation_id' => [
    'name' => 'navigation_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Navigation ID'),
    'description' => ts('FK to navigation ID'),
    'import' => TRUE,
    'where' => 'civicrm_report_instance.navigation_id',
    'export' => TRUE,
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Navigation',
    'html' => [
      'label' => ts("Navigation"),
    ],
    'add' => '3.0',
  ],
  'drilldown_id' => [
    'name' => 'drilldown_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Drilldown Report ID'),
    'description' => ts('FK to instance ID drilldown to'),
    'import' => TRUE,
    'where' => 'civicrm_report_instance.drilldown_id',
    'export' => TRUE,
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'FKClassName' => 'CRM_Report_DAO_ReportInstance',
    'html' => [
      'label' => ts("Drilldown Report"),
    ],
    'add' => '4.3',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Instance is Reserved'),
    'required' => TRUE,
    'where' => 'civicrm_report_instance.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_report_instance',
    'entity' => 'ReportInstance',
    'bao' => 'CRM_Report_BAO_ReportInstance',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '4.2',
  ],
  ];
  
