<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Relationship Type ID'),
    'description' => ts('Primary key'),
    'required' => TRUE,
    'where' => 'civicrm_relationship_type.id',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'name_a_b' => [
    'name' => 'name_a_b',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Relationship Type Name A to B'),
    'description' => ts('name for relationship of contact_a to contact_b.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_relationship_type.name_a_b',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'label_a_b' => [
    'name' => 'label_a_b',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Relationship Type Label A to B'),
    'description' => ts('label for relationship of contact_a to contact_b.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_relationship_type.label_a_b',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.0',
  ],
  'name_b_a' => [
    'name' => 'name_b_a',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Relationship Type Name B to A'),
    'description' => ts('Optional name for relationship of contact_b to contact_a.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_relationship_type.name_b_a',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'add' => '1.1',
  ],
  'label_b_a' => [
    'name' => 'label_b_a',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Relationship Type Label B to A'),
    'description' => ts('Optional label for relationship of contact_b to contact_a.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_relationship_type.label_b_a',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '3.0',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Relationship Description'),
    'description' => ts('Optional verbose description of the relationship type.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_relationship_type.description',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.1',
  ],
  'contact_type_a' => [
    'name' => 'contact_type_a',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Type for Contact A'),
    'description' => ts('If defined, contact_a in a relationship of this type must be a specific contact_type.'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_relationship_type.contact_type_a',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_contact_type',
      'keyColumn' => 'name',
      'labelColumn' => 'label',
      'condition' => 'parent_id IS NULL',
    ],
    'add' => '1.1',
  ],
  'contact_type_b' => [
    'name' => 'contact_type_b',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Type for Contact B'),
    'description' => ts('If defined, contact_b in a relationship of this type must be a specific contact_type.'),
    'maxlength' => 12,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_relationship_type.contact_type_b',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_contact_type',
      'keyColumn' => 'name',
      'labelColumn' => 'label',
      'condition' => 'parent_id IS NULL',
    ],
    'add' => '1.1',
  ],
  'contact_sub_type_a' => [
    'name' => 'contact_sub_type_a',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Subtype A'),
    'description' => ts('If defined, contact_sub_type_a in a relationship of this type must be a specific contact_sub_type.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_relationship_type.contact_sub_type_a',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_contact_type',
      'keyColumn' => 'name',
      'labelColumn' => 'label',
      'condition' => 'parent_id IS NOT NULL',
    ],
    'add' => '3.1',
  ],
  'contact_sub_type_b' => [
    'name' => 'contact_sub_type_b',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Subtype B'),
    'description' => ts('If defined, contact_sub_type_b in a relationship of this type must be a specific contact_sub_type.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_relationship_type.contact_sub_type_b',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'Select',
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_contact_type',
      'keyColumn' => 'name',
      'labelColumn' => 'label',
      'condition' => 'parent_id IS NOT NULL',
    ],
    'add' => '3.1',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Relationship Type is Reserved'),
    'description' => ts('Is this relationship type a predefined system type (can not be changed or de-activated)?'),
    'required' => TRUE,
    'where' => 'civicrm_relationship_type.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '1.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Relationship Type is Active'),
    'description' => ts('Is this relationship type currently active (i.e. can be used when creating or editing relationships)?'),
    'required' => TRUE,
    'where' => 'civicrm_relationship_type.is_active',
    'default' => '1',
    'table_name' => 'civicrm_relationship_type',
    'entity' => 'RelationshipType',
    'bao' => 'CRM_Contact_BAO_RelationshipType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '1.1',
  ],
  ];
  
