<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Spool ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_spool.id',
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'job_id' => [
    'name' => 'job_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Job ID'),
    'description' => ts('The ID of the Job .'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_spool.job_id',
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_DAO_MailingJob',
    'html' => [
      'label' => ts("Job"),
    ],
    'add' => NULL,
  ],
  'recipient_email' => [
    'name' => 'recipient_email',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Recipient Email'),
    'description' => ts('The email of the recipients this mail is to be sent.'),
    'where' => 'civicrm_mailing_spool.recipient_email',
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'add' => NULL,
  ],
  'headers' => [
    'name' => 'headers',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Headers'),
    'description' => ts('The header information of this mailing .'),
    'where' => 'civicrm_mailing_spool.headers',
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'add' => NULL,
  ],
  'body' => [
    'name' => 'body',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Body'),
    'description' => ts('The body of this mailing.'),
    'where' => 'civicrm_mailing_spool.body',
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'add' => NULL,
  ],
  'added_at' => [
    'name' => 'added_at',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Added'),
    'description' => ts('date on which this job was added.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing_spool.added_at',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'add' => NULL,
  ],
  'removed_at' => [
    'name' => 'removed_at',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Removed'),
    'description' => ts('date on which this job was removed.'),
    'required' => FALSE,
    'where' => 'civicrm_mailing_spool.removed_at',
    'default' => NULL,
    'table_name' => 'civicrm_mailing_spool',
    'entity' => 'Spool',
    'bao' => 'CRM_Mailing_BAO_Spool',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
