<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Forward ID'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_forward.id',
    'table_name' => 'civicrm_mailing_event_forward',
    'entity' => 'MailingEventForward',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventForward',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
      'label' => ts("ID"),
    ],
    'readonly' => TRUE,
    'add' => NULL,
  ],
  'event_queue_id' => [
    'name' => 'event_queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Event Queue ID'),
    'description' => ts('FK to EventQueue'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_forward.event_queue_id',
    'table_name' => 'civicrm_mailing_event_forward',
    'entity' => 'MailingEventForward',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventForward',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventQueue',
    'html' => [
      'label' => ts("Recipient"),
    ],
    'add' => NULL,
  ],
  'dest_queue_id' => [
    'name' => 'dest_queue_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Destination Queue ID'),
    'description' => ts('FK to EventQueue for destination'),
    'where' => 'civicrm_mailing_event_forward.dest_queue_id',
    'table_name' => 'civicrm_mailing_event_forward',
    'entity' => 'MailingEventForward',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventForward',
    'localizable' => 0,
    'FKClassName' => 'CRM_Mailing_Event_DAO_MailingEventQueue',
    'html' => [
      'label' => ts("Destination Queue"),
    ],
    'add' => NULL,
  ],
  'time_stamp' => [
    'name' => 'time_stamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Timestamp'),
    'description' => ts('When this forward event occurred.'),
    'required' => TRUE,
    'where' => 'civicrm_mailing_event_forward.time_stamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_mailing_event_forward',
    'entity' => 'MailingEventForward',
    'bao' => 'CRM_Mailing_Event_BAO_MailingEventForward',
    'localizable' => 0,
    'add' => NULL,
  ],
  ];
  
