<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Status Preference ID'),
    'description' => ts('Unique Status Preference ID'),
    'required' => TRUE,
    'where' => 'civicrm_status_pref.id',
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.7',
  ],
  'domain_id' => [
    'name' => 'domain_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Domain ID'),
    'description' => ts('Which Domain is this Status Preference for'),
    'required' => TRUE,
    'where' => 'civicrm_status_pref.domain_id',
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Domain',
    'html' => [
      'label' => ts("Domain"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_domain',
      'keyColumn' => 'id',
      'labelColumn' => 'name',
    ],
    'add' => '4.7',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Status Check Name'),
    'description' => ts('Name of the status check this preference references.'),
    'required' => TRUE,
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'import' => TRUE,
    'where' => 'civicrm_status_pref.name',
    'export' => TRUE,
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'add' => '4.7',
  ],
  'hush_until' => [
    'name' => 'hush_until',
    'type' => CRM_Utils_Type::T_DATE,
    'title' => ts('Snooze Status Notifications Until'),
    'description' => ts('expires ignore_severity.  NULL never hushes.'),
    'import' => TRUE,
    'where' => 'civicrm_status_pref.hush_until',
    'export' => TRUE,
    'default' => NULL,
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'add' => '4.7',
  ],
  'ignore_severity' => [
    'name' => 'ignore_severity',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Ignore Severity'),
    'description' => ts('Hush messages up to and including this severity.'),
    'import' => TRUE,
    'where' => 'civicrm_status_pref.ignore_severity',
    'export' => TRUE,
    'default' => '1',
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Utils_Check::getSeverityOptions',
    ],
    'add' => '4.7',
  ],
  'prefs' => [
    'name' => 'prefs',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Status Preferences'),
    'description' => ts('These settings are per-check, and can\'t be compared across checks.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_status_pref.prefs',
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'add' => '4.7',
  ],
  'check_info' => [
    'name' => 'check_info',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Check Info'),
    'description' => ts('These values are per-check, and can\'t be compared across checks.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_status_pref.check_info',
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'add' => '4.7',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Check Is Active'),
    'description' => ts('Is this status check active?'),
    'required' => TRUE,
    'where' => 'civicrm_status_pref.is_active',
    'default' => '1',
    'table_name' => 'civicrm_status_pref',
    'entity' => 'StatusPreference',
    'bao' => 'CRM_Core_BAO_StatusPreference',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '5.19',
  ],
  ];
  
