<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact Type ID'),
    'description' => ts('Contact Type ID'),
    'required' => TRUE,
    'where' => 'civicrm_contact_type.id',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.1',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Name'),
    'description' => ts('Internal name of Contact Type (or Subtype).'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_contact_type.name',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
      'label' => ts("Name"),
    ],
    'add' => '3.1',
  ],
  'label' => [
    'name' => 'label',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Type Label'),
    'description' => ts('localized Name of Contact Type.'),
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_contact_type.label',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
      'label' => ts("Label"),
    ],
    'add' => '3.1',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Contact Type Description'),
    'description' => ts('localized Optional verbose description of the type.'),
    'rows' => 2,
    'cols' => 60,
    'where' => 'civicrm_contact_type.description',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 1,
    'html' => [
      'type' => 'TextArea',
    ],
    'add' => '3.1',
  ],
  'image_URL' => [
    'name' => 'image_URL',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Contact Type Image URL'),
    'description' => ts('URL of image if any.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contact_type.image_URL',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'add' => '3.1',
  ],
  'icon' => [
    'name' => 'icon',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Icon'),
    'description' => ts('crm-i icon class representing this contact type'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contact_type.icon',
    'default' => NULL,
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'add' => '5.49',
  ],
  'parent_id' => [
    'name' => 'parent_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Parent ID'),
    'description' => ts('Optional FK to parent contact type.'),
    'where' => 'civicrm_contact_type.parent_id',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_ContactType',
    'html' => [
      'type' => 'Select',
      'label' => ts("Parent"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_contact_type',
      'keyColumn' => 'id',
      'labelColumn' => 'label',
      'condition' => 'parent_id IS NULL',
    ],
    'add' => '3.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Contact Type Enabled'),
    'description' => ts('Is this entry active?'),
    'required' => TRUE,
    'where' => 'civicrm_contact_type.is_active',
    'default' => '1',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '3.1',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Contact Type is Reserved'),
    'description' => ts('Is this contact type a predefined system type'),
    'required' => TRUE,
    'where' => 'civicrm_contact_type.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_contact_type',
    'entity' => 'ContactType',
    'bao' => 'CRM_Contact_BAO_ContactType',
    'localizable' => 0,
    'add' => '3.1',
  ],
  ];
  
