<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Dashboard Contact ID'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard_contact.id',
    'table_name' => 'civicrm_dashboard_contact',
    'entity' => 'DashboardContact',
    'bao' => 'CRM_Contact_BAO_DashboardContact',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.1',
  ],
  'dashboard_id' => [
    'name' => 'dashboard_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Dashboard ID'),
    'description' => ts('Dashboard ID'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard_contact.dashboard_id',
    'table_name' => 'civicrm_dashboard_contact',
    'entity' => 'DashboardContact',
    'bao' => 'CRM_Contact_BAO_DashboardContact',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_Dashboard',
    'html' => [
      'label' => ts("Dashboard"),
    ],
    'add' => '3.1',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('Contact ID'),
    'required' => TRUE,
    'where' => 'civicrm_dashboard_contact.contact_id',
    'table_name' => 'civicrm_dashboard_contact',
    'entity' => 'DashboardContact',
    'bao' => 'CRM_Contact_BAO_DashboardContact',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '3.1',
  ],
  'column_no' => [
    'name' => 'column_no',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Column No'),
    'description' => ts('column no for this widget'),
    'where' => 'civicrm_dashboard_contact.column_no',
    'default' => '0',
    'table_name' => 'civicrm_dashboard_contact',
    'entity' => 'DashboardContact',
    'bao' => 'CRM_Contact_BAO_DashboardContact',
    'localizable' => 0,
    'html' => [
      'label' => ts("Column Number"),
    ],
    'add' => '3.1',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Dashlet is Active?'),
    'description' => ts('Is this widget active?'),
    'where' => 'civicrm_dashboard_contact.is_active',
    'default' => '0',
    'table_name' => 'civicrm_dashboard_contact',
    'entity' => 'DashboardContact',
    'bao' => 'CRM_Contact_BAO_DashboardContact',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '3.1',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('Ordering of the widgets.'),
    'where' => 'civicrm_dashboard_contact.weight',
    'default' => '0',
    'table_name' => 'civicrm_dashboard_contact',
    'entity' => 'DashboardContact',
    'bao' => 'CRM_Contact_BAO_DashboardContact',
    'localizable' => 0,
    'add' => '3.1',
  ],
  ];
  
