<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from xml/schema/CRM/Core/Discount.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:39f48abf39ca4618fa51b61514053042)
 */

/**
 * Database access object for the Discount entity.
 */
class CRM_Core_DAO_Discount_Fields {

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Discount ID'),
          'description' => ts('primary key'),
          'required' => TRUE,
          'where' => 'civicrm_discount.id',
          'table_name' => 'civicrm_discount',
          'entity' => 'Discount',
          'bao' => 'CRM_Core_BAO_Discount',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '2.1',
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Entity Table'),
          'description' => ts('physical tablename for entity being joined to discount, e.g. civicrm_event'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_discount.entity_table',
          'table_name' => 'civicrm_discount',
          'entity' => 'Discount',
          'bao' => 'CRM_Core_BAO_Discount',
          'localizable' => 0,
          'add' => '2.1',
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Entity ID'),
          'description' => ts('FK to entity table specified in entity_table column.'),
          'required' => TRUE,
          'where' => 'civicrm_discount.entity_id',
          'table_name' => 'civicrm_discount',
          'entity' => 'Discount',
          'bao' => 'CRM_Core_BAO_Discount',
          'localizable' => 0,
          'add' => '2.1',
        ],
        'participant_discount_name' => [
          'name' => 'price_set_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Price Set ID'),
          'description' => ts('FK to civicrm_price_set'),
          'required' => TRUE,
          'where' => 'civicrm_discount.price_set_id',
          'export' => TRUE,
          'table_name' => 'civicrm_discount',
          'entity' => 'Discount',
          'bao' => 'CRM_Core_BAO_Discount',
          'localizable' => 0,
          'FKClassName' => 'CRM_Price_DAO_PriceSet',
          'html' => [
            'label' => ts("Price Set"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_price_set',
            'keyColumn' => 'id',
            'labelColumn' => 'title',
          ],
          'add' => '4.3',
        ],
        'start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Discount Start Date'),
          'description' => ts('Date when discount starts.'),
          'where' => 'civicrm_discount.start_date',
          'table_name' => 'civicrm_discount',
          'entity' => 'Discount',
          'bao' => 'CRM_Core_BAO_Discount',
          'localizable' => 0,
          'add' => '2.1',
        ],
        'end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Discount End Date'),
          'description' => ts('Date when discount ends.'),
          'where' => 'civicrm_discount.end_date',
          'table_name' => 'civicrm_discount',
          'entity' => 'Discount',
          'bao' => 'CRM_Core_BAO_Discount',
          'localizable' => 0,
          'add' => '2.1',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

}
