<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('System Log ID'),
    'description' => ts('Primary key ID'),
    'required' => TRUE,
    'where' => 'civicrm_system_log.id',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.4',
  ],
  'message' => [
    'name' => 'message',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('System Log Message'),
    'description' => ts('Standardized message'),
    'required' => TRUE,
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_system_log.message',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'add' => '4.5',
  ],
  'context' => [
    'name' => 'context',
    'type' => CRM_Utils_Type::T_LONGTEXT,
    'title' => ts('Detailed Log Data'),
    'description' => ts('JSON encoded data'),
    'where' => 'civicrm_system_log.context',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'add' => '4.5',
  ],
  'level' => [
    'name' => 'level',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Detailed Log Data'),
    'description' => ts('error level per PSR3'),
    'maxlength' => 9,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_system_log.level',
    'default' => 'info',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'add' => '4.5',
  ],
  'timestamp' => [
    'name' => 'timestamp',
    'type' => CRM_Utils_Type::T_TIMESTAMP,
    'title' => ts('Log Timestamp'),
    'description' => ts('Timestamp of when event occurred.'),
    'where' => 'civicrm_system_log.timestamp',
    'default' => 'CURRENT_TIMESTAMP',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'add' => '4.5',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Log Contact ID'),
    'description' => ts('Optional Contact ID that created the log. Not an FK as we keep this regardless'),
    'where' => 'civicrm_system_log.contact_id',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'add' => '4.5',
  ],
  'hostname' => [
    'name' => 'hostname',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Log Host'),
    'description' => ts('Optional Name of logging host'),
    'maxlength' => 128,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_system_log.hostname',
    'table_name' => 'civicrm_system_log',
    'entity' => 'SystemLog',
    'bao' => 'CRM_Core_DAO_SystemLog',
    'localizable' => 0,
    'add' => '4.5',
  ],
  ];
  
