<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Case Type ID'),
    'description' => ts('Autoincremented type id'),
    'required' => TRUE,
    'where' => 'civicrm_case_type.id',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '4.5',
  ],
  'name' => [
    'name' => 'name',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Case Type Name'),
    'description' => ts('Machine name for Case Type'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_case_type.name',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.5',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Case Type Title'),
    'description' => ts('Natural language name for Case Type'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_case_type.title',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.5',
  ],
  'description' => [
    'name' => 'description',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Case Type Description'),
    'description' => ts('Description of the Case Type'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_case_type.description',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 1,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '4.5',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Case Type Is Active'),
    'description' => ts('Is this case type enabled?'),
    'required' => TRUE,
    'where' => 'civicrm_case_type.is_active',
    'default' => '1',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '4.5',
  ],
  'is_reserved' => [
    'name' => 'is_reserved',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Case Type Is Reserved'),
    'description' => ts('Is this case type a predefined system type?'),
    'required' => TRUE,
    'where' => 'civicrm_case_type.is_reserved',
    'default' => '0',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
    ],
    'add' => '4.5',
  ],
  'weight' => [
    'name' => 'weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('Ordering of the case types'),
    'required' => TRUE,
    'where' => 'civicrm_case_type.weight',
    'default' => '1',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'add' => '4.5',
  ],
  'definition' => [
    'name' => 'definition',
    'type' => CRM_Utils_Type::T_BLOB,
    'title' => ts('Case Type Definition'),
    'description' => ts('xml definition of case type'),
    'where' => 'civicrm_case_type.definition',
    'table_name' => 'civicrm_case_type',
    'entity' => 'CaseType',
    'bao' => 'CRM_Case_BAO_CaseType',
    'localizable' => 0,
    'add' => '4.5',
  ],
  ];
  
