<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Action Schedule ID'),
    'required' => TRUE,
    'where' => 'civicrm_action_log.id',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '3.4',
  ],
  'contact_id' => [
    'name' => 'contact_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contact ID'),
    'description' => ts('FK to Contact ID'),
    'where' => 'civicrm_action_log.contact_id',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Contact"),
    ],
    'add' => '3.4',
  ],
  'entity_id' => [
    'name' => 'entity_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Entity ID'),
    'description' => ts('FK to id of the entity that the action was performed on. Pseudo - FK.'),
    'required' => TRUE,
    'where' => 'civicrm_action_log.entity_id',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'entity_table' => [
    'name' => 'entity_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Entity Table'),
    'description' => ts('name of the entity table for the above id, e.g. civicrm_activity, civicrm_participant'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_action_log.entity_table',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'action_schedule_id' => [
    'name' => 'action_schedule_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Schedule ID'),
    'description' => ts('FK to the action schedule that this action originated from.'),
    'required' => TRUE,
    'where' => 'civicrm_action_log.action_schedule_id',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'FKClassName' => 'CRM_Core_DAO_ActionSchedule',
    'html' => [
      'label' => ts("Schedule"),
    ],
    'add' => '3.4',
  ],
  'action_date_time' => [
    'name' => 'action_date_time',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Action Date And Time'),
    'description' => ts('date time that the action was performed on.'),
    'where' => 'civicrm_action_log.action_date_time',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'is_error' => [
    'name' => 'is_error',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Error?'),
    'description' => ts('Was there any error sending the reminder?'),
    'required' => TRUE,
    'where' => 'civicrm_action_log.is_error',
    'default' => '0',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'message' => [
    'name' => 'message',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Message'),
    'description' => ts('Description / text in case there was an error encountered.'),
    'where' => 'civicrm_action_log.message',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'repetition_number' => [
    'name' => 'repetition_number',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Repetition Number'),
    'description' => ts('Keeps track of the sequence number of this repetition.'),
    'where' => 'civicrm_action_log.repetition_number',
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '3.4',
  ],
  'reference_date' => [
    'name' => 'reference_date',
    'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
    'title' => ts('Reference Date'),
    'description' => ts('Stores the date from the entity which triggered this reminder action (e.g. membership.end_date for most membership renewal reminders)'),
    'where' => 'civicrm_action_log.reference_date',
    'default' => NULL,
    'table_name' => 'civicrm_action_log',
    'entity' => 'ActionLog',
    'bao' => 'CRM_Core_BAO_ActionLog',
    'localizable' => 0,
    'add' => '4.6',
  ],
  ];
  
