<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group Organization ID'),
    'description' => ts('Relationship ID'),
    'required' => TRUE,
    'where' => 'civicrm_group_organization.id',
    'table_name' => 'civicrm_group_organization',
    'entity' => 'GroupOrganization',
    'bao' => 'CRM_Contact_BAO_GroupOrganization',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.0',
  ],
  'group_id' => [
    'name' => 'group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group ID'),
    'description' => ts('ID of the group'),
    'required' => TRUE,
    'where' => 'civicrm_group_organization.group_id',
    'table_name' => 'civicrm_group_organization',
    'entity' => 'GroupOrganization',
    'bao' => 'CRM_Contact_BAO_GroupOrganization',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Group',
    'html' => [
      'type' => 'Select',
      'label' => ts("Group"),
    ],
    'pseudoconstant' => [
      'table' => 'civicrm_group',
      'keyColumn' => 'id',
      'labelColumn' => 'title',
    ],
    'add' => '2.0',
  ],
  'organization_id' => [
    'name' => 'organization_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Organization ID'),
    'description' => ts('ID of the Organization Contact'),
    'required' => TRUE,
    'where' => 'civicrm_group_organization.organization_id',
    'table_name' => 'civicrm_group_organization',
    'entity' => 'GroupOrganization',
    'bao' => 'CRM_Contact_BAO_GroupOrganization',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contact_DAO_Contact',
    'html' => [
      'label' => ts("Organization"),
    ],
    'add' => '2.0',
  ],
  ];
  
