<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Widget ID'),
    'description' => ts('Contribution ID'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_widget.id',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '2.0',
  ],
  'contribution_page_id' => [
    'name' => 'contribution_page_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Contribution Page ID'),
    'description' => ts('The Contribution Page which triggered this contribution'),
    'where' => 'civicrm_contribution_widget.contribution_page_id',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'FKClassName' => 'CRM_Contribute_DAO_ContributionPage',
    'html' => [
      'label' => ts("Contribution Page"),
    ],
    'add' => '1.5',
  ],
  'is_active' => [
    'name' => 'is_active',
    'type' => CRM_Utils_Type::T_BOOLEAN,
    'title' => ts('Enabled?'),
    'description' => ts('Is this property active?'),
    'required' => TRUE,
    'where' => 'civicrm_contribution_widget.is_active',
    'default' => '1',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'html' => [
      'type' => 'CheckBox',
      'label' => ts("Enabled"),
    ],
    'add' => '2.0',
  ],
  'title' => [
    'name' => 'title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Widget Title'),
    'description' => ts('Widget title.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_widget.title',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'url_logo' => [
    'name' => 'url_logo',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Widget Image Url'),
    'description' => ts('URL to Widget logo'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_widget.url_logo',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'button_title' => [
    'name' => 'button_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Button Title'),
    'description' => ts('Button title.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_widget.button_title',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'about' => [
    'name' => 'about',
    'type' => CRM_Utils_Type::T_TEXT,
    'title' => ts('Description'),
    'description' => ts('About description.'),
    'where' => 'civicrm_contribution_widget.about',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'url_homepage' => [
    'name' => 'url_homepage',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Homepage Url'),
    'description' => ts('URL to Homepage.'),
    'maxlength' => 255,
    'size' => CRM_Utils_Type::HUGE,
    'where' => 'civicrm_contribution_widget.url_homepage',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_title' => [
    'name' => 'color_title',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Title Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_title',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_button' => [
    'name' => 'color_button',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Button Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_button',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_bar' => [
    'name' => 'color_bar',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Bar Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_bar',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_main_text' => [
    'name' => 'color_main_text',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Main Text Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_main_text',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_main' => [
    'name' => 'color_main',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Main Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_main',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_main_bg' => [
    'name' => 'color_main_bg',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Background Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_main_bg',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_bg' => [
    'name' => 'color_bg',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Other Background Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_bg',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_about_link' => [
    'name' => 'color_about_link',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('About Link Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_about_link',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  'color_homepage_link' => [
    'name' => 'color_homepage_link',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Homepage Link Color'),
    'maxlength' => 10,
    'size' => CRM_Utils_Type::TWELVE,
    'where' => 'civicrm_contribution_widget.color_homepage_link',
    'table_name' => 'civicrm_contribution_widget',
    'entity' => 'Widget',
    'bao' => 'CRM_Contribute_BAO_Widget',
    'localizable' => 0,
    'add' => '2.0',
  ],
  ];
  
