<?php
return [
  'id' => [
    'name' => 'id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Dedupe Rule ID'),
    'description' => ts('Unique dedupe rule id'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_rule.id',
    'table_name' => 'civicrm_dedupe_rule',
    'entity' => 'DedupeRule',
    'bao' => 'CRM_Dedupe_BAO_DedupeRule',
    'localizable' => 0,
    'html' => [
      'type' => 'Number',
    ],
    'readonly' => TRUE,
    'add' => '1.8',
  ],
  'dedupe_rule_group_id' => [
    'name' => 'dedupe_rule_group_id',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Group ID'),
    'description' => ts('The id of the rule group this rule belongs to'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_rule.dedupe_rule_group_id',
    'table_name' => 'civicrm_dedupe_rule',
    'entity' => 'DedupeRule',
    'bao' => 'CRM_Dedupe_BAO_DedupeRule',
    'localizable' => 0,
    'FKClassName' => 'CRM_Dedupe_DAO_DedupeRuleGroup',
    'html' => [
      'label' => ts("Group"),
    ],
    'add' => '1.8',
  ],
  'rule_table' => [
    'name' => 'rule_table',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Rule Table'),
    'description' => ts('The name of the table this rule is about'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_dedupe_rule.rule_table',
    'table_name' => 'civicrm_dedupe_rule',
    'entity' => 'DedupeRule',
    'bao' => 'CRM_Dedupe_BAO_DedupeRule',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'rule_field' => [
    'name' => 'rule_field',
    'type' => CRM_Utils_Type::T_STRING,
    'title' => ts('Rule Field'),
    'description' => ts('The name of the field of the table referenced in rule_table'),
    'required' => TRUE,
    'maxlength' => 64,
    'size' => CRM_Utils_Type::BIG,
    'where' => 'civicrm_dedupe_rule.rule_field',
    'table_name' => 'civicrm_dedupe_rule',
    'entity' => 'DedupeRule',
    'bao' => 'CRM_Dedupe_BAO_DedupeRule',
    'localizable' => 0,
    'add' => '1.8',
  ],
  'rule_length' => [
    'name' => 'rule_length',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Rule Length'),
    'description' => ts('The length of the matching substring'),
    'where' => 'civicrm_dedupe_rule.rule_length',
    'table_name' => 'civicrm_dedupe_rule',
    'entity' => 'DedupeRule',
    'bao' => 'CRM_Dedupe_BAO_DedupeRule',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  'rule_weight' => [
    'name' => 'rule_weight',
    'type' => CRM_Utils_Type::T_INT,
    'title' => ts('Order'),
    'description' => ts('The weight of the rule'),
    'required' => TRUE,
    'where' => 'civicrm_dedupe_rule.rule_weight',
    'table_name' => 'civicrm_dedupe_rule',
    'entity' => 'DedupeRule',
    'bao' => 'CRM_Dedupe_BAO_DedupeRule',
    'localizable' => 0,
    'html' => [
      'type' => 'Text',
    ],
    'add' => '1.8',
  ],
  ];
  
